/** @file */
/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/



#ifndef R_KINO_FIELDSPEC
#define R_KINO_FIELDSPEC 1

#include "KinoSearch/Schema/FieldSpec.h"

#define KINO_FIELDSPEC_BOILERPLATE

typedef void
(*kino_FSpec_destroy_t)(kino_FieldSpec *self);

#define Kino_FSpec_Clone(self) \
    (self)->_->clone((kino_Obj*)self)

#define Kino_FSpec_Destroy(self) \
    (self)->_->destroy((kino_Obj*)self)

#define Kino_FSpec_Equals(self, other) \
    (self)->_->equals((kino_Obj*)self, other)

#define Kino_FSpec_Hash_Code(self) \
    (self)->_->hash_code((kino_Obj*)self)

#define Kino_FSpec_Is_A(self, target_vtable) \
    (self)->_->is_a((kino_Obj*)self, target_vtable)

#define Kino_FSpec_To_String(self) \
    (self)->_->to_string((kino_Obj*)self)

#define Kino_FSpec_Serialize(self, target) \
    (self)->_->serialize((kino_Obj*)self, target)

struct KINO_FIELDSPEC_VTABLE {
    KINO_OBJ_VTABLE *_;
    chy_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
};

extern KINO_FIELDSPEC_VTABLE KINO_FIELDSPEC;

#ifdef KINO_USE_SHORT_NAMES
  #define FieldSpec kino_FieldSpec
  #define FIELDSPEC KINO_FIELDSPEC
  #define FSpec_new kino_FSpec_new
  #define FSpec_destroy kino_FSpec_destroy
  #define FSpec_Clone Kino_FSpec_Clone
  #define FSpec_Destroy Kino_FSpec_Destroy
  #define FSpec_Equals Kino_FSpec_Equals
  #define FSpec_Hash_Code Kino_FSpec_Hash_Code
  #define FSpec_Is_A Kino_FSpec_Is_A
  #define FSpec_To_String Kino_FSpec_To_String
  #define FSpec_Serialize Kino_FSpec_Serialize
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_FIELDSPEC_MEMBER_VARS \
    chy_u32_t  refcount; \
    float  boost; \
    chy_bool_t  indexed; \
    chy_bool_t  stored; \
    chy_bool_t  analyzed; \
    chy_bool_t  vectorized; \
    chy_bool_t  binary; \
    chy_bool_t  compressed; \
    struct kino_Posting * posting

#ifdef KINO_WANT_FIELDSPEC_VTABLE
KINO_FIELDSPEC_VTABLE KINO_FIELDSPEC = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_OBJ,
    "KinoSearch::Schema::FieldSpec",
    (kino_Obj_clone_t)kino_Obj_clone,
    (kino_Obj_destroy_t)kino_FSpec_destroy,
    (kino_Obj_equals_t)kino_Obj_equals,
    (kino_Obj_hash_code_t)kino_Obj_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_Obj_to_string,
    (kino_Obj_serialize_t)kino_Obj_serialize
};
#endif /* KINO_WANT_FIELDSPEC_VTABLE */

#undef KINO_FIELDSPEC_BOILERPLATE


#endif /* R_KINO_FIELDSPEC */


/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */

