---
name: KinoSearch
version: 0.20_02
author:
  - 'Marvin Humphrey <marvin at rectangular dot com>'
abstract: Search engine library.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Clone: 0.18
  Compress::Zlib: 0
  Lingua::Stem::Snowball: 0.94
  Lingua::StopWords: 0.06
build_requires:
  ExtUtils::CBuilder: 0
  ExtUtils::ParseXS: 0
provides:
  KinoSearch:
    file: lib/KinoSearch.pm
    version: 0.20_02
  KinoSearch::Analysis::Analyzer:
    file: lib/KinoSearch/Analysis/Analyzer.pm
  KinoSearch::Analysis::LCNormalizer:
    file: lib/KinoSearch/Analysis/LCNormalizer.pm
  KinoSearch::Analysis::PolyAnalyzer:
    file: lib/KinoSearch/Analysis/PolyAnalyzer.pm
  KinoSearch::Analysis::Stemmer:
    file: lib/KinoSearch/Analysis/Stemmer.pm
  KinoSearch::Analysis::Stopalizer:
    file: lib/KinoSearch/Analysis/Stopalizer.pm
  KinoSearch::Analysis::Token:
    file: lib/KinoSearch/Analysis/Token.pm
  KinoSearch::Analysis::TokenBatch:
    file: lib/KinoSearch/Analysis/TokenBatch.pm
  KinoSearch::Analysis::Tokenizer:
    file: lib/KinoSearch/Analysis/Tokenizer.pm
  KinoSearch::Contrib::LongFieldSim:
    file: lib/KinoSearch/Contrib/LongFieldSim.pm
  KinoSearch::Highlight::Encoder:
    file: lib/KinoSearch/Highlight/Encoder.pm
  KinoSearch::Highlight::Formatter:
    file: lib/KinoSearch/Highlight/Formatter.pm
  KinoSearch::Highlight::Highlighter:
    file: lib/KinoSearch/Highlight/Highlighter.pm
  KinoSearch::Highlight::SimpleHTMLEncoder:
    file: lib/KinoSearch/Highlight/SimpleHTMLEncoder.pm
  KinoSearch::Highlight::SimpleHTMLFormatter:
    file: lib/KinoSearch/Highlight/SimpleHTMLFormatter.pm
  KinoSearch::Index::CompoundFileReader:
    file: lib/KinoSearch/Index/CompoundFileReader.pm
  KinoSearch::Index::CompoundFileWriter:
    file: lib/KinoSearch/Index/CompoundFileWriter.pm
  KinoSearch::Index::DelDocs:
    file: lib/KinoSearch/Index/DelDocs.pm
  KinoSearch::Index::DocReader:
    file: lib/KinoSearch/Index/DocReader.pm
  KinoSearch::Index::DocVector:
    file: lib/KinoSearch/Index/DocVector.pm
  KinoSearch::Index::DocWriter:
    file: lib/KinoSearch/Index/DocWriter.pm
  KinoSearch::Index::IndexFileNames:
    file: lib/KinoSearch/Index/IndexFileNames.pm
  KinoSearch::Index::IndexReader:
    file: lib/KinoSearch/Index/IndexReader.pm
  KinoSearch::Index::MultiReader:
    file: lib/KinoSearch/Index/MultiReader.pm
  KinoSearch::Index::MultiTermDocs:
    file: lib/KinoSearch/Index/MultiTermDocs.pm
  KinoSearch::Index::MultiTermList:
    file: lib/KinoSearch/Index/MultiTermList.pm
  KinoSearch::Index::PostingsWriter:
    file: lib/KinoSearch/Index/PostingsWriter.pm
  KinoSearch::Index::SegInfo:
    file: lib/KinoSearch/Index/SegInfo.pm
  KinoSearch::Index::SegInfos:
    file: lib/KinoSearch/Index/SegInfos.pm
  KinoSearch::Index::SegReader:
    file: lib/KinoSearch/Index/SegReader.pm
  KinoSearch::Index::SegTermDocs:
    file: lib/KinoSearch/Index/SegTermDocs.pm
  KinoSearch::Index::SegTermList:
    file: lib/KinoSearch/Index/SegTermList.pm
  KinoSearch::Index::SegWriter:
    file: lib/KinoSearch/Index/SegWriter.pm
  KinoSearch::Index::Term:
    file: lib/KinoSearch/Index/Term.pm
  KinoSearch::Index::TermDocs:
    file: lib/KinoSearch/Index/TermDocs.pm
  KinoSearch::Index::TermInfo:
    file: lib/KinoSearch/Index/TermInfo.pm
  KinoSearch::Index::TermList:
    file: lib/KinoSearch/Index/TermList.pm
  KinoSearch::Index::TermListCache:
    file: lib/KinoSearch/Index/TermListCache.pm
  KinoSearch::Index::TermListReader:
    file: lib/KinoSearch/Index/TermListReader.pm
  KinoSearch::Index::TermListWriter:
    file: lib/KinoSearch/Index/TermListWriter.pm
  KinoSearch::Index::TermVector:
    file: lib/KinoSearch/Index/TermVector.pm
  KinoSearch::Index::TermVectorsReader:
    file: lib/KinoSearch/Index/TermVectorsReader.pm
  KinoSearch::Index::TermVectorsWriter:
    file: lib/KinoSearch/Index/TermVectorsWriter.pm
  KinoSearch::InvIndex:
    file: lib/KinoSearch/InvIndex.pm
  KinoSearch::InvIndexer:
    file: lib/KinoSearch/InvIndexer.pm
  KinoSearch::QueryParser::QueryParser:
    file: lib/KinoSearch/QueryParser/QueryParser.pm
  KinoSearch::Schema:
    file: lib/KinoSearch/Schema.pm
  KinoSearch::Schema::FieldSpec:
    file: lib/KinoSearch/Schema/FieldSpec.pm
  KinoSearch::Search::BooleanClause:
    file: lib/KinoSearch/Search/BooleanClause.pm
  KinoSearch::Search::BooleanQuery:
    file: lib/KinoSearch/Search/BooleanQuery.pm
  KinoSearch::Search::BooleanScorer:
    file: lib/KinoSearch/Search/BooleanScorer.pm
  KinoSearch::Search::BooleanWeight:
    file: lib/KinoSearch/Search/BooleanQuery.pm
  KinoSearch::Search::CacheDFSource:
    file: lib/KinoSearch/Search/MultiSearcher.pm
  KinoSearch::Search::FieldDoc:
    file: lib/KinoSearch/Search/FieldDoc.pm
  KinoSearch::Search::FieldDocCollator:
    file: lib/KinoSearch/Search/FieldDocCollator.pm
  KinoSearch::Search::HitCollector:
    file: lib/KinoSearch/Search/HitCollector.pm
  KinoSearch::Search::HitQueue:
    file: lib/KinoSearch/Search/HitQueue.pm
  KinoSearch::Search::Hits:
    file: lib/KinoSearch/Search/Hits.pm
  KinoSearch::Search::MultiSearcher:
    file: lib/KinoSearch/Search/MultiSearcher.pm
  KinoSearch::Search::PhraseQuery:
    file: lib/KinoSearch/Search/PhraseQuery.pm
  KinoSearch::Search::PhraseScorer:
    file: lib/KinoSearch/Search/PhraseScorer.pm
  KinoSearch::Search::PhraseWeight:
    file: lib/KinoSearch/Search/PhraseQuery.pm
  KinoSearch::Search::Query:
    file: lib/KinoSearch/Search/Query.pm
  KinoSearch::Search::QueryFilter:
    file: lib/KinoSearch/Search/QueryFilter.pm
  KinoSearch::Search::RangeFilter:
    file: lib/KinoSearch/Search/RangeFilter.pm
  KinoSearch::Search::ScoreDoc:
    file: lib/KinoSearch/Search/ScoreDoc.pm
  KinoSearch::Search::Scorer:
    file: lib/KinoSearch/Search/Scorer.pm
  KinoSearch::Search::SearchClient:
    file: lib/KinoSearch/Search/SearchClient.pm
  KinoSearch::Search::SearchServer:
    file: lib/KinoSearch/Search/SearchServer.pm
  KinoSearch::Search::Searchable:
    file: lib/KinoSearch/Search/Searchable.pm
  KinoSearch::Search::Similarity:
    file: lib/KinoSearch/Search/Similarity.pm
  KinoSearch::Search::SortCollector:
    file: lib/KinoSearch/Search/SortCollector.pm
  KinoSearch::Search::SortSpec:
    file: lib/KinoSearch/Search/SortSpec.pm
  KinoSearch::Search::SortedHitQueue:
    file: lib/KinoSearch/Search/SortedHitQueue.pm
  KinoSearch::Search::TermQuery:
    file: lib/KinoSearch/Search/TermQuery.pm
  KinoSearch::Search::TermScorer:
    file: lib/KinoSearch/Search/TermScorer.pm
  KinoSearch::Search::TermWeight:
    file: lib/KinoSearch/Search/TermQuery.pm
  KinoSearch::Search::TopDocCollector:
    file: lib/KinoSearch/Search/TopDocCollector.pm
  KinoSearch::Search::TopDocs:
    file: lib/KinoSearch/Search/TopDocs.pm
  KinoSearch::Search::Weight:
    file: lib/KinoSearch/Search/Weight.pm
  KinoSearch::Searcher:
    file: lib/KinoSearch/Searcher.pm
  KinoSearch::Store::FSFileDes:
    file: lib/KinoSearch/Store/FSFileDes.pm
  KinoSearch::Store::FSFolder:
    file: lib/KinoSearch/Store/FSFolder.pm
  KinoSearch::Store::FileDes:
    file: lib/KinoSearch/Store/FileDes.pm
  KinoSearch::Store::Folder:
    file: lib/KinoSearch/Store/Folder.pm
  KinoSearch::Store::InStream:
    file: lib/KinoSearch/Store/InStream.pm
  KinoSearch::Store::Lock:
    file: lib/KinoSearch/Store/Lock.pm
  KinoSearch::Store::OutStream:
    file: lib/KinoSearch/Store/OutStream.pm
  KinoSearch::Store::RAMFileDes:
    file: lib/KinoSearch/Store/RAMFileDes.pm
  KinoSearch::Store::RAMFolder:
    file: lib/KinoSearch/Store/RAMFolder.pm
  KinoSearch::Util::BitVector:
    file: lib/KinoSearch/Util/BitVector.pm
  KinoSearch::Util::ByteBuf:
    file: lib/KinoSearch/Util/ByteBuf.pm
  KinoSearch::Util::CClass:
    file: lib/KinoSearch/Util/CClass.pm
  KinoSearch::Util::Class:
    file: lib/KinoSearch/Util/Class.pm
  KinoSearch::Util::DynVirtualTable:
    file: lib/KinoSearch/Util/DynVirtualTable.pm
  KinoSearch::Util::Hash:
    file: lib/KinoSearch/Util/Hash.pm
  KinoSearch::Util::Int:
    file: lib/KinoSearch/Util/Int.pm
  KinoSearch::Util::IntMap:
    file: lib/KinoSearch/Util/IntMap.pm
  KinoSearch::Util::Obj:
    file: lib/KinoSearch/Util/Obj.pm
  KinoSearch::Util::PriorityQueue:
    file: lib/KinoSearch/Util/PriorityQueue.pm
  KinoSearch::Util::SortExternal:
    file: lib/KinoSearch/Util/SortExternal.pm
  KinoSearch::Util::StringHelper:
    file: lib/KinoSearch/Util/StringHelper.pm
  KinoSearch::Util::ToStringUtils:
    file: lib/KinoSearch/Util/ToStringUtils.pm
  KinoSearch::Util::ToolSet:
    file: lib/KinoSearch/Util/ToolSet.pm
  KinoSearch::Util::VArray:
    file: lib/KinoSearch/Util/VArray.pm
  KinoSearch::Util::VerifyArgs:
    file: lib/KinoSearch/Util/VerifyArgs.pm
  KinoSearch::Util::ViewByteBuf:
    file: lib/KinoSearch/Util/ViewByteBuf.pm
  KinoSearch::Util::YAML:
    file: lib/KinoSearch/Util/YAML.pm
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
no_index:
  directory:
    - t
    - buildlib
    - buildbin
    - xshelper
    - sample
  file:
    - Build
    - MANIFEST
    - Changes
    - ApacheLicense2.0.txt
    - META.yml
    - Makefile.PL
    - Build.PL
    - ppport.h
    - lib/KinoSearch/Search/TopDocs.pm
    - lib/KinoSearch/Search/BooleanClause.pm
    - lib/KinoSearch/Search/Weight.pm
    - lib/KinoSearch/Search/FieldDocCollator.pm
    - lib/KinoSearch/Search/TermScorer.pm
    - lib/KinoSearch/Search/HitQueue.pm
    - lib/KinoSearch/Search/Searchable.pm
    - lib/KinoSearch/Search/HitCollector.pm
    - lib/KinoSearch/Search/FieldDoc.pm
    - lib/KinoSearch/Search/SortedHitQueue.pm
    - lib/KinoSearch/Search/BooleanScorer.pm
    - lib/KinoSearch/Search/Scorer.pm
    - lib/KinoSearch/Search/TopDocCollector.pm
    - lib/KinoSearch/Search/PhraseScorer.pm
    - lib/KinoSearch/Search/ScoreDoc.pm
    - lib/KinoSearch/Search/SortCollector.pm
    - lib/KinoSearch/Index/SegInfos.pm
    - lib/KinoSearch/Index/CompoundFileReader.pm
    - lib/KinoSearch/Index/TermListReader.pm
    - lib/KinoSearch/Index/SegWriter.pm
    - lib/KinoSearch/Index/MultiReader.pm
    - lib/KinoSearch/Index/DelDocs.pm
    - lib/KinoSearch/Index/SegTermDocs.pm
    - lib/KinoSearch/Index/TermDocs.pm
    - lib/KinoSearch/Index/DocVector.pm
    - lib/KinoSearch/Index/CompoundFileWriter.pm
    - lib/KinoSearch/Index/TermInfo.pm
    - lib/KinoSearch/Index/DocReader.pm
    - lib/KinoSearch/Index/MultiTermDocs.pm
    - lib/KinoSearch/Index/IndexReader.pm
    - lib/KinoSearch/Index/TermVector.pm
    - lib/KinoSearch/Index/SegTermList.pm
    - lib/KinoSearch/Index/TermVectorsWriter.pm
    - lib/KinoSearch/Index/IndexFileNames.pm
    - lib/KinoSearch/Index/SegReader.pm
    - lib/KinoSearch/Index/TermList.pm
    - lib/KinoSearch/Index/PostingsWriter.pm
    - lib/KinoSearch/Index/DocWriter.pm
    - lib/KinoSearch/Index/TermListCache.pm
    - lib/KinoSearch/Index/TermVectorsReader.pm
    - lib/KinoSearch/Index/TermListWriter.pm
    - lib/KinoSearch/Index/SegInfo.pm
    - lib/KinoSearch/Index/MultiTermList.pm
    - lib/KinoSearch/Store/FSFileDes.pm
    - lib/KinoSearch/Store/Lock.pm
    - lib/KinoSearch/Store/FileDes.pm
    - lib/KinoSearch/Store/InStream.pm
    - lib/KinoSearch/Store/OutStream.pm
    - lib/KinoSearch/Store/RAMFileDes.pm
    - lib/KinoSearch/Util/StringHelper.pm
    - lib/KinoSearch/Util/VArray.pm
    - lib/KinoSearch/Util/PriorityQueue.pm
    - lib/KinoSearch/Util/CClass.pm
    - lib/KinoSearch/Util/IntMap.pm
    - lib/KinoSearch/Util/Obj.pm
    - lib/KinoSearch/Util/SortExternal.pm
    - lib/KinoSearch/Util/ToStringUtils.pm
    - lib/KinoSearch/Util/BitVector.pm
    - lib/KinoSearch/Util/VerifyArgs.pm
    - lib/KinoSearch/Util/Hash.pm
    - lib/KinoSearch/Util/ViewByteBuf.pm
    - lib/KinoSearch/Util/ByteBuf.pm
    - lib/KinoSearch/Util/YAML.pm
    - lib/KinoSearch/Util/DynVirtualTable.pm
    - lib/KinoSearch/Util/Int.pm
