/** @file */
/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/



#ifndef R_KINO_ANDNOTSCORER
#define R_KINO_ANDNOTSCORER 1

#include "KinoSearch/Search/ANDNOTScorer.h"

#define KINO_ANDNOTSCORER_BOILERPLATE

typedef void
(*kino_ANDNOTScorer_destroy_t)(kino_ANDNOTScorer *self);

typedef chy_bool_t
(*kino_ANDNOTScorer_next_t)(kino_ANDNOTScorer *self);

typedef chy_u32_t
(*kino_ANDNOTScorer_doc_t)(kino_ANDNOTScorer *self);

typedef struct kino_Tally*
(*kino_ANDNOTScorer_tally_t)(kino_ANDNOTScorer *self);

typedef chy_bool_t
(*kino_ANDNOTScorer_skip_to_t)(kino_ANDNOTScorer *self, chy_u32_t target);

#define Kino_ANDNOTScorer_Clone(self) \
    (self)->_->clone((kino_Obj*)self)

#define Kino_ANDNOTScorer_Destroy(self) \
    (self)->_->destroy((kino_Obj*)self)

#define Kino_ANDNOTScorer_Equals(self, other) \
    (self)->_->equals((kino_Obj*)self, other)

#define Kino_ANDNOTScorer_Hash_Code(self) \
    (self)->_->hash_code((kino_Obj*)self)

#define Kino_ANDNOTScorer_Is_A(self, target_vtable) \
    (self)->_->is_a((kino_Obj*)self, target_vtable)

#define Kino_ANDNOTScorer_To_String(self) \
    (self)->_->to_string((kino_Obj*)self)

#define Kino_ANDNOTScorer_Serialize(self, target) \
    (self)->_->serialize((kino_Obj*)self, target)

#define Kino_ANDNOTScorer_Next(self) \
    (self)->_->next((kino_Scorer*)self)

#define Kino_ANDNOTScorer_Doc(self) \
    (self)->_->doc((kino_Scorer*)self)

#define Kino_ANDNOTScorer_Tally(self) \
    (self)->_->tally((kino_Scorer*)self)

#define Kino_ANDNOTScorer_Skip_To(self, target) \
    (self)->_->skip_to((kino_Scorer*)self, target)

#define Kino_ANDNOTScorer_Collect(self, hc, start, end, hits_per_seg, seg_starts) \
    (self)->_->collect((kino_Scorer*)self, hc, start, end, hits_per_seg, seg_starts)

struct KINO_ANDNOTSCORER_VTABLE {
    KINO_OBJ_VTABLE *_;
    chy_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
    kino_Scorer_next_t next;
    kino_Scorer_doc_t doc;
    kino_Scorer_tally_t tally;
    kino_Scorer_skip_to_t skip_to;
    kino_Scorer_collect_t collect;
};

extern KINO_ANDNOTSCORER_VTABLE KINO_ANDNOTSCORER;

#ifdef KINO_USE_SHORT_NAMES
  #define ANDNOTScorer kino_ANDNOTScorer
  #define ANDNOTSCORER KINO_ANDNOTSCORER
  #define ANDNOTScorer_new kino_ANDNOTScorer_new
  #define ANDNOTScorer_destroy kino_ANDNOTScorer_destroy
  #define ANDNOTScorer_next kino_ANDNOTScorer_next
  #define ANDNOTScorer_doc kino_ANDNOTScorer_doc
  #define ANDNOTScorer_tally kino_ANDNOTScorer_tally
  #define ANDNOTScorer_skip_to kino_ANDNOTScorer_skip_to
  #define ANDNOTScorer_Clone Kino_ANDNOTScorer_Clone
  #define ANDNOTScorer_Destroy Kino_ANDNOTScorer_Destroy
  #define ANDNOTScorer_Equals Kino_ANDNOTScorer_Equals
  #define ANDNOTScorer_Hash_Code Kino_ANDNOTScorer_Hash_Code
  #define ANDNOTScorer_Is_A Kino_ANDNOTScorer_Is_A
  #define ANDNOTScorer_To_String Kino_ANDNOTScorer_To_String
  #define ANDNOTScorer_Serialize Kino_ANDNOTScorer_Serialize
  #define ANDNOTScorer_Next Kino_ANDNOTScorer_Next
  #define ANDNOTScorer_Doc Kino_ANDNOTScorer_Doc
  #define ANDNOTScorer_Tally Kino_ANDNOTScorer_Tally
  #define ANDNOTScorer_Skip_To Kino_ANDNOTScorer_Skip_To
  #define ANDNOTScorer_Collect Kino_ANDNOTScorer_Collect
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_ANDNOTSCORER_MEMBER_VARS \
    chy_u32_t  refcount; \
    struct kino_Similarity * sim; \
    kino_Scorer * and_scorer; \
    kino_Scorer * not_scorer; \
    chy_bool_t  first_time

#ifdef KINO_WANT_ANDNOTSCORER_VTABLE
KINO_ANDNOTSCORER_VTABLE KINO_ANDNOTSCORER = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_SCORER,
    "KinoSearch::Search::ANDNOTScorer",
    (kino_Obj_clone_t)kino_Obj_clone,
    (kino_Obj_destroy_t)kino_ANDNOTScorer_destroy,
    (kino_Obj_equals_t)kino_Obj_equals,
    (kino_Obj_hash_code_t)kino_Obj_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_Obj_to_string,
    (kino_Obj_serialize_t)kino_Obj_serialize,
    (kino_Scorer_next_t)kino_ANDNOTScorer_next,
    (kino_Scorer_doc_t)kino_ANDNOTScorer_doc,
    (kino_Scorer_tally_t)kino_ANDNOTScorer_tally,
    (kino_Scorer_skip_to_t)kino_ANDNOTScorer_skip_to,
    (kino_Scorer_collect_t)kino_Scorer_collect
};
#endif /* KINO_WANT_ANDNOTSCORER_VTABLE */

#undef KINO_ANDNOTSCORER_BOILERPLATE


#endif /* R_KINO_ANDNOTSCORER */


/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */

