/** @file */
/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/



#ifndef R_KINO_ANDSCORER
#define R_KINO_ANDSCORER 1

#include "KinoSearch/Search/ANDScorer.h"

#define KINO_ANDSCORER_BOILERPLATE

typedef void
(*kino_ANDScorer_destroy_t)(kino_ANDScorer *self);

typedef chy_bool_t
(*kino_ANDScorer_next_t)(kino_ANDScorer *self);

typedef chy_u32_t
(*kino_ANDScorer_doc_t)(kino_ANDScorer *self);

typedef struct kino_Tally*
(*kino_ANDScorer_tally_t)(kino_ANDScorer *self);

typedef chy_bool_t
(*kino_ANDScorer_skip_to_t)(kino_ANDScorer *self, chy_u32_t target);

typedef void
(*kino_ANDScorer_add_subscorer_t)(kino_ANDScorer* self, 
                              kino_Scorer* subscorer);

#define Kino_ANDScorer_Clone(self) \
    (self)->_->clone((kino_Obj*)self)

#define Kino_ANDScorer_Destroy(self) \
    (self)->_->destroy((kino_Obj*)self)

#define Kino_ANDScorer_Equals(self, other) \
    (self)->_->equals((kino_Obj*)self, other)

#define Kino_ANDScorer_Hash_Code(self) \
    (self)->_->hash_code((kino_Obj*)self)

#define Kino_ANDScorer_Is_A(self, target_vtable) \
    (self)->_->is_a((kino_Obj*)self, target_vtable)

#define Kino_ANDScorer_To_String(self) \
    (self)->_->to_string((kino_Obj*)self)

#define Kino_ANDScorer_Serialize(self, target) \
    (self)->_->serialize((kino_Obj*)self, target)

#define Kino_ANDScorer_Next(self) \
    (self)->_->next((kino_Scorer*)self)

#define Kino_ANDScorer_Doc(self) \
    (self)->_->doc((kino_Scorer*)self)

#define Kino_ANDScorer_Tally(self) \
    (self)->_->tally((kino_Scorer*)self)

#define Kino_ANDScorer_Skip_To(self, target) \
    (self)->_->skip_to((kino_Scorer*)self, target)

#define Kino_ANDScorer_Collect(self, hc, start, end, hits_per_seg, seg_starts) \
    (self)->_->collect((kino_Scorer*)self, hc, start, end, hits_per_seg, seg_starts)

#define Kino_ANDScorer_Add_Subscorer(self, subscorer) \
    (self)->_->add_subscorer((kino_ANDScorer*)self, subscorer)

struct KINO_ANDSCORER_VTABLE {
    KINO_OBJ_VTABLE *_;
    chy_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
    kino_Scorer_next_t next;
    kino_Scorer_doc_t doc;
    kino_Scorer_tally_t tally;
    kino_Scorer_skip_to_t skip_to;
    kino_Scorer_collect_t collect;
    kino_ANDScorer_add_subscorer_t add_subscorer;
};

extern KINO_ANDSCORER_VTABLE KINO_ANDSCORER;

#ifdef KINO_USE_SHORT_NAMES
  #define ANDScorer kino_ANDScorer
  #define ANDSCORER KINO_ANDSCORER
  #define ANDScorer_new kino_ANDScorer_new
  #define ANDScorer_destroy kino_ANDScorer_destroy
  #define ANDScorer_next kino_ANDScorer_next
  #define ANDScorer_doc kino_ANDScorer_doc
  #define ANDScorer_tally kino_ANDScorer_tally
  #define ANDScorer_skip_to kino_ANDScorer_skip_to
  #define ANDScorer_add_subscorer_t kino_ANDScorer_add_subscorer_t
  #define ANDScorer_add_subscorer kino_ANDScorer_add_subscorer
  #define ANDScorer_Clone Kino_ANDScorer_Clone
  #define ANDScorer_Destroy Kino_ANDScorer_Destroy
  #define ANDScorer_Equals Kino_ANDScorer_Equals
  #define ANDScorer_Hash_Code Kino_ANDScorer_Hash_Code
  #define ANDScorer_Is_A Kino_ANDScorer_Is_A
  #define ANDScorer_To_String Kino_ANDScorer_To_String
  #define ANDScorer_Serialize Kino_ANDScorer_Serialize
  #define ANDScorer_Next Kino_ANDScorer_Next
  #define ANDScorer_Doc Kino_ANDScorer_Doc
  #define ANDScorer_Tally Kino_ANDScorer_Tally
  #define ANDScorer_Skip_To Kino_ANDScorer_Skip_To
  #define ANDScorer_Collect Kino_ANDScorer_Collect
  #define ANDScorer_Add_Subscorer Kino_ANDScorer_Add_Subscorer
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_ANDSCORER_MEMBER_VARS \
    chy_u32_t  refcount; \
    struct kino_Similarity * sim; \
    float  coord; \
    struct kino_Tally * tally; \
    kino_Scorer ** subscorers; \
    size_t  cap; \
    chy_u32_t  num_subs; \
    chy_bool_t  more; \
    chy_bool_t  first_time; \
    struct kino_ByteBuf * raw_prox_bb

#ifdef KINO_WANT_ANDSCORER_VTABLE
KINO_ANDSCORER_VTABLE KINO_ANDSCORER = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_SCORER,
    "KinoSearch::Search::ANDScorer",
    (kino_Obj_clone_t)kino_Obj_clone,
    (kino_Obj_destroy_t)kino_ANDScorer_destroy,
    (kino_Obj_equals_t)kino_Obj_equals,
    (kino_Obj_hash_code_t)kino_Obj_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_Obj_to_string,
    (kino_Obj_serialize_t)kino_Obj_serialize,
    (kino_Scorer_next_t)kino_ANDScorer_next,
    (kino_Scorer_doc_t)kino_ANDScorer_doc,
    (kino_Scorer_tally_t)kino_ANDScorer_tally,
    (kino_Scorer_skip_to_t)kino_ANDScorer_skip_to,
    (kino_Scorer_collect_t)kino_Scorer_collect,
    (kino_ANDScorer_add_subscorer_t)kino_ANDScorer_add_subscorer
};
#endif /* KINO_WANT_ANDSCORER_VTABLE */

#undef KINO_ANDSCORER_BOILERPLATE


#endif /* R_KINO_ANDSCORER */


/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */

