/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/

#ifndef R_KINO_FDOCCOLLATOR
#define R_KINO_FDOCCOLLATOR 1

#include "KinoSearch/Search/FieldDocCollator.h"

typedef void
(*kino_FDocCollator_destroy_t)(kino_FieldDocCollator *self);

typedef kino_bool_t
(*kino_FDocCollator_compare_t)(kino_FieldDocCollator *self, 
                          kino_u32_t doc_num_a, float score_a, 
                          kino_u32_t doc_num_b, float score_b);

#define Kino_FDocCollator_Clone(_self) \
    (_self)->_->clone((kino_Obj*)_self)

#define Kino_FDocCollator_Destroy(_self) \
    (_self)->_->destroy((kino_Obj*)_self)

#define Kino_FDocCollator_Equals(_self, _arg1) \
    (_self)->_->equals((kino_Obj*)_self, _arg1)

#define Kino_FDocCollator_Hash_Code(_self) \
    (_self)->_->hash_code((kino_Obj*)_self)

#define Kino_FDocCollator_Is_A(_self, _arg1) \
    (_self)->_->is_a((kino_Obj*)_self, _arg1)

#define Kino_FDocCollator_To_String(_self) \
    (_self)->_->to_string((kino_Obj*)_self)

#define Kino_FDocCollator_Serialize(_self, _arg1) \
    (_self)->_->serialize((kino_Obj*)_self, _arg1)

#define Kino_FDocCollator_Compare(_self, _arg1, _arg2, _arg3, _arg4) \
    (_self)->_->compare((kino_FieldDocCollator*)_self, _arg1, _arg2, _arg3, _arg4)

struct KINO_FIELDDOCCOLLATOR_VTABLE {
    KINO_OBJ_VTABLE *_;
    kino_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
    kino_FDocCollator_compare_t compare;
};

extern KINO_FIELDDOCCOLLATOR_VTABLE KINO_FIELDDOCCOLLATOR;

#ifdef KINO_USE_SHORT_NAMES
  #define FieldDocCollator kino_FieldDocCollator
  #define FIELDDOCCOLLATOR KINO_FIELDDOCCOLLATOR
  #define FDocCollator_new kino_FDocCollator_new
  #define FDocCollator_add kino_FDocCollator_add
  #define FDocCollator_less_than kino_FDocCollator_less_than
  #define FDocCollator_destroy kino_FDocCollator_destroy
  #define FDocCollator_compare_t kino_FDocCollator_compare_t
  #define FDocCollator_compare kino_FDocCollator_compare
  #define FDocCollator_Clone Kino_FDocCollator_Clone
  #define FDocCollator_Destroy Kino_FDocCollator_Destroy
  #define FDocCollator_Equals Kino_FDocCollator_Equals
  #define FDocCollator_Hash_Code Kino_FDocCollator_Hash_Code
  #define FDocCollator_Is_A Kino_FDocCollator_Is_A
  #define FDocCollator_To_String Kino_FDocCollator_To_String
  #define FDocCollator_Serialize Kino_FDocCollator_Serialize
  #define FDocCollator_Compare Kino_FDocCollator_Compare
  #define FIELDDOCCOLLATOR KINO_FIELDDOCCOLLATOR
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_FIELDDOCCOLLATOR_MEMBER_VARS \
    kino_u32_t  cap; \
    kino_u32_t  size; \
    struct kino_IntMap ** sort_caches; \
    kino_bool_t * reversed;


#ifdef KINO_WANT_FIELDDOCCOLLATOR_VTABLE
KINO_FIELDDOCCOLLATOR_VTABLE KINO_FIELDDOCCOLLATOR = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_OBJ,
    "KinoSearch::Search::FieldDocCollator",
    (kino_Obj_clone_t)kino_Obj_clone,
    (kino_Obj_destroy_t)kino_FDocCollator_destroy,
    (kino_Obj_equals_t)kino_Obj_equals,
    (kino_Obj_hash_code_t)kino_Obj_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_Obj_to_string,
    (kino_Obj_serialize_t)kino_Obj_serialize,
    (kino_FDocCollator_compare_t)kino_FDocCollator_compare
};
#endif /* KINO_WANT_FIELDDOCCOLLATOR_VTABLE */

#endif /* R_KINO_FDOCCOLLATOR */

/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */
