/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/

#ifndef R_KINO_HC
#define R_KINO_HC 1

#include "KinoSearch/Search/HitCollector.h"

typedef void
(*kino_HC_destroy_t)(kino_HitCollector *self);

#define Kino_HC_Clone(_self) \
    (_self)->_->clone((kino_Obj*)_self)

#define Kino_HC_Destroy(_self) \
    (_self)->_->destroy((kino_Obj*)_self)

#define Kino_HC_Equals(_self, _arg1) \
    (_self)->_->equals((kino_Obj*)_self, _arg1)

#define Kino_HC_Hash_Code(_self) \
    (_self)->_->hash_code((kino_Obj*)_self)

#define Kino_HC_Is_A(_self, _arg1) \
    (_self)->_->is_a((kino_Obj*)_self, _arg1)

#define Kino_HC_To_String(_self) \
    (_self)->_->to_string((kino_Obj*)_self)

#define Kino_HC_Serialize(_self, _arg1) \
    (_self)->_->serialize((kino_Obj*)_self, _arg1)

struct KINO_HITCOLLECTOR_VTABLE {
    KINO_OBJ_VTABLE *_;
    kino_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
};

extern KINO_HITCOLLECTOR_VTABLE KINO_HITCOLLECTOR;

#ifdef KINO_USE_SHORT_NAMES
  #define HitCollector kino_HitCollector
  #define HITCOLLECTOR KINO_HITCOLLECTOR
  #define HC_new kino_HC_new
  #define HC_new_bit_coll kino_HC_new_bit_coll
  #define HC_new_offset_coll kino_HC_new_offset_coll
  #define HC_new_filt_coll kino_HC_new_filt_coll
  #define HC_new_range_coll kino_HC_new_range_coll
  #define HC_destroy kino_HC_destroy
  #define HC_Clone Kino_HC_Clone
  #define HC_Destroy Kino_HC_Destroy
  #define HC_Equals Kino_HC_Equals
  #define HC_Hash_Code Kino_HC_Hash_Code
  #define HC_Is_A Kino_HC_Is_A
  #define HC_To_String Kino_HC_To_String
  #define HC_Serialize Kino_HC_Serialize
  #define HITCOLLECTOR KINO_HITCOLLECTOR
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_HITCOLLECTOR_MEMBER_VARS \
    kino_HC_collect_t  collect; \
    kino_HC_release_t  release; \
    void * data;


#ifdef KINO_WANT_HITCOLLECTOR_VTABLE
KINO_HITCOLLECTOR_VTABLE KINO_HITCOLLECTOR = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_OBJ,
    "KinoSearch::Search::HitCollector",
    (kino_Obj_clone_t)kino_Obj_clone,
    (kino_Obj_destroy_t)kino_HC_destroy,
    (kino_Obj_equals_t)kino_Obj_equals,
    (kino_Obj_hash_code_t)kino_Obj_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_Obj_to_string,
    (kino_Obj_serialize_t)kino_Obj_serialize
};
#endif /* KINO_WANT_HITCOLLECTOR_VTABLE */

#endif /* R_KINO_HC */

/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */
