/** @file */
/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/



#ifndef R_KINO_MATCHFIELDSCORER
#define R_KINO_MATCHFIELDSCORER 1

#include "KinoSearch/Search/MatchFieldScorer.h"

#define KINO_MATCHFIELDSCORER_BOILERPLATE

typedef void
(*kino_MatchFieldScorer_destroy_t)(kino_MatchFieldScorer *self);

typedef chy_bool_t
(*kino_MatchFieldScorer_next_t)(kino_MatchFieldScorer* self);

typedef chy_u32_t
(*kino_MatchFieldScorer_doc_t)(kino_MatchFieldScorer* self);

typedef struct kino_Tally*
(*kino_MatchFieldScorer_tally_t)(kino_MatchFieldScorer* self);

#define Kino_MatchFieldScorer_Clone(self) \
    (self)->_->clone((kino_Obj*)self)

#define Kino_MatchFieldScorer_Destroy(self) \
    (self)->_->destroy((kino_Obj*)self)

#define Kino_MatchFieldScorer_Equals(self, other) \
    (self)->_->equals((kino_Obj*)self, other)

#define Kino_MatchFieldScorer_Hash_Code(self) \
    (self)->_->hash_code((kino_Obj*)self)

#define Kino_MatchFieldScorer_Is_A(self, target_vtable) \
    (self)->_->is_a((kino_Obj*)self, target_vtable)

#define Kino_MatchFieldScorer_To_String(self) \
    (self)->_->to_string((kino_Obj*)self)

#define Kino_MatchFieldScorer_Serialize(self, target) \
    (self)->_->serialize((kino_Obj*)self, target)

#define Kino_MatchFieldScorer_Next(self) \
    (self)->_->next((kino_Scorer*)self)

#define Kino_MatchFieldScorer_Doc(self) \
    (self)->_->doc((kino_Scorer*)self)

#define Kino_MatchFieldScorer_Tally(self) \
    (self)->_->tally((kino_Scorer*)self)

#define Kino_MatchFieldScorer_Skip_To(self, target) \
    (self)->_->skip_to((kino_Scorer*)self, target)

#define Kino_MatchFieldScorer_Collect(self, hc, start, end, hits_per_seg, seg_starts) \
    (self)->_->collect((kino_Scorer*)self, hc, start, end, hits_per_seg, seg_starts)

#define Kino_MatchFieldScorer_Max_Matchers(self) \
    (self)->_->max_matchers((kino_Scorer*)self)

struct KINO_MATCHFIELDSCORER_VTABLE {
    KINO_OBJ_VTABLE *_;
    chy_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
    kino_Scorer_next_t next;
    kino_Scorer_doc_t doc;
    kino_Scorer_tally_t tally;
    kino_Scorer_skip_to_t skip_to;
    kino_Scorer_collect_t collect;
    kino_Scorer_max_matchers_t max_matchers;
};

extern KINO_MATCHFIELDSCORER_VTABLE KINO_MATCHFIELDSCORER;

#ifdef KINO_USE_SHORT_NAMES
  #define MatchFieldScorer kino_MatchFieldScorer
  #define MATCHFIELDSCORER KINO_MATCHFIELDSCORER
  #define MatchFieldScorer_new kino_MatchFieldScorer_new
  #define MatchFieldScorer_destroy kino_MatchFieldScorer_destroy
  #define MatchFieldScorer_next kino_MatchFieldScorer_next
  #define MatchFieldScorer_doc kino_MatchFieldScorer_doc
  #define MatchFieldScorer_tally kino_MatchFieldScorer_tally
  #define MatchFieldScorer_Clone Kino_MatchFieldScorer_Clone
  #define MatchFieldScorer_Destroy Kino_MatchFieldScorer_Destroy
  #define MatchFieldScorer_Equals Kino_MatchFieldScorer_Equals
  #define MatchFieldScorer_Hash_Code Kino_MatchFieldScorer_Hash_Code
  #define MatchFieldScorer_Is_A Kino_MatchFieldScorer_Is_A
  #define MatchFieldScorer_To_String Kino_MatchFieldScorer_To_String
  #define MatchFieldScorer_Serialize Kino_MatchFieldScorer_Serialize
  #define MatchFieldScorer_Next Kino_MatchFieldScorer_Next
  #define MatchFieldScorer_Doc Kino_MatchFieldScorer_Doc
  #define MatchFieldScorer_Tally Kino_MatchFieldScorer_Tally
  #define MatchFieldScorer_Skip_To Kino_MatchFieldScorer_Skip_To
  #define MatchFieldScorer_Collect Kino_MatchFieldScorer_Collect
  #define MatchFieldScorer_Max_Matchers Kino_MatchFieldScorer_Max_Matchers
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_MATCHFIELDSCORER_MEMBER_VARS \
    chy_u32_t  refcount; \
    struct kino_Similarity * sim; \
    struct kino_Tally * tally; \
    struct kino_IntMap * sort_cache; \
    chy_i32_t  doc_num; \
    struct kino_Native * weight

#ifdef KINO_WANT_MATCHFIELDSCORER_VTABLE
KINO_MATCHFIELDSCORER_VTABLE KINO_MATCHFIELDSCORER = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_SCORER,
    "KinoSearch::Search::MatchFieldScorer",
    (kino_Obj_clone_t)kino_Obj_clone,
    (kino_Obj_destroy_t)kino_MatchFieldScorer_destroy,
    (kino_Obj_equals_t)kino_Obj_equals,
    (kino_Obj_hash_code_t)kino_Obj_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_Obj_to_string,
    (kino_Obj_serialize_t)kino_Obj_serialize,
    (kino_Scorer_next_t)kino_MatchFieldScorer_next,
    (kino_Scorer_doc_t)kino_MatchFieldScorer_doc,
    (kino_Scorer_tally_t)kino_MatchFieldScorer_tally,
    (kino_Scorer_skip_to_t)kino_Scorer_skip_to,
    (kino_Scorer_collect_t)kino_Scorer_collect,
    (kino_Scorer_max_matchers_t)kino_Scorer_max_matchers
};
#endif /* KINO_WANT_MATCHFIELDSCORER_VTABLE */

#undef KINO_MATCHFIELDSCORER_BOILERPLATE


#endif /* R_KINO_MATCHFIELDSCORER */


/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */

