/** @file */
/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/



#ifndef R_KINO_ORSCORER
#define R_KINO_ORSCORER 1

#include "KinoSearch/Search/ORScorer.h"

#define KINO_ORSCORER_BOILERPLATE

typedef void
(*kino_ORScorer_destroy_t)(kino_ORScorer *self);

typedef chy_bool_t
(*kino_ORScorer_next_t)(kino_ORScorer *self);

typedef chy_u32_t
(*kino_ORScorer_doc_t)(kino_ORScorer *self);

typedef struct kino_Tally*
(*kino_ORScorer_tally_t)(kino_ORScorer *self);

typedef chy_bool_t
(*kino_ORScorer_skip_to_t)(kino_ORScorer *self, chy_u32_t target);

#define Kino_ORScorer_Clone(self) \
    (self)->_->clone((kino_Obj*)self)

#define Kino_ORScorer_Destroy(self) \
    (self)->_->destroy((kino_Obj*)self)

#define Kino_ORScorer_Equals(self, other) \
    (self)->_->equals((kino_Obj*)self, other)

#define Kino_ORScorer_Hash_Code(self) \
    (self)->_->hash_code((kino_Obj*)self)

#define Kino_ORScorer_Is_A(self, target_vtable) \
    (self)->_->is_a((kino_Obj*)self, target_vtable)

#define Kino_ORScorer_To_String(self) \
    (self)->_->to_string((kino_Obj*)self)

#define Kino_ORScorer_Serialize(self, target) \
    (self)->_->serialize((kino_Obj*)self, target)

#define Kino_ORScorer_Next(self) \
    (self)->_->next((kino_Scorer*)self)

#define Kino_ORScorer_Doc(self) \
    (self)->_->doc((kino_Scorer*)self)

#define Kino_ORScorer_Tally(self) \
    (self)->_->tally((kino_Scorer*)self)

#define Kino_ORScorer_Skip_To(self, target) \
    (self)->_->skip_to((kino_Scorer*)self, target)

#define Kino_ORScorer_Collect(self, hc, start, end, hits_per_seg, seg_starts) \
    (self)->_->collect((kino_Scorer*)self, hc, start, end, hits_per_seg, seg_starts)

struct KINO_ORSCORER_VTABLE {
    KINO_OBJ_VTABLE *_;
    chy_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
    kino_Scorer_next_t next;
    kino_Scorer_doc_t doc;
    kino_Scorer_tally_t tally;
    kino_Scorer_skip_to_t skip_to;
    kino_Scorer_collect_t collect;
};

extern KINO_ORSCORER_VTABLE KINO_ORSCORER;

#ifdef KINO_USE_SHORT_NAMES
  #define ORScorer kino_ORScorer
  #define ORSCORER KINO_ORSCORER
  #define ORScorer_new kino_ORScorer_new
  #define ORScorer_destroy kino_ORScorer_destroy
  #define ORScorer_next kino_ORScorer_next
  #define ORScorer_doc kino_ORScorer_doc
  #define ORScorer_tally kino_ORScorer_tally
  #define ORScorer_skip_to kino_ORScorer_skip_to
  #define ORScorer_Clone Kino_ORScorer_Clone
  #define ORScorer_Destroy Kino_ORScorer_Destroy
  #define ORScorer_Equals Kino_ORScorer_Equals
  #define ORScorer_Hash_Code Kino_ORScorer_Hash_Code
  #define ORScorer_Is_A Kino_ORScorer_Is_A
  #define ORScorer_To_String Kino_ORScorer_To_String
  #define ORScorer_Serialize Kino_ORScorer_Serialize
  #define ORScorer_Next Kino_ORScorer_Next
  #define ORScorer_Doc Kino_ORScorer_Doc
  #define ORScorer_Tally Kino_ORScorer_Tally
  #define ORScorer_Skip_To Kino_ORScorer_Skip_To
  #define ORScorer_Collect Kino_ORScorer_Collect
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_ORSCORER_MEMBER_VARS \
    chy_u32_t  refcount; \
    struct kino_Similarity * sim; \
    struct kino_Tally * tally; \
    struct kino_VArray * subscorers; \
    struct kino_ScorerDocQueue * q; \
    chy_u32_t  num_subs; \
    float * scores; \
    chy_u32_t  doc_num

#ifdef KINO_WANT_ORSCORER_VTABLE
KINO_ORSCORER_VTABLE KINO_ORSCORER = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_SCORER,
    "KinoSearch::Search::ORScorer",
    (kino_Obj_clone_t)kino_Obj_clone,
    (kino_Obj_destroy_t)kino_ORScorer_destroy,
    (kino_Obj_equals_t)kino_Obj_equals,
    (kino_Obj_hash_code_t)kino_Obj_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_Obj_to_string,
    (kino_Obj_serialize_t)kino_Obj_serialize,
    (kino_Scorer_next_t)kino_ORScorer_next,
    (kino_Scorer_doc_t)kino_ORScorer_doc,
    (kino_Scorer_tally_t)kino_ORScorer_tally,
    (kino_Scorer_skip_to_t)kino_ORScorer_skip_to,
    (kino_Scorer_collect_t)kino_Scorer_collect
};
#endif /* KINO_WANT_ORSCORER_VTABLE */

#undef KINO_ORSCORER_BOILERPLATE


#endif /* R_KINO_ORSCORER */


/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */

