/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/

#ifndef R_KINO_PHRASESCORER
#define R_KINO_PHRASESCORER 1

#include "KinoSearch/Search/PhraseScorer.h"

typedef void
(*kino_PhraseScorer_destroy_t)(kino_PhraseScorer*);

typedef kino_bool_t
(*kino_PhraseScorer_next_t)(kino_PhraseScorer*);

typedef kino_u32_t
(*kino_PhraseScorer_doc_t)(kino_PhraseScorer*);

typedef float
(*kino_PhraseScorer_score_t)(kino_PhraseScorer*);

typedef kino_bool_t
(*kino_PhraseScorer_skip_to_t)(kino_PhraseScorer *self, kino_u32_t target);

typedef float
(*kino_PhraseScorer_calc_phrase_freq_t)(kino_PhraseScorer*);

#define Kino_PhraseScorer_Clone(_self) \
    (_self)->_->clone((kino_Obj*)_self)

#define Kino_PhraseScorer_Destroy(_self) \
    (_self)->_->destroy((kino_Obj*)_self)

#define Kino_PhraseScorer_Equals(_self, _arg1) \
    (_self)->_->equals((kino_Obj*)_self, _arg1)

#define Kino_PhraseScorer_Hash_Code(_self) \
    (_self)->_->hash_code((kino_Obj*)_self)

#define Kino_PhraseScorer_Is_A(_self, _arg1) \
    (_self)->_->is_a((kino_Obj*)_self, _arg1)

#define Kino_PhraseScorer_To_String(_self) \
    (_self)->_->to_string((kino_Obj*)_self)

#define Kino_PhraseScorer_Serialize(_self, _arg1) \
    (_self)->_->serialize((kino_Obj*)_self, _arg1)

#define Kino_PhraseScorer_Next(_self) \
    (_self)->_->next((kino_Scorer*)_self)

#define Kino_PhraseScorer_Doc(_self) \
    (_self)->_->doc((kino_Scorer*)_self)

#define Kino_PhraseScorer_Score(_self) \
    (_self)->_->score((kino_Scorer*)_self)

#define Kino_PhraseScorer_Skip_To(_self, _arg1) \
    (_self)->_->skip_to((kino_Scorer*)_self, _arg1)

#define Kino_PhraseScorer_Calc_Phrase_Freq(_self) \
    (_self)->_->calc_phrase_freq((kino_PhraseScorer*)_self)

struct KINO_PHRASESCORER_VTABLE {
    KINO_OBJ_VTABLE *_;
    kino_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
    kino_Scorer_next_t next;
    kino_Scorer_doc_t doc;
    kino_Scorer_score_t score;
    kino_Scorer_skip_to_t skip_to;
    kino_PhraseScorer_calc_phrase_freq_t calc_phrase_freq;
};

extern KINO_PHRASESCORER_VTABLE KINO_PHRASESCORER;

#ifdef KINO_USE_SHORT_NAMES
  #define PhraseScorer kino_PhraseScorer
  #define PHRASESCORER KINO_PHRASESCORER
  #define PhraseScorer_new kino_PhraseScorer_new
  #define PhraseScorer_destroy kino_PhraseScorer_destroy
  #define PhraseScorer_next kino_PhraseScorer_next
  #define PhraseScorer_doc kino_PhraseScorer_doc
  #define PhraseScorer_score kino_PhraseScorer_score
  #define PhraseScorer_skip_to kino_PhraseScorer_skip_to
  #define PhraseScorer_calc_phrase_freq_t kino_PhraseScorer_calc_phrase_freq_t
  #define PhraseScorer_calc_phrase_freq kino_PhraseScorer_calc_phrase_freq
  #define PhraseScorer_Clone Kino_PhraseScorer_Clone
  #define PhraseScorer_Destroy Kino_PhraseScorer_Destroy
  #define PhraseScorer_Equals Kino_PhraseScorer_Equals
  #define PhraseScorer_Hash_Code Kino_PhraseScorer_Hash_Code
  #define PhraseScorer_Is_A Kino_PhraseScorer_Is_A
  #define PhraseScorer_To_String Kino_PhraseScorer_To_String
  #define PhraseScorer_Serialize Kino_PhraseScorer_Serialize
  #define PhraseScorer_Next Kino_PhraseScorer_Next
  #define PhraseScorer_Doc Kino_PhraseScorer_Doc
  #define PhraseScorer_Score Kino_PhraseScorer_Score
  #define PhraseScorer_Skip_To Kino_PhraseScorer_Skip_To
  #define PhraseScorer_Calc_Phrase_Freq Kino_PhraseScorer_Calc_Phrase_Freq
  #define PHRASESCORER KINO_PHRASESCORER
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_PHRASESCORER_MEMBER_VARS \
    struct kino_Similarity * sim; \
    struct kino_ByteBuf * raw_prox_bb; \
    kino_u32_t * prox; \
    kino_u32_t  num_prox; \
    kino_u32_t  doc_num; \
    kino_u32_t  slop; \
    kino_u32_t  num_elements; \
    struct kino_TermDocs ** term_docs; \
    kino_u32_t * phrase_offsets; \
    struct kino_ByteBuf * anchor_set; \
    float  phrase_freq; \
    float  phrase_boost; \
    float  weight_value; \
    kino_bool_t  first_time; \
    kino_bool_t  more;


#ifdef KINO_WANT_PHRASESCORER_VTABLE
KINO_PHRASESCORER_VTABLE KINO_PHRASESCORER = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_SCORER,
    "KinoSearch::Search::PhraseScorer",
    (kino_Obj_clone_t)kino_Obj_clone,
    (kino_Obj_destroy_t)kino_PhraseScorer_destroy,
    (kino_Obj_equals_t)kino_Obj_equals,
    (kino_Obj_hash_code_t)kino_Obj_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_Obj_to_string,
    (kino_Obj_serialize_t)kino_Obj_serialize,
    (kino_Scorer_next_t)kino_PhraseScorer_next,
    (kino_Scorer_doc_t)kino_PhraseScorer_doc,
    (kino_Scorer_score_t)kino_PhraseScorer_score,
    (kino_Scorer_skip_to_t)kino_PhraseScorer_skip_to,
    (kino_PhraseScorer_calc_phrase_freq_t)kino_PhraseScorer_calc_phrase_freq
};
#endif /* KINO_WANT_PHRASESCORER_VTABLE */

#endif /* R_KINO_PHRASESCORER */

/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */
