/** @file */
/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/



#ifndef R_KINO_PHRASESCORER
#define R_KINO_PHRASESCORER 1

#include "KinoSearch/Search/PhraseScorer.h"

#define KINO_PHRASESCORER_BOILERPLATE

typedef void
(*kino_PhraseScorer_destroy_t)(kino_PhraseScorer *self);

typedef chy_bool_t
(*kino_PhraseScorer_next_t)(kino_PhraseScorer *self);

typedef chy_u32_t
(*kino_PhraseScorer_doc_t)(kino_PhraseScorer *self);

typedef struct kino_Tally*
(*kino_PhraseScorer_tally_t)(kino_PhraseScorer *self);

typedef chy_bool_t
(*kino_PhraseScorer_skip_to_t)(kino_PhraseScorer *self, chy_u32_t target);

typedef float
(*kino_PhraseScorer_calc_phrase_freq_t)(kino_PhraseScorer *self);

#define Kino_PhraseScorer_Clone(self) \
    (self)->_->clone((kino_Obj*)self)

#define Kino_PhraseScorer_Destroy(self) \
    (self)->_->destroy((kino_Obj*)self)

#define Kino_PhraseScorer_Equals(self, other) \
    (self)->_->equals((kino_Obj*)self, other)

#define Kino_PhraseScorer_Hash_Code(self) \
    (self)->_->hash_code((kino_Obj*)self)

#define Kino_PhraseScorer_Is_A(self, target_vtable) \
    (self)->_->is_a((kino_Obj*)self, target_vtable)

#define Kino_PhraseScorer_To_String(self) \
    (self)->_->to_string((kino_Obj*)self)

#define Kino_PhraseScorer_Serialize(self, target) \
    (self)->_->serialize((kino_Obj*)self, target)

#define Kino_PhraseScorer_Next(self) \
    (self)->_->next((kino_Scorer*)self)

#define Kino_PhraseScorer_Doc(self) \
    (self)->_->doc((kino_Scorer*)self)

#define Kino_PhraseScorer_Tally(self) \
    (self)->_->tally((kino_Scorer*)self)

#define Kino_PhraseScorer_Skip_To(self, target) \
    (self)->_->skip_to((kino_Scorer*)self, target)

#define Kino_PhraseScorer_Collect(self, hc, start, end, hits_per_seg, seg_starts) \
    (self)->_->collect((kino_Scorer*)self, hc, start, end, hits_per_seg, seg_starts)

#define Kino_PhraseScorer_Max_Matchers(self) \
    (self)->_->max_matchers((kino_Scorer*)self)

#define Kino_PhraseScorer_Calc_Phrase_Freq(self) \
    (self)->_->calc_phrase_freq((kino_PhraseScorer*)self)

struct KINO_PHRASESCORER_VTABLE {
    KINO_OBJ_VTABLE *_;
    chy_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
    kino_Scorer_next_t next;
    kino_Scorer_doc_t doc;
    kino_Scorer_tally_t tally;
    kino_Scorer_skip_to_t skip_to;
    kino_Scorer_collect_t collect;
    kino_Scorer_max_matchers_t max_matchers;
    kino_PhraseScorer_calc_phrase_freq_t calc_phrase_freq;
};

extern KINO_PHRASESCORER_VTABLE KINO_PHRASESCORER;

#ifdef KINO_USE_SHORT_NAMES
  #define PhraseScorer kino_PhraseScorer
  #define PHRASESCORER KINO_PHRASESCORER
  #define PhraseScorer_new kino_PhraseScorer_new
  #define PhraseScorer_destroy kino_PhraseScorer_destroy
  #define PhraseScorer_next kino_PhraseScorer_next
  #define PhraseScorer_doc kino_PhraseScorer_doc
  #define PhraseScorer_tally kino_PhraseScorer_tally
  #define PhraseScorer_skip_to kino_PhraseScorer_skip_to
  #define PhraseScorer_calc_phrase_freq_t kino_PhraseScorer_calc_phrase_freq_t
  #define PhraseScorer_calc_phrase_freq kino_PhraseScorer_calc_phrase_freq
  #define PhraseScorer_Clone Kino_PhraseScorer_Clone
  #define PhraseScorer_Destroy Kino_PhraseScorer_Destroy
  #define PhraseScorer_Equals Kino_PhraseScorer_Equals
  #define PhraseScorer_Hash_Code Kino_PhraseScorer_Hash_Code
  #define PhraseScorer_Is_A Kino_PhraseScorer_Is_A
  #define PhraseScorer_To_String Kino_PhraseScorer_To_String
  #define PhraseScorer_Serialize Kino_PhraseScorer_Serialize
  #define PhraseScorer_Next Kino_PhraseScorer_Next
  #define PhraseScorer_Doc Kino_PhraseScorer_Doc
  #define PhraseScorer_Tally Kino_PhraseScorer_Tally
  #define PhraseScorer_Skip_To Kino_PhraseScorer_Skip_To
  #define PhraseScorer_Collect Kino_PhraseScorer_Collect
  #define PhraseScorer_Max_Matchers Kino_PhraseScorer_Max_Matchers
  #define PhraseScorer_Calc_Phrase_Freq Kino_PhraseScorer_Calc_Phrase_Freq
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_PHRASESCORER_MEMBER_VARS \
    chy_u32_t  refcount; \
    struct kino_Similarity * sim; \
    chy_u32_t  doc_num; \
    chy_u32_t  slop; \
    chy_u32_t  num_elements; \
    struct kino_ScoreProx * sprox; \
    struct kino_Tally * tally; \
    struct kino_PostingList ** plists; \
    chy_u32_t * phrase_offsets; \
    struct kino_ByteBuf * anchor_set; \
    struct kino_ByteBuf * raw_prox_bb; \
    float  phrase_freq; \
    float  phrase_boost; \
    struct kino_Native * weight; \
    float  weight_value; \
    chy_bool_t  first_time; \
    chy_bool_t  more

#ifdef KINO_WANT_PHRASESCORER_VTABLE
KINO_PHRASESCORER_VTABLE KINO_PHRASESCORER = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_SCORER,
    "KinoSearch::Search::PhraseScorer",
    (kino_Obj_clone_t)kino_Obj_clone,
    (kino_Obj_destroy_t)kino_PhraseScorer_destroy,
    (kino_Obj_equals_t)kino_Obj_equals,
    (kino_Obj_hash_code_t)kino_Obj_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_Obj_to_string,
    (kino_Obj_serialize_t)kino_Obj_serialize,
    (kino_Scorer_next_t)kino_PhraseScorer_next,
    (kino_Scorer_doc_t)kino_PhraseScorer_doc,
    (kino_Scorer_tally_t)kino_PhraseScorer_tally,
    (kino_Scorer_skip_to_t)kino_PhraseScorer_skip_to,
    (kino_Scorer_collect_t)kino_Scorer_collect,
    (kino_Scorer_max_matchers_t)kino_Scorer_max_matchers,
    (kino_PhraseScorer_calc_phrase_freq_t)kino_PhraseScorer_calc_phrase_freq
};
#endif /* KINO_WANT_PHRASESCORER_VTABLE */

#undef KINO_PHRASESCORER_BOILERPLATE


#endif /* R_KINO_PHRASESCORER */


/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */

