/** @file */
/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/

#ifndef R_KINO_SCORER
#define R_KINO_SCORER 1

#include "KinoSearch/Search/Scorer.h"

typedef kino_bool_t
(*kino_Scorer_next_t)(kino_Scorer *self);

typedef kino_u32_t
(*kino_Scorer_doc_t)(kino_Scorer *self);

typedef float
(*kino_Scorer_score_t)(kino_Scorer *self);

typedef kino_bool_t
(*kino_Scorer_skip_to_t)(kino_Scorer*, kino_u32_t);

typedef void
(*kino_Scorer_score_batch_t)(kino_Scorer *self, struct kino_HitCollector *hc, 
                        kino_u32_t start, kino_u32_t end, 
                        kino_u32_t prune_factor, 
                        struct kino_VArray *seg_starts);

#define Kino_Scorer_Clone(_self) \
    (_self)->_->clone((kino_Obj*)_self)

#define Kino_Scorer_Destroy(_self) \
    (_self)->_->destroy((kino_Obj*)_self)

#define Kino_Scorer_Equals(_self, _arg1) \
    (_self)->_->equals((kino_Obj*)_self, _arg1)

#define Kino_Scorer_Hash_Code(_self) \
    (_self)->_->hash_code((kino_Obj*)_self)

#define Kino_Scorer_Is_A(_self, _arg1) \
    (_self)->_->is_a((kino_Obj*)_self, _arg1)

#define Kino_Scorer_To_String(_self) \
    (_self)->_->to_string((kino_Obj*)_self)

#define Kino_Scorer_Serialize(_self, _arg1) \
    (_self)->_->serialize((kino_Obj*)_self, _arg1)

#define Kino_Scorer_Next(_self) \
    (_self)->_->next((kino_Scorer*)_self)

#define Kino_Scorer_Doc(_self) \
    (_self)->_->doc((kino_Scorer*)_self)

#define Kino_Scorer_Score(_self) \
    (_self)->_->score((kino_Scorer*)_self)

#define Kino_Scorer_Skip_To(_self, _arg1) \
    (_self)->_->skip_to((kino_Scorer*)_self, _arg1)

#define Kino_Scorer_Score_Batch(_self, _arg1, _arg2, _arg3, _arg4, _arg5) \
    (_self)->_->score_batch((kino_Scorer*)_self, _arg1, _arg2, _arg3, _arg4, _arg5)

struct KINO_SCORER_VTABLE {
    KINO_OBJ_VTABLE *_;
    kino_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
    kino_Scorer_next_t next;
    kino_Scorer_doc_t doc;
    kino_Scorer_score_t score;
    kino_Scorer_skip_to_t skip_to;
    kino_Scorer_score_batch_t score_batch;
};

extern KINO_SCORER_VTABLE KINO_SCORER;

#ifdef KINO_USE_SHORT_NAMES
  #define Scorer kino_Scorer
  #define SCORER KINO_SCORER
  #define Scorer_next_t kino_Scorer_next_t
  #define Scorer_next kino_Scorer_next
  #define Scorer_doc_t kino_Scorer_doc_t
  #define Scorer_doc kino_Scorer_doc
  #define Scorer_score_t kino_Scorer_score_t
  #define Scorer_score kino_Scorer_score
  #define Scorer_skip_to_t kino_Scorer_skip_to_t
  #define Scorer_skip_to kino_Scorer_skip_to
  #define Scorer_score_batch_t kino_Scorer_score_batch_t
  #define Scorer_score_batch kino_Scorer_score_batch
  #define Scorer_Clone Kino_Scorer_Clone
  #define Scorer_Destroy Kino_Scorer_Destroy
  #define Scorer_Equals Kino_Scorer_Equals
  #define Scorer_Hash_Code Kino_Scorer_Hash_Code
  #define Scorer_Is_A Kino_Scorer_Is_A
  #define Scorer_To_String Kino_Scorer_To_String
  #define Scorer_Serialize Kino_Scorer_Serialize
  #define Scorer_Next Kino_Scorer_Next
  #define Scorer_Doc Kino_Scorer_Doc
  #define Scorer_Score Kino_Scorer_Score
  #define Scorer_Skip_To Kino_Scorer_Skip_To
  #define Scorer_Score_Batch Kino_Scorer_Score_Batch
  #define SCORER KINO_SCORER
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_SCORER_MEMBER_VARS \
    kino_u32_t  refcount; \
    struct kino_Similarity * sim; \
    struct kino_ByteBuf * raw_prox_bb; \
    kino_u32_t * prox; \
    kino_u32_t  num_prox


#ifdef KINO_WANT_SCORER_VTABLE
KINO_SCORER_VTABLE KINO_SCORER = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_OBJ,
    "KinoSearch::Search::Scorer",
    (kino_Obj_clone_t)kino_Obj_clone,
    (kino_Obj_destroy_t)kino_Obj_destroy,
    (kino_Obj_equals_t)kino_Obj_equals,
    (kino_Obj_hash_code_t)kino_Obj_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_Obj_to_string,
    (kino_Obj_serialize_t)kino_Obj_serialize,
    (kino_Scorer_next_t)kino_Scorer_next,
    (kino_Scorer_doc_t)kino_Scorer_doc,
    (kino_Scorer_score_t)kino_Scorer_score,
    (kino_Scorer_skip_to_t)kino_Scorer_skip_to,
    (kino_Scorer_score_batch_t)kino_Scorer_score_batch
};
#endif /* KINO_WANT_SCORER_VTABLE */

#endif /* R_KINO_SCORER */

/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */
