/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/

#ifndef R_KINO_SORTCOLL
#define R_KINO_SORTCOLL 1

#include "KinoSearch/Search/SortCollector.h"

typedef void
(*kino_SortColl_destroy_t)(kino_SortCollector *self);

#define Kino_SortColl_Clone(_self) \
    (_self)->_->clone((kino_Obj*)_self)

#define Kino_SortColl_Destroy(_self) \
    (_self)->_->destroy((kino_Obj*)_self)

#define Kino_SortColl_Equals(_self, _arg1) \
    (_self)->_->equals((kino_Obj*)_self, _arg1)

#define Kino_SortColl_Hash_Code(_self) \
    (_self)->_->hash_code((kino_Obj*)_self)

#define Kino_SortColl_Is_A(_self, _arg1) \
    (_self)->_->is_a((kino_Obj*)_self, _arg1)

#define Kino_SortColl_To_String(_self) \
    (_self)->_->to_string((kino_Obj*)_self)

#define Kino_SortColl_Serialize(_self, _arg1) \
    (_self)->_->serialize((kino_Obj*)_self, _arg1)

struct KINO_SORTCOLLECTOR_VTABLE {
    KINO_OBJ_VTABLE *_;
    kino_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
};

extern KINO_SORTCOLLECTOR_VTABLE KINO_SORTCOLLECTOR;

#ifdef KINO_USE_SHORT_NAMES
  #define SortCollector kino_SortCollector
  #define SORTCOLLECTOR KINO_SORTCOLLECTOR
  #define SortColl_new kino_SortColl_new
  #define SortColl_destroy kino_SortColl_destroy
  #define SortColl_Clone Kino_SortColl_Clone
  #define SortColl_Destroy Kino_SortColl_Destroy
  #define SortColl_Equals Kino_SortColl_Equals
  #define SortColl_Hash_Code Kino_SortColl_Hash_Code
  #define SortColl_Is_A Kino_SortColl_Is_A
  #define SortColl_To_String Kino_SortColl_To_String
  #define SortColl_Serialize Kino_SortColl_Serialize
  #define SORTCOLLECTOR KINO_SORTCOLLECTOR
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_SORTCOLLECTOR_MEMBER_VARS \
    kino_HC_collect_t  collect; \
    kino_HC_release_t  release; \
    void * data; \
    float  min_score; \
    kino_u32_t  num_hits; \
    kino_u32_t  total_hits; \
    struct kino_HitQueue * hit_q; \
    struct kino_FieldDocCollator * collator; \
    kino_i32_t  min_doc;


#ifdef KINO_WANT_SORTCOLLECTOR_VTABLE
KINO_SORTCOLLECTOR_VTABLE KINO_SORTCOLLECTOR = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_TOPDOCCOLLECTOR,
    "KinoSearch::Search::SortCollector",
    (kino_Obj_clone_t)kino_Obj_clone,
    (kino_Obj_destroy_t)kino_SortColl_destroy,
    (kino_Obj_equals_t)kino_Obj_equals,
    (kino_Obj_hash_code_t)kino_Obj_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_Obj_to_string,
    (kino_Obj_serialize_t)kino_Obj_serialize
};
#endif /* KINO_WANT_SORTCOLLECTOR_VTABLE */

#endif /* R_KINO_SORTCOLL */

/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */
