/** @file */
/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/

#ifndef R_KINO_SORTEDHITQ
#define R_KINO_SORTEDHITQ 1

#include "KinoSearch/Search/SortedHitQueue.h"

#define Kino_SortedHitQ_Clone(_self) \
    (_self)->_->clone((kino_Obj*)_self)

#define Kino_SortedHitQ_Destroy(_self) \
    (_self)->_->destroy((kino_Obj*)_self)

#define Kino_SortedHitQ_Equals(_self, _arg1) \
    (_self)->_->equals((kino_Obj*)_self, _arg1)

#define Kino_SortedHitQ_Hash_Code(_self) \
    (_self)->_->hash_code((kino_Obj*)_self)

#define Kino_SortedHitQ_Is_A(_self, _arg1) \
    (_self)->_->is_a((kino_Obj*)_self, _arg1)

#define Kino_SortedHitQ_To_String(_self) \
    (_self)->_->to_string((kino_Obj*)_self)

#define Kino_SortedHitQ_Serialize(_self, _arg1) \
    (_self)->_->serialize((kino_Obj*)_self, _arg1)

#define Kino_SortedHitQ_Insert(_self, _arg1) \
    (_self)->_->insert((kino_PriorityQueue*)_self, _arg1)

#define Kino_SortedHitQ_Pop(_self) \
    (_self)->_->pop((kino_PriorityQueue*)_self)

#define Kino_SortedHitQ_Peek(_self) \
    (_self)->_->peek((kino_PriorityQueue*)_self)

struct KINO_SORTEDHITQUEUE_VTABLE {
    KINO_OBJ_VTABLE *_;
    kino_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
    kino_PriQ_insert_t insert;
    kino_PriQ_pop_t pop;
    kino_PriQ_peek_t peek;
};

extern KINO_SORTEDHITQUEUE_VTABLE KINO_SORTEDHITQUEUE;

#ifdef KINO_USE_SHORT_NAMES
  #define SortedHitQueue kino_SortedHitQueue
  #define SORTEDHITQUEUE KINO_SORTEDHITQUEUE
  #define SortedHitQ_new kino_SortedHitQ_new
  #define SortedHitQ_Clone Kino_SortedHitQ_Clone
  #define SortedHitQ_Destroy Kino_SortedHitQ_Destroy
  #define SortedHitQ_Equals Kino_SortedHitQ_Equals
  #define SortedHitQ_Hash_Code Kino_SortedHitQ_Hash_Code
  #define SortedHitQ_Is_A Kino_SortedHitQ_Is_A
  #define SortedHitQ_To_String Kino_SortedHitQ_To_String
  #define SortedHitQ_Serialize Kino_SortedHitQ_Serialize
  #define SortedHitQ_Insert Kino_SortedHitQ_Insert
  #define SortedHitQ_Pop Kino_SortedHitQ_Pop
  #define SortedHitQ_Peek Kino_SortedHitQ_Peek
  #define SORTEDHITQUEUE KINO_SORTEDHITQUEUE
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_SORTEDHITQUEUE_MEMBER_VARS \
    kino_u32_t  refcount; \
    kino_u32_t  size; \
    kino_u32_t  max_size; \
    void ** heap; \
    kino_PriQ_less_than_t  less_than; \
    kino_PriQ_free_elem_t  free_elem


#ifdef KINO_WANT_SORTEDHITQUEUE_VTABLE
KINO_SORTEDHITQUEUE_VTABLE KINO_SORTEDHITQUEUE = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_HITQUEUE,
    "KinoSearch::Search::SortedHitQueue",
    (kino_Obj_clone_t)kino_Obj_clone,
    (kino_Obj_destroy_t)kino_PriQ_destroy,
    (kino_Obj_equals_t)kino_Obj_equals,
    (kino_Obj_hash_code_t)kino_Obj_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_Obj_to_string,
    (kino_Obj_serialize_t)kino_Obj_serialize,
    (kino_PriQ_insert_t)kino_PriQ_insert,
    (kino_PriQ_pop_t)kino_PriQ_pop,
    (kino_PriQ_peek_t)kino_PriQ_peek
};
#endif /* KINO_WANT_SORTEDHITQUEUE_VTABLE */

#endif /* R_KINO_SORTEDHITQ */

/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */
