/** @file */
/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/



#ifndef R_KINO_TERMSCORER
#define R_KINO_TERMSCORER 1

#include "KinoSearch/Search/TermScorer.h"

#define KINO_TERMSCORER_BOILERPLATE

typedef void
(*kino_TermScorer_destroy_t)(kino_TermScorer *self);

typedef chy_bool_t
(*kino_TermScorer_next_t)(kino_TermScorer* self);

typedef chy_u32_t
(*kino_TermScorer_doc_t)(kino_TermScorer* self);

typedef struct kino_Tally*
(*kino_TermScorer_tally_t)(kino_TermScorer* self);

typedef chy_bool_t
(*kino_TermScorer_skip_to_t)(kino_TermScorer* self, chy_u32_t target);

#define Kino_TermScorer_Clone(self) \
    (self)->_->clone((kino_Obj*)self)

#define Kino_TermScorer_Destroy(self) \
    (self)->_->destroy((kino_Obj*)self)

#define Kino_TermScorer_Equals(self, other) \
    (self)->_->equals((kino_Obj*)self, other)

#define Kino_TermScorer_Hash_Code(self) \
    (self)->_->hash_code((kino_Obj*)self)

#define Kino_TermScorer_Is_A(self, target_vtable) \
    (self)->_->is_a((kino_Obj*)self, target_vtable)

#define Kino_TermScorer_To_String(self) \
    (self)->_->to_string((kino_Obj*)self)

#define Kino_TermScorer_Serialize(self, target) \
    (self)->_->serialize((kino_Obj*)self, target)

#define Kino_TermScorer_Next(self) \
    (self)->_->next((kino_Scorer*)self)

#define Kino_TermScorer_Doc(self) \
    (self)->_->doc((kino_Scorer*)self)

#define Kino_TermScorer_Tally(self) \
    (self)->_->tally((kino_Scorer*)self)

#define Kino_TermScorer_Skip_To(self, target) \
    (self)->_->skip_to((kino_Scorer*)self, target)

#define Kino_TermScorer_Collect(self, hc, start, end, hits_per_seg, seg_starts) \
    (self)->_->collect((kino_Scorer*)self, hc, start, end, hits_per_seg, seg_starts)

#define Kino_TermScorer_Max_Matchers(self) \
    (self)->_->max_matchers((kino_Scorer*)self)

struct KINO_TERMSCORER_VTABLE {
    KINO_OBJ_VTABLE *_;
    chy_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
    kino_Scorer_next_t next;
    kino_Scorer_doc_t doc;
    kino_Scorer_tally_t tally;
    kino_Scorer_skip_to_t skip_to;
    kino_Scorer_collect_t collect;
    kino_Scorer_max_matchers_t max_matchers;
};

extern KINO_TERMSCORER_VTABLE KINO_TERMSCORER;

#ifdef KINO_USE_SHORT_NAMES
  #define TermScorer kino_TermScorer
  #define TERMSCORER KINO_TERMSCORER
  #define TermScorer_destroy kino_TermScorer_destroy
  #define TermScorer_next kino_TermScorer_next
  #define TermScorer_doc kino_TermScorer_doc
  #define TermScorer_tally kino_TermScorer_tally
  #define TermScorer_skip_to kino_TermScorer_skip_to
  #define TermScorer_Clone Kino_TermScorer_Clone
  #define TermScorer_Destroy Kino_TermScorer_Destroy
  #define TermScorer_Equals Kino_TermScorer_Equals
  #define TermScorer_Hash_Code Kino_TermScorer_Hash_Code
  #define TermScorer_Is_A Kino_TermScorer_Is_A
  #define TermScorer_To_String Kino_TermScorer_To_String
  #define TermScorer_Serialize Kino_TermScorer_Serialize
  #define TermScorer_Next Kino_TermScorer_Next
  #define TermScorer_Doc Kino_TermScorer_Doc
  #define TermScorer_Tally Kino_TermScorer_Tally
  #define TermScorer_Skip_To Kino_TermScorer_Skip_To
  #define TermScorer_Collect Kino_TermScorer_Collect
  #define TermScorer_Max_Matchers Kino_TermScorer_Max_Matchers
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_TERMSCORER_MEMBER_VARS \
    chy_u32_t  refcount; \
    struct kino_Similarity * sim; \
    float  weight_value; \
    float * score_cache; \
    struct kino_Native * weight; \
    struct kino_Tally * tally; \
    struct kino_ScoreProx * sprox; \
    struct kino_PostingList * plist; \
    struct kino_Posting * posting

#ifdef KINO_WANT_TERMSCORER_VTABLE
KINO_TERMSCORER_VTABLE KINO_TERMSCORER = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_SCORER,
    "KinoSearch::Search::TermScorer",
    (kino_Obj_clone_t)kino_Obj_clone,
    (kino_Obj_destroy_t)kino_TermScorer_destroy,
    (kino_Obj_equals_t)kino_Obj_equals,
    (kino_Obj_hash_code_t)kino_Obj_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_Obj_to_string,
    (kino_Obj_serialize_t)kino_Obj_serialize,
    (kino_Scorer_next_t)kino_TermScorer_next,
    (kino_Scorer_doc_t)kino_TermScorer_doc,
    (kino_Scorer_tally_t)kino_TermScorer_tally,
    (kino_Scorer_skip_to_t)kino_TermScorer_skip_to,
    (kino_Scorer_collect_t)kino_Scorer_collect,
    (kino_Scorer_max_matchers_t)kino_Scorer_max_matchers
};
#endif /* KINO_WANT_TERMSCORER_VTABLE */

#undef KINO_TERMSCORER_BOILERPLATE


#endif /* R_KINO_TERMSCORER */


/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */

