/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/

#ifndef R_KINO_TERMSCORER
#define R_KINO_TERMSCORER 1

#include "KinoSearch/Search/TermScorer.h"

typedef void
(*kino_TermScorer_destroy_t)(kino_TermScorer *self);

typedef kino_bool_t
(*kino_TermScorer_next_t)(kino_TermScorer* self);

typedef kino_u32_t
(*kino_TermScorer_doc_t)(kino_TermScorer* self);

typedef float
(*kino_TermScorer_score_t)(kino_TermScorer* self);

#define Kino_TermScorer_Clone(_self) \
    (_self)->_->clone((kino_Obj*)_self)

#define Kino_TermScorer_Destroy(_self) \
    (_self)->_->destroy((kino_Obj*)_self)

#define Kino_TermScorer_Equals(_self, _arg1) \
    (_self)->_->equals((kino_Obj*)_self, _arg1)

#define Kino_TermScorer_Hash_Code(_self) \
    (_self)->_->hash_code((kino_Obj*)_self)

#define Kino_TermScorer_Is_A(_self, _arg1) \
    (_self)->_->is_a((kino_Obj*)_self, _arg1)

#define Kino_TermScorer_To_String(_self) \
    (_self)->_->to_string((kino_Obj*)_self)

#define Kino_TermScorer_Serialize(_self, _arg1) \
    (_self)->_->serialize((kino_Obj*)_self, _arg1)

#define Kino_TermScorer_Next(_self) \
    (_self)->_->next((kino_Scorer*)_self)

#define Kino_TermScorer_Doc(_self) \
    (_self)->_->doc((kino_Scorer*)_self)

#define Kino_TermScorer_Score(_self) \
    (_self)->_->score((kino_Scorer*)_self)

#define Kino_TermScorer_Skip_To(_self, _arg1) \
    (_self)->_->skip_to((kino_Scorer*)_self, _arg1)

struct KINO_TERMSCORER_VTABLE {
    KINO_OBJ_VTABLE *_;
    kino_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
    kino_Scorer_next_t next;
    kino_Scorer_doc_t doc;
    kino_Scorer_score_t score;
    kino_Scorer_skip_to_t skip_to;
};

extern KINO_TERMSCORER_VTABLE KINO_TERMSCORER;

#ifdef KINO_USE_SHORT_NAMES
  #define TermScorer kino_TermScorer
  #define TERMSCORER KINO_TERMSCORER
  #define TermScorer_new kino_TermScorer_new
  #define TermScorer_fill_score_cache kino_TermScorer_fill_score_cache
  #define TermScorer_destroy kino_TermScorer_destroy
  #define TermScorer_next kino_TermScorer_next
  #define TermScorer_doc kino_TermScorer_doc
  #define TermScorer_score kino_TermScorer_score
  #define TermScorer_Clone Kino_TermScorer_Clone
  #define TermScorer_Destroy Kino_TermScorer_Destroy
  #define TermScorer_Equals Kino_TermScorer_Equals
  #define TermScorer_Hash_Code Kino_TermScorer_Hash_Code
  #define TermScorer_Is_A Kino_TermScorer_Is_A
  #define TermScorer_To_String Kino_TermScorer_To_String
  #define TermScorer_Serialize Kino_TermScorer_Serialize
  #define TermScorer_Next Kino_TermScorer_Next
  #define TermScorer_Doc Kino_TermScorer_Doc
  #define TermScorer_Score Kino_TermScorer_Score
  #define TermScorer_Skip_To Kino_TermScorer_Skip_To
  #define TERMSCORER KINO_TERMSCORER
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_TERMSCORER_MEMBER_VARS \
    struct kino_Similarity * sim; \
    struct kino_ByteBuf * raw_prox_bb; \
    kino_u32_t * prox; \
    kino_u32_t  num_prox; \
    kino_u32_t  doc_num; \
    struct kino_TermDocs*  term_docs; \
    kino_u32_t  pointer; \
    kino_u32_t  pointer_max; \
    float  weight_value; \
    float * score_cache; \
    kino_u32_t * doc_nums; \
    kino_u32_t * freqs; \
    float * boosts; \
    struct kino_ByteBuf * doc_nums_bb; \
    struct kino_ByteBuf * field_boosts_bb; \
    struct kino_ByteBuf * freqs_bb; \
    struct kino_ByteBuf * boosts_bb; \
    struct kino_ByteBuf * pos_boosts_bb; \
    void * weight_ref;


#ifdef KINO_WANT_TERMSCORER_VTABLE
KINO_TERMSCORER_VTABLE KINO_TERMSCORER = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_SCORER,
    "KinoSearch::Search::TermScorer",
    (kino_Obj_clone_t)kino_Obj_clone,
    (kino_Obj_destroy_t)kino_TermScorer_destroy,
    (kino_Obj_equals_t)kino_Obj_equals,
    (kino_Obj_hash_code_t)kino_Obj_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_Obj_to_string,
    (kino_Obj_serialize_t)kino_Obj_serialize,
    (kino_Scorer_next_t)kino_TermScorer_next,
    (kino_Scorer_doc_t)kino_TermScorer_doc,
    (kino_Scorer_score_t)kino_TermScorer_score,
    (kino_Scorer_skip_to_t)kino_Scorer_skip_to
};
#endif /* KINO_WANT_TERMSCORER_VTABLE */

#endif /* R_KINO_TERMSCORER */

/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */
