/** @file */
/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/



#ifndef R_KINO_BBSORTEX
#define R_KINO_BBSORTEX 1

#include "KinoSearch/Util/BBSortEx.h"

#define KINO_BBSORTEX_BOILERPLATE

typedef void
(*kino_BBSortEx_destroy_t)(kino_BBSortEx *self);

typedef void
(*kino_BBSortEx_flip_t)(kino_BBSortEx *self);

typedef void
(*kino_BBSortEx_flush_t)(kino_BBSortEx *self);

typedef void
(*kino_BBSortEx_feed_str_t)(kino_BBSortEx *self, char *ptr, chy_u32_t len);

#define Kino_BBSortEx_Clone(self) \
    kino_Obj_clone((kino_Obj*)self)

#define Kino_BBSortEx_Destroy(self) \
    kino_BBSortEx_destroy((kino_BBSortEx*)self)

#define Kino_BBSortEx_Equals(self, other) \
    kino_Obj_equals((kino_Obj*)self, other)

#define Kino_BBSortEx_Hash_Code(self) \
    kino_Obj_hash_code((kino_Obj*)self)

#define Kino_BBSortEx_Is_A(self, target_vtable) \
    kino_Obj_is_a((kino_Obj*)self, target_vtable)

#define Kino_BBSortEx_To_String(self) \
    kino_Obj_to_string((kino_Obj*)self)

#define Kino_BBSortEx_Serialize(self, target) \
    kino_Obj_serialize((kino_Obj*)self, target)

#define Kino_BBSortEx_Feed(self, obj, bytes_this_obj) \
    kino_SortEx_feed((kino_SortExternal*)self, obj, bytes_this_obj)

#define Kino_BBSortEx_Flip(self) \
    kino_BBSortEx_flip((kino_BBSortEx*)self)

#define Kino_BBSortEx_Fetch(self) \
    kino_SortEx_fetch((kino_SortExternal*)self)

#define Kino_BBSortEx_Peek(self) \
    kino_SortEx_peek((kino_SortExternal*)self)

#define Kino_BBSortEx_Sort_Cache(self) \
    kino_SortEx_sort_cache((kino_SortExternal*)self)

#define Kino_BBSortEx_Flush(self) \
    kino_BBSortEx_flush((kino_BBSortEx*)self)

#define Kino_BBSortEx_Clear_Cache(self) \
    kino_SortEx_clear_cache((kino_SortExternal*)self)

#define Kino_BBSortEx_Add_Run(self, run) \
    kino_SortEx_add_run((kino_SortExternal*)self, run)

#define Kino_BBSortEx_Feed_Str(self, ptr, len) \
    kino_BBSortEx_feed_str((kino_BBSortEx*)self, ptr, len)

struct KINO_BBSORTEX_VTABLE {
    KINO_OBJ_VTABLE *_;
    chy_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
    kino_SortEx_feed_t feed;
    kino_SortEx_flip_t flip;
    kino_SortEx_fetch_t fetch;
    kino_SortEx_peek_t peek;
    kino_SortEx_sort_cache_t sort_cache;
    kino_SortEx_flush_t flush;
    kino_SortEx_clear_cache_t clear_cache;
    kino_SortEx_add_run_t add_run;
    kino_BBSortEx_feed_str_t feed_str;
};

extern KINO_BBSORTEX_VTABLE KINO_BBSORTEX;

#ifdef KINO_USE_SHORT_NAMES
  #define BBSortEx kino_BBSortEx
  #define BBSORTEX KINO_BBSORTEX
  #define BBSortEx_new kino_BBSortEx_new
  #define BBSortEx_compare_bbs kino_BBSortEx_compare_bbs
  #define BBSortEx_destroy_t kino_BBSortEx_destroy_t
  #define BBSortEx_destroy kino_BBSortEx_destroy
  #define BBSortEx_flip_t kino_BBSortEx_flip_t
  #define BBSortEx_flip kino_BBSortEx_flip
  #define BBSortEx_flush_t kino_BBSortEx_flush_t
  #define BBSortEx_flush kino_BBSortEx_flush
  #define BBSortEx_feed_str_t kino_BBSortEx_feed_str_t
  #define BBSortEx_feed_str kino_BBSortEx_feed_str
  #define BBSortEx_Clone Kino_BBSortEx_Clone
  #define BBSortEx_Destroy Kino_BBSortEx_Destroy
  #define BBSortEx_Equals Kino_BBSortEx_Equals
  #define BBSortEx_Hash_Code Kino_BBSortEx_Hash_Code
  #define BBSortEx_Is_A Kino_BBSortEx_Is_A
  #define BBSortEx_To_String Kino_BBSortEx_To_String
  #define BBSortEx_Serialize Kino_BBSortEx_Serialize
  #define BBSortEx_Feed Kino_BBSortEx_Feed
  #define BBSortEx_Flip Kino_BBSortEx_Flip
  #define BBSortEx_Fetch Kino_BBSortEx_Fetch
  #define BBSortEx_Peek Kino_BBSortEx_Peek
  #define BBSortEx_Sort_Cache Kino_BBSortEx_Sort_Cache
  #define BBSortEx_Flush Kino_BBSortEx_Flush
  #define BBSortEx_Clear_Cache Kino_BBSortEx_Clear_Cache
  #define BBSortEx_Add_Run Kino_BBSortEx_Add_Run
  #define BBSortEx_Feed_Str Kino_BBSortEx_Feed_Str
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_BBSORTEX_MEMBER_VARS \
    chy_u32_t  refcount; \
    kino_MSort_compare_t  compare; \
    kino_Obj * context; \
    kino_Obj ** cache; \
    chy_u32_t  cache_cap; \
    chy_u32_t  cache_max; \
    chy_u32_t  cache_tick; \
    kino_Obj ** scratch; \
    chy_u32_t  scratch_cap; \
    chy_u32_t  mem_thresh; \
    chy_u32_t  consumed; \
    struct kino_SortExRun ** runs; \
    chy_u32_t  num_runs; \
    chy_bool_t  flipped; \
    struct kino_ByteBuf * sortfile_name; \
    struct kino_OutStream * outstream; \
    struct kino_InStream * instream; \
    struct kino_InvIndex * invindex; \
    struct kino_SegInfo * seg_info

#ifdef KINO_WANT_BBSORTEX_VTABLE
KINO_BBSORTEX_VTABLE KINO_BBSORTEX = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_SORTEXTERNAL,
    "KinoSearch::Util::BBSortEx",
    (kino_Obj_clone_t)kino_Obj_clone,
    (kino_Obj_destroy_t)kino_BBSortEx_destroy,
    (kino_Obj_equals_t)kino_Obj_equals,
    (kino_Obj_hash_code_t)kino_Obj_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_Obj_to_string,
    (kino_Obj_serialize_t)kino_Obj_serialize,
    (kino_SortEx_feed_t)kino_SortEx_feed,
    (kino_SortEx_flip_t)kino_BBSortEx_flip,
    (kino_SortEx_fetch_t)kino_SortEx_fetch,
    (kino_SortEx_peek_t)kino_SortEx_peek,
    (kino_SortEx_sort_cache_t)kino_SortEx_sort_cache,
    (kino_SortEx_flush_t)kino_BBSortEx_flush,
    (kino_SortEx_clear_cache_t)kino_SortEx_clear_cache,
    (kino_SortEx_add_run_t)kino_SortEx_add_run,
    (kino_BBSortEx_feed_str_t)kino_BBSortEx_feed_str
};
#endif /* KINO_WANT_BBSORTEX_VTABLE */

#undef KINO_BBSORTEX_BOILERPLATE


#endif /* R_KINO_BBSORTEX */


/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */

