/** @file */
/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/



#ifndef R_KINO_BBSORTEXRUN
#define R_KINO_BBSORTEXRUN 1

#include "KinoSearch/Util/BBSortExRun.h"

#define KINO_BBSORTEXRUN_BOILERPLATE

typedef void
(*kino_BBSortExRun_destroy_t)(kino_BBSortExRun *self);

typedef chy_u32_t
(*kino_BBSortExRun_refill_t)(kino_BBSortExRun *self);

typedef void
(*kino_BBSortExRun_flip_t)(kino_BBSortExRun *self, struct kino_InStream *instream,
                      chy_u32_t mem_thresh);

typedef void
(*kino_BBSortExRun_flush_t)(kino_BBSortExRun *self, 
                       struct kino_OutStream *outstream);

#define Kino_BBSortExRun_Clone(self) \
    kino_Obj_clone((kino_Obj*)self)

#define Kino_BBSortExRun_Destroy(self) \
    kino_BBSortExRun_destroy((kino_BBSortExRun*)self)

#define Kino_BBSortExRun_Equals(self, other) \
    kino_Obj_equals((kino_Obj*)self, other)

#define Kino_BBSortExRun_Hash_Code(self) \
    kino_Obj_hash_code((kino_Obj*)self)

#define Kino_BBSortExRun_Is_A(self, target_vtable) \
    kino_Obj_is_a((kino_Obj*)self, target_vtable)

#define Kino_BBSortExRun_To_String(self) \
    kino_Obj_to_string((kino_Obj*)self)

#define Kino_BBSortExRun_Serialize(self, target) \
    kino_Obj_serialize((kino_Obj*)self, target)

#define Kino_BBSortExRun_Refill(self) \
    kino_BBSortExRun_refill((kino_BBSortExRun*)self)

#define Kino_BBSortExRun_Grow_Cache(self, new_cache_cap) \
    kino_SortExRun_grow_cache((kino_SortExRun*)self, new_cache_cap)

#define Kino_BBSortExRun_Peek_Last(self) \
    kino_SortExRun_peek_last((kino_SortExRun*)self)

#define Kino_BBSortExRun_Prepare_Slice(self, endpost) \
    kino_SortExRun_prepare_slice((kino_SortExRun*)self, endpost)

#define Kino_BBSortExRun_Pop_Slice(self, slice_size) \
    kino_SortExRun_pop_slice((kino_SortExRun*)self, slice_size)

#define Kino_BBSortExRun_Clear_Cache(self) \
    kino_SortExRun_clear_cache((kino_SortExRun*)self)

#define Kino_BBSortExRun_Flip(self, instream, mem_thresh) \
    kino_BBSortExRun_flip((kino_BBSortExRun*)self, instream, mem_thresh)

#define Kino_BBSortExRun_Flush(self, outstream) \
    kino_BBSortExRun_flush((kino_BBSortExRun*)self, outstream)

struct KINO_BBSORTEXRUN_VTABLE {
    KINO_OBJ_VTABLE *_;
    chy_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
    kino_SortExRun_refill_t refill;
    kino_SortExRun_grow_cache_t grow_cache;
    kino_SortExRun_peek_last_t peek_last;
    kino_SortExRun_prepare_slice_t prepare_slice;
    kino_SortExRun_pop_slice_t pop_slice;
    kino_SortExRun_clear_cache_t clear_cache;
    kino_BBSortExRun_flip_t flip;
    kino_BBSortExRun_flush_t flush;
};

extern KINO_BBSORTEXRUN_VTABLE KINO_BBSORTEXRUN;

#ifdef KINO_USE_SHORT_NAMES
  #define BBSortExRun kino_BBSortExRun
  #define BBSORTEXRUN KINO_BBSORTEXRUN
  #define BBSortExRun_new kino_BBSortExRun_new
  #define BBSortExRun_destroy_t kino_BBSortExRun_destroy_t
  #define BBSortExRun_destroy kino_BBSortExRun_destroy
  #define BBSortExRun_refill_t kino_BBSortExRun_refill_t
  #define BBSortExRun_refill kino_BBSortExRun_refill
  #define BBSortExRun_flip_t kino_BBSortExRun_flip_t
  #define BBSortExRun_flip kino_BBSortExRun_flip
  #define BBSortExRun_flush_t kino_BBSortExRun_flush_t
  #define BBSortExRun_flush kino_BBSortExRun_flush
  #define BBSortExRun_Clone Kino_BBSortExRun_Clone
  #define BBSortExRun_Destroy Kino_BBSortExRun_Destroy
  #define BBSortExRun_Equals Kino_BBSortExRun_Equals
  #define BBSortExRun_Hash_Code Kino_BBSortExRun_Hash_Code
  #define BBSortExRun_Is_A Kino_BBSortExRun_Is_A
  #define BBSortExRun_To_String Kino_BBSortExRun_To_String
  #define BBSortExRun_Serialize Kino_BBSortExRun_Serialize
  #define BBSortExRun_Refill Kino_BBSortExRun_Refill
  #define BBSortExRun_Grow_Cache Kino_BBSortExRun_Grow_Cache
  #define BBSortExRun_Peek_Last Kino_BBSortExRun_Peek_Last
  #define BBSortExRun_Prepare_Slice Kino_BBSortExRun_Prepare_Slice
  #define BBSortExRun_Pop_Slice Kino_BBSortExRun_Pop_Slice
  #define BBSortExRun_Clear_Cache Kino_BBSortExRun_Clear_Cache
  #define BBSortExRun_Flip Kino_BBSortExRun_Flip
  #define BBSortExRun_Flush Kino_BBSortExRun_Flush
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_BBSORTEXRUN_MEMBER_VARS \
    chy_u32_t  refcount; \
    kino_MSort_compare_t  compare; \
    kino_Obj * context; \
    kino_Obj ** cache; \
    chy_u32_t  cache_cap; \
    chy_u32_t  cache_max; \
    chy_u32_t  cache_tick; \
    chy_u32_t  slice_size; \
    struct kino_InStream * instream; \
    chy_u32_t  mem_thresh; \
    chy_u64_t  start; \
    chy_u64_t  end

#ifdef KINO_WANT_BBSORTEXRUN_VTABLE
KINO_BBSORTEXRUN_VTABLE KINO_BBSORTEXRUN = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_SORTEXRUN,
    "KinoSearch::Util::BBSortExRun",
    (kino_Obj_clone_t)kino_Obj_clone,
    (kino_Obj_destroy_t)kino_BBSortExRun_destroy,
    (kino_Obj_equals_t)kino_Obj_equals,
    (kino_Obj_hash_code_t)kino_Obj_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_Obj_to_string,
    (kino_Obj_serialize_t)kino_Obj_serialize,
    (kino_SortExRun_refill_t)kino_BBSortExRun_refill,
    (kino_SortExRun_grow_cache_t)kino_SortExRun_grow_cache,
    (kino_SortExRun_peek_last_t)kino_SortExRun_peek_last,
    (kino_SortExRun_prepare_slice_t)kino_SortExRun_prepare_slice,
    (kino_SortExRun_pop_slice_t)kino_SortExRun_pop_slice,
    (kino_SortExRun_clear_cache_t)kino_SortExRun_clear_cache,
    (kino_BBSortExRun_flip_t)kino_BBSortExRun_flip,
    (kino_BBSortExRun_flush_t)kino_BBSortExRun_flush
};
#endif /* KINO_WANT_BBSORTEXRUN_VTABLE */

#undef KINO_BBSORTEXRUN_BOILERPLATE


#endif /* R_KINO_BBSORTEXRUN */


/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */

