/** @file */
/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/

#ifndef R_KINO_BITVEC
#define R_KINO_BITVEC 1

#include "KinoSearch/Util/BitVector.h"

typedef kino_BitVector*
(*kino_BitVec_clone_t)(kino_BitVector *self);

typedef void
(*kino_BitVec_destroy_t)(kino_BitVector* self);

typedef kino_bool_t
(*kino_BitVec_get_t)(const kino_BitVector *self, kino_u32_t num);

typedef void
(*kino_BitVec_set_t)(kino_BitVector *self, kino_u32_t num);

typedef void
(*kino_BitVec_clear_t)(kino_BitVector *self, kino_u32_t num);

typedef void
(*kino_BitVec_grow_t)(kino_BitVector *self, kino_u32_t capacity);

typedef void
(*kino_BitVec_logical_and_t)(kino_BitVector *self, kino_BitVector *other);

typedef kino_u32_t
(*kino_BitVec_count_t)(kino_BitVector *self);

typedef kino_u32_t*
(*kino_BitVec_to_array_t)(kino_BitVector *self);

#define Kino_BitVec_Clone(_self) \
    (_self)->_->clone((kino_Obj*)_self)

#define Kino_BitVec_Destroy(_self) \
    (_self)->_->destroy((kino_Obj*)_self)

#define Kino_BitVec_Equals(_self, _arg1) \
    (_self)->_->equals((kino_Obj*)_self, _arg1)

#define Kino_BitVec_Hash_Code(_self) \
    (_self)->_->hash_code((kino_Obj*)_self)

#define Kino_BitVec_Is_A(_self, _arg1) \
    (_self)->_->is_a((kino_Obj*)_self, _arg1)

#define Kino_BitVec_To_String(_self) \
    (_self)->_->to_string((kino_Obj*)_self)

#define Kino_BitVec_Serialize(_self, _arg1) \
    (_self)->_->serialize((kino_Obj*)_self, _arg1)

#define Kino_BitVec_Get(_self, _arg1) \
    (_self)->_->get((kino_BitVector*)_self, _arg1)

#define Kino_BitVec_Set(_self, _arg1) \
    (_self)->_->set((kino_BitVector*)_self, _arg1)

#define Kino_BitVec_Clear(_self, _arg1) \
    (_self)->_->clear((kino_BitVector*)_self, _arg1)

#define Kino_BitVec_Grow(_self, _arg1) \
    (_self)->_->grow((kino_BitVector*)_self, _arg1)

#define Kino_BitVec_Logical_And(_self, _arg1) \
    (_self)->_->logical_and((kino_BitVector*)_self, _arg1)

#define Kino_BitVec_Count(_self) \
    (_self)->_->count((kino_BitVector*)_self)

#define Kino_BitVec_To_Array(_self) \
    (_self)->_->to_array((kino_BitVector*)_self)

struct KINO_BITVECTOR_VTABLE {
    KINO_OBJ_VTABLE *_;
    kino_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
    kino_BitVec_get_t get;
    kino_BitVec_set_t set;
    kino_BitVec_clear_t clear;
    kino_BitVec_grow_t grow;
    kino_BitVec_logical_and_t logical_and;
    kino_BitVec_count_t count;
    kino_BitVec_to_array_t to_array;
};

extern KINO_BITVECTOR_VTABLE KINO_BITVECTOR;

#ifdef KINO_USE_SHORT_NAMES
  #define BitVector kino_BitVector
  #define BITVECTOR KINO_BITVECTOR
  #define BitVec_new kino_BitVec_new
  #define BitVec_init_base kino_BitVec_init_base
  #define BitVec_clone kino_BitVec_clone
  #define BitVec_destroy kino_BitVec_destroy
  #define BitVec_get_t kino_BitVec_get_t
  #define BitVec_get kino_BitVec_get
  #define BitVec_set_t kino_BitVec_set_t
  #define BitVec_set kino_BitVec_set
  #define BitVec_clear_t kino_BitVec_clear_t
  #define BitVec_clear kino_BitVec_clear
  #define BitVec_grow_t kino_BitVec_grow_t
  #define BitVec_grow kino_BitVec_grow
  #define BitVec_logical_and_t kino_BitVec_logical_and_t
  #define BitVec_logical_and kino_BitVec_logical_and
  #define BitVec_count_t kino_BitVec_count_t
  #define BitVec_count kino_BitVec_count
  #define BitVec_to_array_t kino_BitVec_to_array_t
  #define BitVec_to_array kino_BitVec_to_array
  #define BitVec_Clone Kino_BitVec_Clone
  #define BitVec_Destroy Kino_BitVec_Destroy
  #define BitVec_Equals Kino_BitVec_Equals
  #define BitVec_Hash_Code Kino_BitVec_Hash_Code
  #define BitVec_Is_A Kino_BitVec_Is_A
  #define BitVec_To_String Kino_BitVec_To_String
  #define BitVec_Serialize Kino_BitVec_Serialize
  #define BitVec_Get Kino_BitVec_Get
  #define BitVec_Set Kino_BitVec_Set
  #define BitVec_Clear Kino_BitVec_Clear
  #define BitVec_Grow Kino_BitVec_Grow
  #define BitVec_Logical_And Kino_BitVec_Logical_And
  #define BitVec_Count Kino_BitVec_Count
  #define BitVec_To_Array Kino_BitVec_To_Array
  #define BITVECTOR KINO_BITVECTOR
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_BITVECTOR_MEMBER_VARS \
    kino_u32_t  refcount; \
    kino_u32_t  capacity; \
    kino_u8_t * bits; \
    kino_u32_t  count; \
    kino_bool_t  count_is_valid


#ifdef KINO_WANT_BITVECTOR_VTABLE
KINO_BITVECTOR_VTABLE KINO_BITVECTOR = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_OBJ,
    "KinoSearch::Util::BitVector",
    (kino_Obj_clone_t)kino_BitVec_clone,
    (kino_Obj_destroy_t)kino_BitVec_destroy,
    (kino_Obj_equals_t)kino_Obj_equals,
    (kino_Obj_hash_code_t)kino_Obj_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_Obj_to_string,
    (kino_Obj_serialize_t)kino_Obj_serialize,
    (kino_BitVec_get_t)kino_BitVec_get,
    (kino_BitVec_set_t)kino_BitVec_set,
    (kino_BitVec_clear_t)kino_BitVec_clear,
    (kino_BitVec_grow_t)kino_BitVec_grow,
    (kino_BitVec_logical_and_t)kino_BitVec_logical_and,
    (kino_BitVec_count_t)kino_BitVec_count,
    (kino_BitVec_to_array_t)kino_BitVec_to_array
};
#endif /* KINO_WANT_BITVECTOR_VTABLE */

#endif /* R_KINO_BITVEC */

/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */
