/** @file */
/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/

#ifndef R_KINO_BB
#define R_KINO_BB 1

#include "KinoSearch/Util/ByteBuf.h"

typedef kino_ByteBuf*
(*kino_BB_clone_t)(kino_ByteBuf *self);

typedef void
(*kino_BB_destroy_t)(kino_ByteBuf *self);

typedef kino_bool_t
(*kino_BB_equals_t)(kino_ByteBuf *self, kino_ByteBuf *other);

typedef kino_i32_t
(*kino_BB_hash_code_t)(kino_ByteBuf *self);

typedef kino_ByteBuf*
(*kino_BB_to_string_t)(kino_ByteBuf *self);

typedef void
(*kino_BB_serialize_t)(kino_ByteBuf *self, kino_ByteBuf *target);

typedef void
(*kino_BB_copy_str_t)(kino_ByteBuf *self, char* ptr, size_t size);

typedef void
(*kino_BB_copy_bb_t)(kino_ByteBuf *self, const kino_ByteBuf *other);

typedef void
(*kino_BB_cat_str_t)(kino_ByteBuf *self, char* ptr, size_t size);

typedef void
(*kino_BB_cat_bb_t)(kino_ByteBuf *self, const kino_ByteBuf *other);

typedef void
(*kino_BB_cat_i64_t)(kino_ByteBuf *self, kino_i64_t num);

typedef kino_i64_t
(*kino_BB_to_i64_t)(kino_ByteBuf *self);

typedef void
(*kino_BB_grow_t)(kino_ByteBuf *self, size_t new_size);

#define Kino_BB_Clone(_self) \
    (_self)->_->clone((kino_Obj*)_self)

#define Kino_BB_Destroy(_self) \
    (_self)->_->destroy((kino_Obj*)_self)

#define Kino_BB_Equals(_self, _arg1) \
    (_self)->_->equals((kino_Obj*)_self, _arg1)

#define Kino_BB_Hash_Code(_self) \
    (_self)->_->hash_code((kino_Obj*)_self)

#define Kino_BB_Is_A(_self, _arg1) \
    (_self)->_->is_a((kino_Obj*)_self, _arg1)

#define Kino_BB_To_String(_self) \
    (_self)->_->to_string((kino_Obj*)_self)

#define Kino_BB_Serialize(_self, _arg1) \
    (_self)->_->serialize((kino_Obj*)_self, _arg1)

#define Kino_BB_Copy_Str(_self, _arg1, _arg2) \
    (_self)->_->copy_str((kino_ByteBuf*)_self, _arg1, _arg2)

#define Kino_BB_Copy_BB(_self, _arg1) \
    (_self)->_->copy_bb((kino_ByteBuf*)_self, _arg1)

#define Kino_BB_Cat_Str(_self, _arg1, _arg2) \
    (_self)->_->cat_str((kino_ByteBuf*)_self, _arg1, _arg2)

#define Kino_BB_Cat_BB(_self, _arg1) \
    (_self)->_->cat_bb((kino_ByteBuf*)_self, _arg1)

#define Kino_BB_Cat_I64(_self, _arg1) \
    (_self)->_->cat_i64((kino_ByteBuf*)_self, _arg1)

#define Kino_BB_To_I64(_self) \
    (_self)->_->to_i64((kino_ByteBuf*)_self)

#define Kino_BB_Grow(_self, _arg1) \
    (_self)->_->grow((kino_ByteBuf*)_self, _arg1)

struct KINO_BYTEBUF_VTABLE {
    KINO_OBJ_VTABLE *_;
    kino_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
    kino_BB_copy_str_t copy_str;
    kino_BB_copy_bb_t copy_bb;
    kino_BB_cat_str_t cat_str;
    kino_BB_cat_bb_t cat_bb;
    kino_BB_cat_i64_t cat_i64;
    kino_BB_to_i64_t to_i64;
    kino_BB_grow_t grow;
};

extern KINO_BYTEBUF_VTABLE KINO_BYTEBUF;

#ifdef KINO_USE_SHORT_NAMES
  #define ByteBuf kino_ByteBuf
  #define BYTEBUF KINO_BYTEBUF
  #define BB_new kino_BB_new
  #define BB_new_str kino_BB_new_str
  #define BB_new_steal kino_BB_new_steal
  #define BB_new_i64 kino_BB_new_i64
  #define BB_compare kino_BB_compare
  #define BB_less_than kino_BB_less_than
  #define BB_deserialize kino_BB_deserialize
  #define BB_clone kino_BB_clone
  #define BB_destroy kino_BB_destroy
  #define BB_equals kino_BB_equals
  #define BB_hash_code kino_BB_hash_code
  #define BB_to_string kino_BB_to_string
  #define BB_serialize kino_BB_serialize
  #define BB_copy_str_t kino_BB_copy_str_t
  #define BB_copy_str kino_BB_copy_str
  #define BB_copy_bb_t kino_BB_copy_bb_t
  #define BB_copy_bb kino_BB_copy_bb
  #define BB_cat_str_t kino_BB_cat_str_t
  #define BB_cat_str kino_BB_cat_str
  #define BB_cat_bb_t kino_BB_cat_bb_t
  #define BB_cat_bb kino_BB_cat_bb
  #define BB_cat_i64_t kino_BB_cat_i64_t
  #define BB_cat_i64 kino_BB_cat_i64
  #define BB_to_i64_t kino_BB_to_i64_t
  #define BB_to_i64 kino_BB_to_i64
  #define BB_grow_t kino_BB_grow_t
  #define BB_grow kino_BB_grow
  #define BB_Clone Kino_BB_Clone
  #define BB_Destroy Kino_BB_Destroy
  #define BB_Equals Kino_BB_Equals
  #define BB_Hash_Code Kino_BB_Hash_Code
  #define BB_Is_A Kino_BB_Is_A
  #define BB_To_String Kino_BB_To_String
  #define BB_Serialize Kino_BB_Serialize
  #define BB_Copy_Str Kino_BB_Copy_Str
  #define BB_Copy_BB Kino_BB_Copy_BB
  #define BB_Cat_Str Kino_BB_Cat_Str
  #define BB_Cat_BB Kino_BB_Cat_BB
  #define BB_Cat_I64 Kino_BB_Cat_I64
  #define BB_To_I64 Kino_BB_To_I64
  #define BB_Grow Kino_BB_Grow
  #define BYTEBUF KINO_BYTEBUF
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_BYTEBUF_MEMBER_VARS \
    kino_u32_t  refcount; \
    char * ptr; \
    size_t  len; \
    size_t  cap


#ifdef KINO_WANT_BYTEBUF_VTABLE
KINO_BYTEBUF_VTABLE KINO_BYTEBUF = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_OBJ,
    "KinoSearch::Util::ByteBuf",
    (kino_Obj_clone_t)kino_BB_clone,
    (kino_Obj_destroy_t)kino_BB_destroy,
    (kino_Obj_equals_t)kino_BB_equals,
    (kino_Obj_hash_code_t)kino_BB_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_BB_to_string,
    (kino_Obj_serialize_t)kino_BB_serialize,
    (kino_BB_copy_str_t)kino_BB_copy_str,
    (kino_BB_copy_bb_t)kino_BB_copy_bb,
    (kino_BB_cat_str_t)kino_BB_cat_str,
    (kino_BB_cat_bb_t)kino_BB_cat_bb,
    (kino_BB_cat_i64_t)kino_BB_cat_i64,
    (kino_BB_to_i64_t)kino_BB_to_i64,
    (kino_BB_grow_t)kino_BB_grow
};
#endif /* KINO_WANT_BYTEBUF_VTABLE */

#endif /* R_KINO_BB */

/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */
