/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/

#ifndef R_KINO_DYNVT
#define R_KINO_DYNVT 1

#include "KinoSearch/Util/DynVirtualTable.h"

typedef void
(*kino_DynVT_destroy_t)(kino_DynVirtualTable *self);

#define Kino_DynVT_Clone(_self) \
    (_self)->_->clone((kino_Obj*)_self)

#define Kino_DynVT_Destroy(_self) \
    (_self)->_->destroy((kino_Obj*)_self)

#define Kino_DynVT_Equals(_self, _arg1) \
    (_self)->_->equals((kino_Obj*)_self, _arg1)

#define Kino_DynVT_Hash_Code(_self) \
    (_self)->_->hash_code((kino_Obj*)_self)

#define Kino_DynVT_Is_A(_self, _arg1) \
    (_self)->_->is_a((kino_Obj*)_self, _arg1)

#define Kino_DynVT_To_String(_self) \
    (_self)->_->to_string((kino_Obj*)_self)

#define Kino_DynVT_Serialize(_self, _arg1) \
    (_self)->_->serialize((kino_Obj*)_self, _arg1)

struct KINO_DYNVIRTUALTABLE_VTABLE {
    KINO_OBJ_VTABLE *_;
    kino_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
};

extern KINO_DYNVIRTUALTABLE_VTABLE KINO_DYNVIRTUALTABLE;

#ifdef KINO_USE_SHORT_NAMES
  #define DynVirtualTable kino_DynVirtualTable
  #define DYNVIRTUALTABLE KINO_DYNVIRTUALTABLE
  #define DynVT_singleton kino_DynVT_singleton
  #define DynVT_destroy kino_DynVT_destroy
  #define DynVT_Clone Kino_DynVT_Clone
  #define DynVT_Destroy Kino_DynVT_Destroy
  #define DynVT_Equals Kino_DynVT_Equals
  #define DynVT_Hash_Code Kino_DynVT_Hash_Code
  #define DynVT_Is_A Kino_DynVT_Is_A
  #define DynVT_To_String Kino_DynVT_To_String
  #define DynVT_Serialize Kino_DynVT_Serialize
  #define DYNVIRTUALTABLE KINO_DYNVIRTUALTABLE
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_DYNVIRTUALTABLE_MEMBER_VARS \
    KINO_OBJ_VTABLE * parent; \
    const char * class_name;


#ifdef KINO_WANT_DYNVIRTUALTABLE_VTABLE
KINO_DYNVIRTUALTABLE_VTABLE KINO_DYNVIRTUALTABLE = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    "KinoSearch::Util::DynVirtualTable",
    (kino_Obj_clone_t)kino_Obj_clone,
    (kino_Obj_destroy_t)kino_DynVT_destroy,
    (kino_Obj_equals_t)kino_Obj_equals,
    (kino_Obj_hash_code_t)kino_Obj_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_Obj_to_string,
    (kino_Obj_serialize_t)kino_Obj_serialize
};
#endif /* KINO_WANT_DYNVIRTUALTABLE_VTABLE */

#endif /* R_KINO_DYNVT */

/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */
