/** @file */
/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/

#ifndef R_KINO_INT
#define R_KINO_INT 1

#include "KinoSearch/Util/Int.h"

#define Kino_Int_Clone(_self) \
    (_self)->_->clone((kino_Obj*)_self)

#define Kino_Int_Destroy(_self) \
    (_self)->_->destroy((kino_Obj*)_self)

#define Kino_Int_Equals(_self, _arg1) \
    (_self)->_->equals((kino_Obj*)_self, _arg1)

#define Kino_Int_Hash_Code(_self) \
    (_self)->_->hash_code((kino_Obj*)_self)

#define Kino_Int_Is_A(_self, _arg1) \
    (_self)->_->is_a((kino_Obj*)_self, _arg1)

#define Kino_Int_To_String(_self) \
    (_self)->_->to_string((kino_Obj*)_self)

#define Kino_Int_Serialize(_self, _arg1) \
    (_self)->_->serialize((kino_Obj*)_self, _arg1)

struct KINO_INT_VTABLE {
    KINO_OBJ_VTABLE *_;
    kino_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
};

extern KINO_INT_VTABLE KINO_INT;

#ifdef KINO_USE_SHORT_NAMES
  #define Int kino_Int
  #define INT KINO_INT
  #define Int_new kino_Int_new
  #define Int_Clone Kino_Int_Clone
  #define Int_Destroy Kino_Int_Destroy
  #define Int_Equals Kino_Int_Equals
  #define Int_Hash_Code Kino_Int_Hash_Code
  #define Int_Is_A Kino_Int_Is_A
  #define Int_To_String Kino_Int_To_String
  #define Int_Serialize Kino_Int_Serialize
  #define INT KINO_INT
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_INT_MEMBER_VARS \
    kino_u32_t  refcount; \
    kino_i64_t  value


#ifdef KINO_WANT_INT_VTABLE
KINO_INT_VTABLE KINO_INT = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_OBJ,
    "KinoSearch::Util::Int",
    (kino_Obj_clone_t)kino_Obj_clone,
    (kino_Obj_destroy_t)kino_Obj_destroy,
    (kino_Obj_equals_t)kino_Obj_equals,
    (kino_Obj_hash_code_t)kino_Obj_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_Obj_to_string,
    (kino_Obj_serialize_t)kino_Obj_serialize
};
#endif /* KINO_WANT_INT_VTABLE */

#endif /* R_KINO_INT */

/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */
