/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/

#ifndef R_KINO_INTMAP
#define R_KINO_INTMAP 1

#include "KinoSearch/Util/IntMap.h"

typedef void
(*kino_IntMap_destroy_t)(kino_IntMap *self);

typedef kino_i32_t
(*kino_IntMap_get_t)(kino_IntMap *self, kino_i32_t num);

#define Kino_IntMap_Clone(_self) \
    (_self)->_->clone((kino_Obj*)_self)

#define Kino_IntMap_Destroy(_self) \
    (_self)->_->destroy((kino_Obj*)_self)

#define Kino_IntMap_Equals(_self, _arg1) \
    (_self)->_->equals((kino_Obj*)_self, _arg1)

#define Kino_IntMap_Hash_Code(_self) \
    (_self)->_->hash_code((kino_Obj*)_self)

#define Kino_IntMap_Is_A(_self, _arg1) \
    (_self)->_->is_a((kino_Obj*)_self, _arg1)

#define Kino_IntMap_To_String(_self) \
    (_self)->_->to_string((kino_Obj*)_self)

#define Kino_IntMap_Serialize(_self, _arg1) \
    (_self)->_->serialize((kino_Obj*)_self, _arg1)

#define Kino_IntMap_Get(_self, _arg1) \
    (_self)->_->get((kino_IntMap*)_self, _arg1)

struct KINO_INTMAP_VTABLE {
    KINO_OBJ_VTABLE *_;
    kino_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
    kino_IntMap_get_t get;
};

extern KINO_INTMAP_VTABLE KINO_INTMAP;

#ifdef KINO_USE_SHORT_NAMES
  #define IntMap kino_IntMap
  #define INTMAP KINO_INTMAP
  #define IntMap_new kino_IntMap_new
  #define IntMap_destroy kino_IntMap_destroy
  #define IntMap_get_t kino_IntMap_get_t
  #define IntMap_get kino_IntMap_get
  #define IntMap_Clone Kino_IntMap_Clone
  #define IntMap_Destroy Kino_IntMap_Destroy
  #define IntMap_Equals Kino_IntMap_Equals
  #define IntMap_Hash_Code Kino_IntMap_Hash_Code
  #define IntMap_Is_A Kino_IntMap_Is_A
  #define IntMap_To_String Kino_IntMap_To_String
  #define IntMap_Serialize Kino_IntMap_Serialize
  #define IntMap_Get Kino_IntMap_Get
  #define INTMAP KINO_INTMAP
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_INTMAP_MEMBER_VARS \
    kino_i32_t * ints; \
    kino_i32_t  size;


#ifdef KINO_WANT_INTMAP_VTABLE
KINO_INTMAP_VTABLE KINO_INTMAP = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_OBJ,
    "KinoSearch::Util::IntMap",
    (kino_Obj_clone_t)kino_Obj_clone,
    (kino_Obj_destroy_t)kino_IntMap_destroy,
    (kino_Obj_equals_t)kino_Obj_equals,
    (kino_Obj_hash_code_t)kino_Obj_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_Obj_to_string,
    (kino_Obj_serialize_t)kino_Obj_serialize,
    (kino_IntMap_get_t)kino_IntMap_get
};
#endif /* KINO_WANT_INTMAP_VTABLE */

#endif /* R_KINO_INTMAP */

/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */
