/** @file */
/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/

#ifndef R_KINO_PRIQ
#define R_KINO_PRIQ 1

#include "KinoSearch/Util/PriorityQueue.h"

typedef void
(*kino_PriQ_destroy_t)(kino_PriorityQueue *self);

typedef kino_bool_t
(*kino_PriQ_insert_t)(kino_PriorityQueue *self, void *element);

typedef void*
(*kino_PriQ_pop_t)(kino_PriorityQueue *self);

typedef void*
(*kino_PriQ_peek_t)(kino_PriorityQueue *self);

#define Kino_PriQ_Clone(_self) \
    (_self)->_->clone((kino_Obj*)_self)

#define Kino_PriQ_Destroy(_self) \
    (_self)->_->destroy((kino_Obj*)_self)

#define Kino_PriQ_Equals(_self, _arg1) \
    (_self)->_->equals((kino_Obj*)_self, _arg1)

#define Kino_PriQ_Hash_Code(_self) \
    (_self)->_->hash_code((kino_Obj*)_self)

#define Kino_PriQ_Is_A(_self, _arg1) \
    (_self)->_->is_a((kino_Obj*)_self, _arg1)

#define Kino_PriQ_To_String(_self) \
    (_self)->_->to_string((kino_Obj*)_self)

#define Kino_PriQ_Serialize(_self, _arg1) \
    (_self)->_->serialize((kino_Obj*)_self, _arg1)

#define Kino_PriQ_Insert(_self, _arg1) \
    (_self)->_->insert((kino_PriorityQueue*)_self, _arg1)

#define Kino_PriQ_Pop(_self) \
    (_self)->_->pop((kino_PriorityQueue*)_self)

#define Kino_PriQ_Peek(_self) \
    (_self)->_->peek((kino_PriorityQueue*)_self)

struct KINO_PRIORITYQUEUE_VTABLE {
    KINO_OBJ_VTABLE *_;
    kino_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
    kino_PriQ_insert_t insert;
    kino_PriQ_pop_t pop;
    kino_PriQ_peek_t peek;
};

extern KINO_PRIORITYQUEUE_VTABLE KINO_PRIORITYQUEUE;

#ifdef KINO_USE_SHORT_NAMES
  #define PriorityQueue kino_PriorityQueue
  #define PRIORITYQUEUE KINO_PRIORITYQUEUE
  #define PriQ_new kino_PriQ_new
  #define PriQ_init_base kino_PriQ_init_base
  #define PriQ_destroy kino_PriQ_destroy
  #define PriQ_insert_t kino_PriQ_insert_t
  #define PriQ_insert kino_PriQ_insert
  #define PriQ_pop_t kino_PriQ_pop_t
  #define PriQ_pop kino_PriQ_pop
  #define PriQ_peek_t kino_PriQ_peek_t
  #define PriQ_peek kino_PriQ_peek
  #define PriQ_Clone Kino_PriQ_Clone
  #define PriQ_Destroy Kino_PriQ_Destroy
  #define PriQ_Equals Kino_PriQ_Equals
  #define PriQ_Hash_Code Kino_PriQ_Hash_Code
  #define PriQ_Is_A Kino_PriQ_Is_A
  #define PriQ_To_String Kino_PriQ_To_String
  #define PriQ_Serialize Kino_PriQ_Serialize
  #define PriQ_Insert Kino_PriQ_Insert
  #define PriQ_Pop Kino_PriQ_Pop
  #define PriQ_Peek Kino_PriQ_Peek
  #define PRIORITYQUEUE KINO_PRIORITYQUEUE
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_PRIORITYQUEUE_MEMBER_VARS \
    kino_u32_t  refcount; \
    kino_u32_t  size; \
    kino_u32_t  max_size; \
    void ** heap; \
    kino_PriQ_less_than_t  less_than; \
    kino_PriQ_free_elem_t  free_elem


#ifdef KINO_WANT_PRIORITYQUEUE_VTABLE
KINO_PRIORITYQUEUE_VTABLE KINO_PRIORITYQUEUE = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_OBJ,
    "KinoSearch::Util::PriorityQueue",
    (kino_Obj_clone_t)kino_Obj_clone,
    (kino_Obj_destroy_t)kino_PriQ_destroy,
    (kino_Obj_equals_t)kino_Obj_equals,
    (kino_Obj_hash_code_t)kino_Obj_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_Obj_to_string,
    (kino_Obj_serialize_t)kino_Obj_serialize,
    (kino_PriQ_insert_t)kino_PriQ_insert,
    (kino_PriQ_pop_t)kino_PriQ_pop,
    (kino_PriQ_peek_t)kino_PriQ_peek
};
#endif /* KINO_WANT_PRIORITYQUEUE_VTABLE */

#endif /* R_KINO_PRIQ */

/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */
