/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/

#ifndef R_KINO_SORTEX
#define R_KINO_SORTEX 1

#include "KinoSearch/Util/SortExternal.h"

typedef void
(*kino_SortEx_destroy_t)(kino_SortExternal *self);

typedef void
(*kino_SortEx_feed_t)(kino_SortExternal *self, char *ptr, kino_u32_t len);

typedef void
(*kino_SortEx_feed_bb_t)(kino_SortExternal *self, struct kino_ByteBuf *bb);

typedef struct kino_ByteBuf*
(*kino_SortEx_fetch_t)(kino_SortExternal *self);

typedef void
(*kino_SortEx_sort_cache_t)(kino_SortExternal *self);

typedef void
(*kino_SortEx_sort_run_t)(kino_SortExternal *self);

#define Kino_SortEx_Clone(_self) \
    kino_Obj_clone((kino_Obj*)_self)

#define Kino_SortEx_Destroy(_self) \
    kino_SortEx_destroy((kino_SortExternal*)_self)

#define Kino_SortEx_Equals(_self, _arg1) \
    kino_Obj_equals((kino_Obj*)_self, _arg1)

#define Kino_SortEx_Hash_Code(_self) \
    kino_Obj_hash_code((kino_Obj*)_self)

#define Kino_SortEx_Is_A(_self, _arg1) \
    kino_Obj_is_a((kino_Obj*)_self, _arg1)

#define Kino_SortEx_To_String(_self) \
    kino_Obj_to_string((kino_Obj*)_self)

#define Kino_SortEx_Serialize(_self, _arg1) \
    kino_Obj_serialize((kino_Obj*)_self, _arg1)

#define Kino_SortEx_Feed(_self, _arg1, _arg2) \
    kino_SortEx_feed((kino_SortExternal*)_self, _arg1, _arg2)

#define Kino_SortEx_Feed_BB(_self, _arg1) \
    kino_SortEx_feed_bb((kino_SortExternal*)_self, _arg1)

#define Kino_SortEx_Fetch(_self) \
    kino_SortEx_fetch((kino_SortExternal*)_self)

#define Kino_SortEx_Sort_Cache(_self) \
    kino_SortEx_sort_cache((kino_SortExternal*)_self)

#define Kino_SortEx_Sort_Run(_self) \
    kino_SortEx_sort_run((kino_SortExternal*)_self)

struct KINO_SORTEXTERNAL_VTABLE {
    KINO_OBJ_VTABLE *_;
    kino_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
    kino_SortEx_feed_t feed;
    kino_SortEx_feed_bb_t feed_bb;
    kino_SortEx_fetch_t fetch;
    kino_SortEx_sort_cache_t sort_cache;
    kino_SortEx_sort_run_t sort_run;
};

extern KINO_SORTEXTERNAL_VTABLE KINO_SORTEXTERNAL;

#ifdef KINO_USE_SHORT_NAMES
  #define SortExternal kino_SortExternal
  #define SORTEXTERNAL KINO_SORTEXTERNAL
  #define SortEx_new kino_SortEx_new
  #define SortEx_destroy_t kino_SortEx_destroy_t
  #define SortEx_destroy kino_SortEx_destroy
  #define SortEx_feed_t kino_SortEx_feed_t
  #define SortEx_feed kino_SortEx_feed
  #define SortEx_feed_bb_t kino_SortEx_feed_bb_t
  #define SortEx_feed_bb kino_SortEx_feed_bb
  #define SortEx_fetch_t kino_SortEx_fetch_t
  #define SortEx_fetch kino_SortEx_fetch
  #define SortEx_sort_cache_t kino_SortEx_sort_cache_t
  #define SortEx_sort_cache kino_SortEx_sort_cache
  #define SortEx_sort_run_t kino_SortEx_sort_run_t
  #define SortEx_sort_run kino_SortEx_sort_run
  #define SortEx_Clone Kino_SortEx_Clone
  #define SortEx_Destroy Kino_SortEx_Destroy
  #define SortEx_Equals Kino_SortEx_Equals
  #define SortEx_Hash_Code Kino_SortEx_Hash_Code
  #define SortEx_Is_A Kino_SortEx_Is_A
  #define SortEx_To_String Kino_SortEx_To_String
  #define SortEx_Serialize Kino_SortEx_Serialize
  #define SortEx_Feed Kino_SortEx_Feed
  #define SortEx_Feed_BB Kino_SortEx_Feed_BB
  #define SortEx_Fetch Kino_SortEx_Fetch
  #define SortEx_Sort_Cache Kino_SortEx_Sort_Cache
  #define SortEx_Sort_Run Kino_SortEx_Sort_Run
  #define SORTEXTERNAL KINO_SORTEXTERNAL
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_SORTEXTERNAL_MEMBER_VARS \
    struct kino_ByteBuf ** cache; \
    kino_u32_t  cache_cap; \
    kino_u32_t  cache_elems; \
    kino_u32_t  cache_pos; \
    struct kino_ByteBuf ** scratch; \
    kino_u32_t  scratch_cap; \
    kino_u32_t  mem_threshold; \
    kino_u32_t  cache_bytes; \
    kino_u32_t  run_cache_limit; \
    kino_SortExRun ** runs; \
    kino_u32_t  num_runs; \
    struct kino_OutStream * outstream; \
    struct kino_InStream * instream; \
    struct kino_InvIndex * invindex; \
    struct kino_SegInfo * seg_info;


#ifdef KINO_WANT_SORTEXTERNAL_VTABLE
KINO_SORTEXTERNAL_VTABLE KINO_SORTEXTERNAL = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_OBJ,
    "KinoSearch::Util::SortExternal",
    (kino_Obj_clone_t)kino_Obj_clone,
    (kino_Obj_destroy_t)kino_SortEx_destroy,
    (kino_Obj_equals_t)kino_Obj_equals,
    (kino_Obj_hash_code_t)kino_Obj_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_Obj_to_string,
    (kino_Obj_serialize_t)kino_Obj_serialize,
    (kino_SortEx_feed_t)kino_SortEx_feed,
    (kino_SortEx_feed_bb_t)kino_SortEx_feed_bb,
    (kino_SortEx_fetch_t)kino_SortEx_fetch,
    (kino_SortEx_sort_cache_t)kino_SortEx_sort_cache,
    (kino_SortEx_sort_run_t)kino_SortEx_sort_run
};
#endif /* KINO_WANT_SORTEXTERNAL_VTABLE */

#endif /* R_KINO_SORTEX */

/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */
