/** @file */
/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/



#ifndef R_KINO_STEPPER
#define R_KINO_STEPPER 1

#include "KinoSearch/Util/Stepper.h"

#define KINO_STEPPER_BOILERPLATE

typedef void
(*kino_Stepper_read_record_t)(kino_Stepper *self, struct kino_InStream *instream);

typedef void
(*kino_Stepper_dump_t)(kino_Stepper *self, struct kino_InStream *instream);

typedef void
(*kino_Stepper_dump_to_file_t)(kino_Stepper *self, struct kino_InStream *instream,
                          struct kino_OutStream *outstream);

#define Kino_Stepper_Clone(self) \
    (self)->_->clone((kino_Obj*)self)

#define Kino_Stepper_Destroy(self) \
    (self)->_->destroy((kino_Obj*)self)

#define Kino_Stepper_Equals(self, other) \
    (self)->_->equals((kino_Obj*)self, other)

#define Kino_Stepper_Hash_Code(self) \
    (self)->_->hash_code((kino_Obj*)self)

#define Kino_Stepper_Is_A(self, target_vtable) \
    (self)->_->is_a((kino_Obj*)self, target_vtable)

#define Kino_Stepper_To_String(self) \
    (self)->_->to_string((kino_Obj*)self)

#define Kino_Stepper_Serialize(self, target) \
    (self)->_->serialize((kino_Obj*)self, target)

#define Kino_Stepper_Read_Record(self, instream) \
    (self)->_->read_record((kino_Stepper*)self, instream)

#define Kino_Stepper_Dump(self, instream) \
    (self)->_->dump((kino_Stepper*)self, instream)

#define Kino_Stepper_Dump_To_File(self, instream, outstream) \
    (self)->_->dump_to_file((kino_Stepper*)self, instream, outstream)

struct KINO_STEPPER_VTABLE {
    KINO_OBJ_VTABLE *_;
    chy_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
    kino_Stepper_read_record_t read_record;
    kino_Stepper_dump_t dump;
    kino_Stepper_dump_to_file_t dump_to_file;
};

extern KINO_STEPPER_VTABLE KINO_STEPPER;

#ifdef KINO_USE_SHORT_NAMES
  #define Stepper kino_Stepper
  #define STEPPER KINO_STEPPER
  #define Stepper_read_record_t kino_Stepper_read_record_t
  #define Stepper_read_record kino_Stepper_read_record
  #define Stepper_dump_t kino_Stepper_dump_t
  #define Stepper_dump kino_Stepper_dump
  #define Stepper_dump_to_file_t kino_Stepper_dump_to_file_t
  #define Stepper_dump_to_file kino_Stepper_dump_to_file
  #define Stepper_Clone Kino_Stepper_Clone
  #define Stepper_Destroy Kino_Stepper_Destroy
  #define Stepper_Equals Kino_Stepper_Equals
  #define Stepper_Hash_Code Kino_Stepper_Hash_Code
  #define Stepper_Is_A Kino_Stepper_Is_A
  #define Stepper_To_String Kino_Stepper_To_String
  #define Stepper_Serialize Kino_Stepper_Serialize
  #define Stepper_Read_Record Kino_Stepper_Read_Record
  #define Stepper_Dump Kino_Stepper_Dump
  #define Stepper_Dump_To_File Kino_Stepper_Dump_To_File
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_STEPPER_MEMBER_VARS \
    chy_u32_t  refcount

#ifdef KINO_WANT_STEPPER_VTABLE
KINO_STEPPER_VTABLE KINO_STEPPER = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_OBJ,
    "KinoSearch::Util::Stepper",
    (kino_Obj_clone_t)kino_Obj_clone,
    (kino_Obj_destroy_t)kino_Obj_destroy,
    (kino_Obj_equals_t)kino_Obj_equals,
    (kino_Obj_hash_code_t)kino_Obj_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_Obj_to_string,
    (kino_Obj_serialize_t)kino_Obj_serialize,
    (kino_Stepper_read_record_t)kino_Stepper_read_record,
    (kino_Stepper_dump_t)kino_Stepper_dump,
    (kino_Stepper_dump_to_file_t)kino_Stepper_dump_to_file
};
#endif /* KINO_WANT_STEPPER_VTABLE */

#undef KINO_STEPPER_BOILERPLATE


#endif /* R_KINO_STEPPER */


/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */

