/** @file */
/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/



#ifndef R_KINO_VARRAY
#define R_KINO_VARRAY 1

#include "KinoSearch/Util/VArray.h"

#define KINO_VARRAY_BOILERPLATE

typedef kino_VArray*
(*kino_VA_clone_t)(kino_VArray *self);

typedef void
(*kino_VA_destroy_t)(kino_VArray *self);

typedef void
(*kino_VA_push_t)(kino_VArray *self, kino_Obj *element);

typedef kino_Obj*
(*kino_VA_pop_t)(kino_VArray *self);

typedef void
(*kino_VA_unshift_t)(kino_VArray *self, kino_Obj *element);

typedef kino_Obj*
(*kino_VA_shift_t)(kino_VArray *self);

typedef void
(*kino_VA_grow_t)(kino_VArray *self, chy_u32_t capacity);

typedef kino_Obj*
(*kino_VA_fetch_t)(kino_VArray *self, chy_u32_t num);

typedef void
(*kino_VA_store_t)(kino_VArray *self, chy_u32_t num, kino_Obj *elem);

#define Kino_VA_Clone(self) \
    (self)->_->clone((kino_Obj*)self)

#define Kino_VA_Destroy(self) \
    (self)->_->destroy((kino_Obj*)self)

#define Kino_VA_Equals(self, other) \
    (self)->_->equals((kino_Obj*)self, other)

#define Kino_VA_Hash_Code(self) \
    (self)->_->hash_code((kino_Obj*)self)

#define Kino_VA_Is_A(self, target_vtable) \
    (self)->_->is_a((kino_Obj*)self, target_vtable)

#define Kino_VA_To_String(self) \
    (self)->_->to_string((kino_Obj*)self)

#define Kino_VA_Serialize(self, target) \
    (self)->_->serialize((kino_Obj*)self, target)

#define Kino_VA_Push(self, element) \
    (self)->_->push((kino_VArray*)self, element)

#define Kino_VA_Pop(self) \
    (self)->_->pop((kino_VArray*)self)

#define Kino_VA_Unshift(self, element) \
    (self)->_->unshift((kino_VArray*)self, element)

#define Kino_VA_Shift(self) \
    (self)->_->shift((kino_VArray*)self)

#define Kino_VA_Grow(self, capacity) \
    (self)->_->grow((kino_VArray*)self, capacity)

#define Kino_VA_Fetch(self, num) \
    (self)->_->fetch((kino_VArray*)self, num)

#define Kino_VA_Store(self, num, elem) \
    (self)->_->store((kino_VArray*)self, num, elem)

struct KINO_VARRAY_VTABLE {
    KINO_OBJ_VTABLE *_;
    chy_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
    kino_VA_push_t push;
    kino_VA_pop_t pop;
    kino_VA_unshift_t unshift;
    kino_VA_shift_t shift;
    kino_VA_grow_t grow;
    kino_VA_fetch_t fetch;
    kino_VA_store_t store;
};

extern KINO_VARRAY_VTABLE KINO_VARRAY;

#ifdef KINO_USE_SHORT_NAMES
  #define VArray kino_VArray
  #define VARRAY KINO_VARRAY
  #define VA_new kino_VA_new
  #define VA_clone kino_VA_clone
  #define VA_destroy kino_VA_destroy
  #define VA_push_t kino_VA_push_t
  #define VA_push kino_VA_push
  #define VA_pop_t kino_VA_pop_t
  #define VA_pop kino_VA_pop
  #define VA_unshift_t kino_VA_unshift_t
  #define VA_unshift kino_VA_unshift
  #define VA_shift_t kino_VA_shift_t
  #define VA_shift kino_VA_shift
  #define VA_grow_t kino_VA_grow_t
  #define VA_grow kino_VA_grow
  #define VA_fetch_t kino_VA_fetch_t
  #define VA_fetch kino_VA_fetch
  #define VA_store_t kino_VA_store_t
  #define VA_store kino_VA_store
  #define VA_Clone Kino_VA_Clone
  #define VA_Destroy Kino_VA_Destroy
  #define VA_Equals Kino_VA_Equals
  #define VA_Hash_Code Kino_VA_Hash_Code
  #define VA_Is_A Kino_VA_Is_A
  #define VA_To_String Kino_VA_To_String
  #define VA_Serialize Kino_VA_Serialize
  #define VA_Push Kino_VA_Push
  #define VA_Pop Kino_VA_Pop
  #define VA_Unshift Kino_VA_Unshift
  #define VA_Shift Kino_VA_Shift
  #define VA_Grow Kino_VA_Grow
  #define VA_Fetch Kino_VA_Fetch
  #define VA_Store Kino_VA_Store
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_VARRAY_MEMBER_VARS \
    chy_u32_t  refcount; \
    kino_Obj ** elems; \
    chy_u32_t  size; \
    chy_u32_t  cap

#ifdef KINO_WANT_VARRAY_VTABLE
KINO_VARRAY_VTABLE KINO_VARRAY = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_OBJ,
    "KinoSearch::Util::VArray",
    (kino_Obj_clone_t)kino_VA_clone,
    (kino_Obj_destroy_t)kino_VA_destroy,
    (kino_Obj_equals_t)kino_Obj_equals,
    (kino_Obj_hash_code_t)kino_Obj_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_Obj_to_string,
    (kino_Obj_serialize_t)kino_Obj_serialize,
    (kino_VA_push_t)kino_VA_push,
    (kino_VA_pop_t)kino_VA_pop,
    (kino_VA_unshift_t)kino_VA_unshift,
    (kino_VA_shift_t)kino_VA_shift,
    (kino_VA_grow_t)kino_VA_grow,
    (kino_VA_fetch_t)kino_VA_fetch,
    (kino_VA_store_t)kino_VA_store
};
#endif /* KINO_WANT_VARRAY_VTABLE */

#undef KINO_VARRAY_BOILERPLATE


#endif /* R_KINO_VARRAY */


/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */

