/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/

#ifndef R_KINO_VIRTUALTABLE
#define R_KINO_VIRTUALTABLE 1

#include "KinoSearch/Util/VirtualTable.h"

typedef void
(*kino_VirtualTable_destroy_t)(kino_VirtualTable *self);

#define Kino_VirtualTable_Clone(_self) \
    (_self)->_->clone((kino_Obj*)_self)

#define Kino_VirtualTable_Destroy(_self) \
    (_self)->_->destroy((kino_Obj*)_self)

#define Kino_VirtualTable_Equals(_self, _arg1) \
    (_self)->_->equals((kino_Obj*)_self, _arg1)

#define Kino_VirtualTable_Hash_Code(_self) \
    (_self)->_->hash_code((kino_Obj*)_self)

#define Kino_VirtualTable_Is_A(_self, _arg1) \
    (_self)->_->is_a((kino_Obj*)_self, _arg1)

#define Kino_VirtualTable_To_String(_self) \
    (_self)->_->to_string((kino_Obj*)_self)

#define Kino_VirtualTable_Serialize(_self, _arg1) \
    (_self)->_->serialize((kino_Obj*)_self, _arg1)

struct KINO_VIRTUALTABLE_VTABLE {
    KINO_OBJ_VTABLE *_;
    kino_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
};

extern KINO_VIRTUALTABLE_VTABLE KINO_VIRTUALTABLE;

#ifdef KINO_USE_SHORT_NAMES
  #define VirtualTable kino_VirtualTable
  #define VIRTUALTABLE KINO_VIRTUALTABLE
  #define VirtualTable_destroy kino_VirtualTable_destroy
  #define VirtualTable_Clone Kino_VirtualTable_Clone
  #define VirtualTable_Destroy Kino_VirtualTable_Destroy
  #define VirtualTable_Equals Kino_VirtualTable_Equals
  #define VirtualTable_Hash_Code Kino_VirtualTable_Hash_Code
  #define VirtualTable_Is_A Kino_VirtualTable_Is_A
  #define VirtualTable_To_String Kino_VirtualTable_To_String
  #define VirtualTable_Serialize Kino_VirtualTable_Serialize
  #define VIRTUALTABLE KINO_VIRTUALTABLE
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_VIRTUALTABLE_MEMBER_VARS \
    KINO_OBJ_VTABLE * parent; \
    const char * class_name;


#ifdef KINO_WANT_VIRTUALTABLE_VTABLE
KINO_VIRTUALTABLE_VTABLE KINO_VIRTUALTABLE = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_OBJ,
    "KinoSearch::Util::VirtualTable",
    (kino_Obj_clone_t)kino_Obj_clone,
    (kino_Obj_destroy_t)kino_VirtualTable_destroy,
    (kino_Obj_equals_t)kino_Obj_equals,
    (kino_Obj_hash_code_t)kino_Obj_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_Obj_to_string,
    (kino_Obj_serialize_t)kino_Obj_serialize
};
#endif /* KINO_WANT_VIRTUALTABLE_VTABLE */

#endif /* R_KINO_VIRTUALTABLE */

/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */
