/** @file */
/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/

#ifndef R_KINO_DELDOCS
#define R_KINO_DELDOCS 1

#include "KinoSearch/Index/DelDocs.h"

typedef void
(*kino_DelDocs_destroy_t)(kino_DelDocs *self);

typedef void
(*kino_DelDocs_read_deldocs_t)(kino_DelDocs *self);

typedef void
(*kino_DelDocs_write_deldocs_t)(kino_DelDocs *self);

typedef struct kino_IntMap*
(*kino_DelDocs_generate_doc_map_t)(kino_DelDocs *self, kino_i32_t offset);

typedef void
(*kino_DelDocs_delete_by_term_docs_t)(kino_DelDocs *self, 
                                 struct kino_TermDocs *term_docs);

#define Kino_DelDocs_Clone(_self) \
    kino_BitVec_clone((kino_BitVector*)_self)

#define Kino_DelDocs_Destroy(_self) \
    kino_DelDocs_destroy((kino_DelDocs*)_self)

#define Kino_DelDocs_Equals(_self, _arg1) \
    kino_Obj_equals((kino_Obj*)_self, _arg1)

#define Kino_DelDocs_Hash_Code(_self) \
    kino_Obj_hash_code((kino_Obj*)_self)

#define Kino_DelDocs_Is_A(_self, _arg1) \
    kino_Obj_is_a((kino_Obj*)_self, _arg1)

#define Kino_DelDocs_To_String(_self) \
    kino_Obj_to_string((kino_Obj*)_self)

#define Kino_DelDocs_Serialize(_self, _arg1) \
    kino_Obj_serialize((kino_Obj*)_self, _arg1)

#define Kino_DelDocs_Get(_self, _arg1) \
    kino_BitVec_get((kino_BitVector*)_self, _arg1)

#define Kino_DelDocs_Set(_self, _arg1) \
    kino_BitVec_set((kino_BitVector*)_self, _arg1)

#define Kino_DelDocs_Clear(_self, _arg1) \
    kino_BitVec_clear((kino_BitVector*)_self, _arg1)

#define Kino_DelDocs_Grow(_self, _arg1) \
    kino_BitVec_grow((kino_BitVector*)_self, _arg1)

#define Kino_DelDocs_Logical_And(_self, _arg1) \
    kino_BitVec_logical_and((kino_BitVector*)_self, _arg1)

#define Kino_DelDocs_Count(_self) \
    kino_BitVec_count((kino_BitVector*)_self)

#define Kino_DelDocs_To_Array(_self) \
    kino_BitVec_to_array((kino_BitVector*)_self)

#define Kino_DelDocs_Read_Deldocs(_self) \
    kino_DelDocs_read_deldocs((kino_DelDocs*)_self)

#define Kino_DelDocs_Write_Deldocs(_self) \
    kino_DelDocs_write_deldocs((kino_DelDocs*)_self)

#define Kino_DelDocs_Generate_Doc_Map(_self, _arg1) \
    kino_DelDocs_generate_doc_map((kino_DelDocs*)_self, _arg1)

#define Kino_DelDocs_Delete_By_Term_Docs(_self, _arg1) \
    kino_DelDocs_delete_by_term_docs((kino_DelDocs*)_self, _arg1)

struct KINO_DELDOCS_VTABLE {
    KINO_OBJ_VTABLE *_;
    kino_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
    kino_BitVec_get_t get;
    kino_BitVec_set_t set;
    kino_BitVec_clear_t clear;
    kino_BitVec_grow_t grow;
    kino_BitVec_logical_and_t logical_and;
    kino_BitVec_count_t count;
    kino_BitVec_to_array_t to_array;
    kino_DelDocs_read_deldocs_t read_deldocs;
    kino_DelDocs_write_deldocs_t write_deldocs;
    kino_DelDocs_generate_doc_map_t generate_doc_map;
    kino_DelDocs_delete_by_term_docs_t delete_by_term_docs;
};

extern KINO_DELDOCS_VTABLE KINO_DELDOCS;

#ifdef KINO_USE_SHORT_NAMES
  #define DelDocs kino_DelDocs
  #define DELDOCS KINO_DELDOCS
  #define DelDocs_new kino_DelDocs_new
  #define DelDocs_destroy_t kino_DelDocs_destroy_t
  #define DelDocs_destroy kino_DelDocs_destroy
  #define DelDocs_read_deldocs_t kino_DelDocs_read_deldocs_t
  #define DelDocs_read_deldocs kino_DelDocs_read_deldocs
  #define DelDocs_write_deldocs_t kino_DelDocs_write_deldocs_t
  #define DelDocs_write_deldocs kino_DelDocs_write_deldocs
  #define DelDocs_generate_doc_map_t kino_DelDocs_generate_doc_map_t
  #define DelDocs_generate_doc_map kino_DelDocs_generate_doc_map
  #define DelDocs_delete_by_term_docs_t kino_DelDocs_delete_by_term_docs_t
  #define DelDocs_delete_by_term_docs kino_DelDocs_delete_by_term_docs
  #define DelDocs_Clone Kino_DelDocs_Clone
  #define DelDocs_Destroy Kino_DelDocs_Destroy
  #define DelDocs_Equals Kino_DelDocs_Equals
  #define DelDocs_Hash_Code Kino_DelDocs_Hash_Code
  #define DelDocs_Is_A Kino_DelDocs_Is_A
  #define DelDocs_To_String Kino_DelDocs_To_String
  #define DelDocs_Serialize Kino_DelDocs_Serialize
  #define DelDocs_Get Kino_DelDocs_Get
  #define DelDocs_Set Kino_DelDocs_Set
  #define DelDocs_Clear Kino_DelDocs_Clear
  #define DelDocs_Grow Kino_DelDocs_Grow
  #define DelDocs_Logical_And Kino_DelDocs_Logical_And
  #define DelDocs_Count Kino_DelDocs_Count
  #define DelDocs_To_Array Kino_DelDocs_To_Array
  #define DelDocs_Read_Deldocs Kino_DelDocs_Read_Deldocs
  #define DelDocs_Write_Deldocs Kino_DelDocs_Write_Deldocs
  #define DelDocs_Generate_Doc_Map Kino_DelDocs_Generate_Doc_Map
  #define DelDocs_Delete_By_Term_Docs Kino_DelDocs_Delete_By_Term_Docs
  #define DELDOCS KINO_DELDOCS
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_DELDOCS_MEMBER_VARS \
    kino_u32_t  refcount; \
    kino_u32_t  capacity; \
    kino_u8_t * bits; \
    kino_u32_t  count; \
    kino_bool_t  count_is_valid; \
    kino_i32_t  del_gen; \
    struct kino_InvIndex * invindex; \
    struct kino_SegInfo * seg_info


#ifdef KINO_WANT_DELDOCS_VTABLE
KINO_DELDOCS_VTABLE KINO_DELDOCS = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_BITVECTOR,
    "KinoSearch::Index::DelDocs",
    (kino_Obj_clone_t)kino_BitVec_clone,
    (kino_Obj_destroy_t)kino_DelDocs_destroy,
    (kino_Obj_equals_t)kino_Obj_equals,
    (kino_Obj_hash_code_t)kino_Obj_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_Obj_to_string,
    (kino_Obj_serialize_t)kino_Obj_serialize,
    (kino_BitVec_get_t)kino_BitVec_get,
    (kino_BitVec_set_t)kino_BitVec_set,
    (kino_BitVec_clear_t)kino_BitVec_clear,
    (kino_BitVec_grow_t)kino_BitVec_grow,
    (kino_BitVec_logical_and_t)kino_BitVec_logical_and,
    (kino_BitVec_count_t)kino_BitVec_count,
    (kino_BitVec_to_array_t)kino_BitVec_to_array,
    (kino_DelDocs_read_deldocs_t)kino_DelDocs_read_deldocs,
    (kino_DelDocs_write_deldocs_t)kino_DelDocs_write_deldocs,
    (kino_DelDocs_generate_doc_map_t)kino_DelDocs_generate_doc_map,
    (kino_DelDocs_delete_by_term_docs_t)kino_DelDocs_delete_by_term_docs
};
#endif /* KINO_WANT_DELDOCS_VTABLE */

#endif /* R_KINO_DELDOCS */

/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */
