/** @file */
/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/



#ifndef R_KINO_LEXICON
#define R_KINO_LEXICON 1

#include "KinoSearch/Index/Lexicon.h"

#define KINO_LEXICON_BOILERPLATE

typedef void
(*kino_Lex_seek_t)(kino_Lexicon *self, struct kino_Term *term);

typedef chy_bool_t
(*kino_Lex_next_t)(kino_Lexicon *self);

typedef void
(*kino_Lex_reset_t)(kino_Lexicon* self);

typedef chy_i32_t
(*kino_Lex_get_size_t)(kino_Lexicon *self);

typedef chy_i32_t
(*kino_Lex_get_term_num_t)(kino_Lexicon *self);

typedef struct kino_Term*
(*kino_Lex_get_term_t)(kino_Lexicon *self);

typedef struct kino_IntMap*
(*kino_Lex_build_sort_cache_t)(kino_Lexicon *self, 
                          struct kino_PostingList *plist, 
                          chy_u32_t max_doc);

typedef void
(*kino_Lex_seek_by_num_t)(kino_Lexicon *self, chy_i32_t term_num);

#define Kino_Lex_Clone(self) \
    (self)->_->clone((kino_Obj*)self)

#define Kino_Lex_Destroy(self) \
    (self)->_->destroy((kino_Obj*)self)

#define Kino_Lex_Equals(self, other) \
    (self)->_->equals((kino_Obj*)self, other)

#define Kino_Lex_Hash_Code(self) \
    (self)->_->hash_code((kino_Obj*)self)

#define Kino_Lex_Is_A(self, target_vtable) \
    (self)->_->is_a((kino_Obj*)self, target_vtable)

#define Kino_Lex_To_String(self) \
    (self)->_->to_string((kino_Obj*)self)

#define Kino_Lex_Serialize(self, target) \
    (self)->_->serialize((kino_Obj*)self, target)

#define Kino_Lex_Seek(self, term) \
    (self)->_->seek((kino_Lexicon*)self, term)

#define Kino_Lex_Next(self) \
    (self)->_->next((kino_Lexicon*)self)

#define Kino_Lex_Reset(self) \
    (self)->_->reset((kino_Lexicon*)self)

#define Kino_Lex_Get_Size(self) \
    (self)->_->get_size((kino_Lexicon*)self)

#define Kino_Lex_Get_Term_Num(self) \
    (self)->_->get_term_num((kino_Lexicon*)self)

#define Kino_Lex_Get_Term(self) \
    (self)->_->get_term((kino_Lexicon*)self)

#define Kino_Lex_Build_Sort_Cache(self, plist, max_doc) \
    (self)->_->build_sort_cache((kino_Lexicon*)self, plist, max_doc)

#define Kino_Lex_Seek_By_Num(self, term_num) \
    (self)->_->seek_by_num((kino_Lexicon*)self, term_num)

struct KINO_LEXICON_VTABLE {
    KINO_OBJ_VTABLE *_;
    chy_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
    kino_Lex_seek_t seek;
    kino_Lex_next_t next;
    kino_Lex_reset_t reset;
    kino_Lex_get_size_t get_size;
    kino_Lex_get_term_num_t get_term_num;
    kino_Lex_get_term_t get_term;
    kino_Lex_build_sort_cache_t build_sort_cache;
    kino_Lex_seek_by_num_t seek_by_num;
};

extern KINO_LEXICON_VTABLE KINO_LEXICON;

#ifdef KINO_USE_SHORT_NAMES
  #define Lexicon kino_Lexicon
  #define LEXICON KINO_LEXICON
  #define Lex_seek_t kino_Lex_seek_t
  #define Lex_seek kino_Lex_seek
  #define Lex_next_t kino_Lex_next_t
  #define Lex_next kino_Lex_next
  #define Lex_reset_t kino_Lex_reset_t
  #define Lex_reset kino_Lex_reset
  #define Lex_get_size_t kino_Lex_get_size_t
  #define Lex_get_size kino_Lex_get_size
  #define Lex_get_term_num_t kino_Lex_get_term_num_t
  #define Lex_get_term_num kino_Lex_get_term_num
  #define Lex_get_term_t kino_Lex_get_term_t
  #define Lex_get_term kino_Lex_get_term
  #define Lex_build_sort_cache_t kino_Lex_build_sort_cache_t
  #define Lex_build_sort_cache kino_Lex_build_sort_cache
  #define Lex_seek_by_num_t kino_Lex_seek_by_num_t
  #define Lex_seek_by_num kino_Lex_seek_by_num
  #define Lex_Clone Kino_Lex_Clone
  #define Lex_Destroy Kino_Lex_Destroy
  #define Lex_Equals Kino_Lex_Equals
  #define Lex_Hash_Code Kino_Lex_Hash_Code
  #define Lex_Is_A Kino_Lex_Is_A
  #define Lex_To_String Kino_Lex_To_String
  #define Lex_Serialize Kino_Lex_Serialize
  #define Lex_Seek Kino_Lex_Seek
  #define Lex_Next Kino_Lex_Next
  #define Lex_Reset Kino_Lex_Reset
  #define Lex_Get_Size Kino_Lex_Get_Size
  #define Lex_Get_Term_Num Kino_Lex_Get_Term_Num
  #define Lex_Get_Term Kino_Lex_Get_Term
  #define Lex_Build_Sort_Cache Kino_Lex_Build_Sort_Cache
  #define Lex_Seek_By_Num Kino_Lex_Seek_By_Num
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_LEXICON_MEMBER_VARS \
    chy_u32_t  refcount

#ifdef KINO_WANT_LEXICON_VTABLE
KINO_LEXICON_VTABLE KINO_LEXICON = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_OBJ,
    "KinoSearch::Index::Lexicon",
    (kino_Obj_clone_t)kino_Obj_clone,
    (kino_Obj_destroy_t)kino_Obj_destroy,
    (kino_Obj_equals_t)kino_Obj_equals,
    (kino_Obj_hash_code_t)kino_Obj_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_Obj_to_string,
    (kino_Obj_serialize_t)kino_Obj_serialize,
    (kino_Lex_seek_t)kino_Lex_seek,
    (kino_Lex_next_t)kino_Lex_next,
    (kino_Lex_reset_t)kino_Lex_reset,
    (kino_Lex_get_size_t)kino_Lex_get_size,
    (kino_Lex_get_term_num_t)kino_Lex_get_term_num,
    (kino_Lex_get_term_t)kino_Lex_get_term,
    (kino_Lex_build_sort_cache_t)kino_Lex_build_sort_cache,
    (kino_Lex_seek_by_num_t)kino_Lex_seek_by_num
};
#endif /* KINO_WANT_LEXICON_VTABLE */

#undef KINO_LEXICON_BOILERPLATE


#endif /* R_KINO_LEXICON */


/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */

