/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/

#ifndef R_KINO_SEGINFO
#define R_KINO_SEGINFO 1

#include "KinoSearch/Index/SegInfo.h"

typedef void
(*kino_SegInfo_destroy_t)(kino_SegInfo *self);

typedef void
(*kino_SegInfo_add_metadata_t)(kino_SegInfo *self, const char *key, size_t key_len,
                          kino_Obj *value);

typedef struct kino_Hash*
(*kino_SegInfo_get_metadata_t)(kino_SegInfo *self);

typedef kino_Obj*
(*kino_SegInfo_extract_metadata_t)(kino_SegInfo *self, const char *key, 
                              size_t key_len);

typedef struct kino_ByteBuf*
(*kino_SegInfo_field_name_t)(kino_SegInfo *self, kino_i32_t field_num);

typedef kino_i32_t
(*kino_SegInfo_field_num_t)(kino_SegInfo *self, 
                       const struct kino_ByteBuf *field_name);

typedef struct kino_IntMap*
(*kino_SegInfo_generate_field_num_map_t)(kino_SegInfo *self, kino_SegInfo *other);

#define Kino_SegInfo_Clone(_self) \
    kino_Obj_clone((kino_Obj*)_self)

#define Kino_SegInfo_Destroy(_self) \
    kino_SegInfo_destroy((kino_SegInfo*)_self)

#define Kino_SegInfo_Equals(_self, _arg1) \
    kino_Obj_equals((kino_Obj*)_self, _arg1)

#define Kino_SegInfo_Hash_Code(_self) \
    kino_Obj_hash_code((kino_Obj*)_self)

#define Kino_SegInfo_Is_A(_self, _arg1) \
    kino_Obj_is_a((kino_Obj*)_self, _arg1)

#define Kino_SegInfo_To_String(_self) \
    kino_Obj_to_string((kino_Obj*)_self)

#define Kino_SegInfo_Serialize(_self, _arg1) \
    kino_Obj_serialize((kino_Obj*)_self, _arg1)

#define Kino_SegInfo_Add_Metadata(_self, _arg1, _arg2, _arg3) \
    kino_SegInfo_add_metadata((kino_SegInfo*)_self, _arg1, _arg2, _arg3)

#define Kino_SegInfo_Get_Metadata(_self) \
    kino_SegInfo_get_metadata((kino_SegInfo*)_self)

#define Kino_SegInfo_Extract_Metadata(_self, _arg1, _arg2) \
    kino_SegInfo_extract_metadata((kino_SegInfo*)_self, _arg1, _arg2)

#define Kino_SegInfo_Field_Name(_self, _arg1) \
    kino_SegInfo_field_name((kino_SegInfo*)_self, _arg1)

#define Kino_SegInfo_Field_Num(_self, _arg1) \
    kino_SegInfo_field_num((kino_SegInfo*)_self, _arg1)

#define Kino_SegInfo_Generate_Field_Num_Map(_self, _arg1) \
    kino_SegInfo_generate_field_num_map((kino_SegInfo*)_self, _arg1)

struct KINO_SEGINFO_VTABLE {
    KINO_OBJ_VTABLE *_;
    kino_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
    kino_SegInfo_add_metadata_t add_metadata;
    kino_SegInfo_get_metadata_t get_metadata;
    kino_SegInfo_extract_metadata_t extract_metadata;
    kino_SegInfo_field_name_t field_name;
    kino_SegInfo_field_num_t field_num;
    kino_SegInfo_generate_field_num_map_t generate_field_num_map;
};

extern KINO_SEGINFO_VTABLE KINO_SEGINFO;

#ifdef KINO_USE_SHORT_NAMES
  #define SegInfo kino_SegInfo
  #define SEGINFO KINO_SEGINFO
  #define SegInfo_new kino_SegInfo_new
  #define SegInfo_destroy_t kino_SegInfo_destroy_t
  #define SegInfo_destroy kino_SegInfo_destroy
  #define SegInfo_add_metadata_t kino_SegInfo_add_metadata_t
  #define SegInfo_add_metadata kino_SegInfo_add_metadata
  #define SegInfo_get_metadata_t kino_SegInfo_get_metadata_t
  #define SegInfo_get_metadata kino_SegInfo_get_metadata
  #define SegInfo_extract_metadata_t kino_SegInfo_extract_metadata_t
  #define SegInfo_extract_metadata kino_SegInfo_extract_metadata
  #define SegInfo_field_name_t kino_SegInfo_field_name_t
  #define SegInfo_field_name kino_SegInfo_field_name
  #define SegInfo_field_num_t kino_SegInfo_field_num_t
  #define SegInfo_field_num kino_SegInfo_field_num
  #define SegInfo_generate_field_num_map_t kino_SegInfo_generate_field_num_map_t
  #define SegInfo_generate_field_num_map kino_SegInfo_generate_field_num_map
  #define SegInfo_Clone Kino_SegInfo_Clone
  #define SegInfo_Destroy Kino_SegInfo_Destroy
  #define SegInfo_Equals Kino_SegInfo_Equals
  #define SegInfo_Hash_Code Kino_SegInfo_Hash_Code
  #define SegInfo_Is_A Kino_SegInfo_Is_A
  #define SegInfo_To_String Kino_SegInfo_To_String
  #define SegInfo_Serialize Kino_SegInfo_Serialize
  #define SegInfo_Add_Metadata Kino_SegInfo_Add_Metadata
  #define SegInfo_Get_Metadata Kino_SegInfo_Get_Metadata
  #define SegInfo_Extract_Metadata Kino_SegInfo_Extract_Metadata
  #define SegInfo_Field_Name Kino_SegInfo_Field_Name
  #define SegInfo_Field_Num Kino_SegInfo_Field_Num
  #define SegInfo_Generate_Field_Num_Map Kino_SegInfo_Generate_Field_Num_Map
  #define SEGINFO KINO_SEGINFO
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_SEGINFO_MEMBER_VARS \
    struct kino_ByteBuf * seg_name; \
    kino_u32_t  doc_count; \
    struct kino_Hash * by_name; \
    struct kino_VArray * by_num; \
    struct kino_Hash * metadata;


#ifdef KINO_WANT_SEGINFO_VTABLE
KINO_SEGINFO_VTABLE KINO_SEGINFO = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_OBJ,
    "KinoSearch::Index::SegInfo",
    (kino_Obj_clone_t)kino_Obj_clone,
    (kino_Obj_destroy_t)kino_SegInfo_destroy,
    (kino_Obj_equals_t)kino_Obj_equals,
    (kino_Obj_hash_code_t)kino_Obj_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_Obj_to_string,
    (kino_Obj_serialize_t)kino_Obj_serialize,
    (kino_SegInfo_add_metadata_t)kino_SegInfo_add_metadata,
    (kino_SegInfo_get_metadata_t)kino_SegInfo_get_metadata,
    (kino_SegInfo_extract_metadata_t)kino_SegInfo_extract_metadata,
    (kino_SegInfo_field_name_t)kino_SegInfo_field_name,
    (kino_SegInfo_field_num_t)kino_SegInfo_field_num,
    (kino_SegInfo_generate_field_num_map_t)kino_SegInfo_generate_field_num_map
};
#endif /* KINO_WANT_SEGINFO_VTABLE */

#endif /* R_KINO_SEGINFO */

/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */
