/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/

#ifndef R_KINO_TERMDOCS
#define R_KINO_TERMDOCS 1

#include "KinoSearch/Index/TermDocs.h"

typedef void
(*kino_TermDocs_set_doc_freq_t)(kino_TermDocs *self, kino_u32_t doc_freq);

typedef kino_u32_t
(*kino_TermDocs_get_doc_freq_t)(kino_TermDocs *self);

typedef kino_u32_t
(*kino_TermDocs_get_doc_t)(kino_TermDocs *self);

typedef kino_u32_t
(*kino_TermDocs_get_freq_t)(kino_TermDocs *self);

typedef kino_u8_t
(*kino_TermDocs_get_field_boost_byte_t)(kino_TermDocs *self);

typedef struct kino_ByteBuf*
(*kino_TermDocs_get_positions_t)(kino_TermDocs *self);

typedef struct kino_ByteBuf*
(*kino_TermDocs_get_boosts_t)(kino_TermDocs *self);

typedef void
(*kino_TermDocs_seek_t)(kino_TermDocs *self, struct kino_Term *target);

typedef void
(*kino_TermDocs_seek_tl_t)(kino_TermDocs *self, struct kino_TermList *term_list);

typedef kino_bool_t
(*kino_TermDocs_next_t)(kino_TermDocs *self);

typedef kino_bool_t
(*kino_TermDocs_skip_to_t)(kino_TermDocs *self, kino_u32_t target);

typedef kino_u32_t
(*kino_TermDocs_bulk_read_t)(kino_TermDocs *self, 
                        struct kino_ByteBuf *doc_nums_bb, 
                        struct kino_ByteBuf *field_boosts_bb, 
                        struct kino_ByteBuf *freqs_bb, 
                        struct kino_ByteBuf *prox_bb, 
                        struct kino_ByteBuf *boosts_bb, 
                        kino_u32_t num_wanted);

#define Kino_TermDocs_Clone(_self) \
    (_self)->_->clone((kino_Obj*)_self)

#define Kino_TermDocs_Destroy(_self) \
    (_self)->_->destroy((kino_Obj*)_self)

#define Kino_TermDocs_Equals(_self, _arg1) \
    (_self)->_->equals((kino_Obj*)_self, _arg1)

#define Kino_TermDocs_Hash_Code(_self) \
    (_self)->_->hash_code((kino_Obj*)_self)

#define Kino_TermDocs_Is_A(_self, _arg1) \
    (_self)->_->is_a((kino_Obj*)_self, _arg1)

#define Kino_TermDocs_To_String(_self) \
    (_self)->_->to_string((kino_Obj*)_self)

#define Kino_TermDocs_Serialize(_self, _arg1) \
    (_self)->_->serialize((kino_Obj*)_self, _arg1)

#define Kino_TermDocs_Set_Doc_Freq(_self, _arg1) \
    (_self)->_->set_doc_freq((kino_TermDocs*)_self, _arg1)

#define Kino_TermDocs_Get_Doc_Freq(_self) \
    (_self)->_->get_doc_freq((kino_TermDocs*)_self)

#define Kino_TermDocs_Get_Doc(_self) \
    (_self)->_->get_doc((kino_TermDocs*)_self)

#define Kino_TermDocs_Get_Freq(_self) \
    (_self)->_->get_freq((kino_TermDocs*)_self)

#define Kino_TermDocs_Get_Field_Boost_Byte(_self) \
    (_self)->_->get_field_boost_byte((kino_TermDocs*)_self)

#define Kino_TermDocs_Get_Positions(_self) \
    (_self)->_->get_positions((kino_TermDocs*)_self)

#define Kino_TermDocs_Get_Boosts(_self) \
    (_self)->_->get_boosts((kino_TermDocs*)_self)

#define Kino_TermDocs_Seek(_self, _arg1) \
    (_self)->_->seek((kino_TermDocs*)_self, _arg1)

#define Kino_TermDocs_Seek_TL(_self, _arg1) \
    (_self)->_->seek_tl((kino_TermDocs*)_self, _arg1)

#define Kino_TermDocs_Next(_self) \
    (_self)->_->next((kino_TermDocs*)_self)

#define Kino_TermDocs_Skip_To(_self, _arg1) \
    (_self)->_->skip_to((kino_TermDocs*)_self, _arg1)

#define Kino_TermDocs_Bulk_Read(_self, _arg1, _arg2, _arg3, _arg4, _arg5, _arg6) \
    (_self)->_->bulk_read((kino_TermDocs*)_self, _arg1, _arg2, _arg3, _arg4, _arg5, _arg6)

struct KINO_TERMDOCS_VTABLE {
    KINO_OBJ_VTABLE *_;
    kino_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
    kino_TermDocs_set_doc_freq_t set_doc_freq;
    kino_TermDocs_get_doc_freq_t get_doc_freq;
    kino_TermDocs_get_doc_t get_doc;
    kino_TermDocs_get_freq_t get_freq;
    kino_TermDocs_get_field_boost_byte_t get_field_boost_byte;
    kino_TermDocs_get_positions_t get_positions;
    kino_TermDocs_get_boosts_t get_boosts;
    kino_TermDocs_seek_t seek;
    kino_TermDocs_seek_tl_t seek_tl;
    kino_TermDocs_next_t next;
    kino_TermDocs_skip_to_t skip_to;
    kino_TermDocs_bulk_read_t bulk_read;
};

extern KINO_TERMDOCS_VTABLE KINO_TERMDOCS;

#ifdef KINO_USE_SHORT_NAMES
  #define TermDocs kino_TermDocs
  #define TERMDOCS KINO_TERMDOCS
  #define TermDocs_set_doc_freq_t kino_TermDocs_set_doc_freq_t
  #define TermDocs_set_doc_freq kino_TermDocs_set_doc_freq
  #define TermDocs_get_doc_freq_t kino_TermDocs_get_doc_freq_t
  #define TermDocs_get_doc_freq kino_TermDocs_get_doc_freq
  #define TermDocs_get_doc_t kino_TermDocs_get_doc_t
  #define TermDocs_get_doc kino_TermDocs_get_doc
  #define TermDocs_get_freq_t kino_TermDocs_get_freq_t
  #define TermDocs_get_freq kino_TermDocs_get_freq
  #define TermDocs_get_field_boost_byte_t kino_TermDocs_get_field_boost_byte_t
  #define TermDocs_get_field_boost_byte kino_TermDocs_get_field_boost_byte
  #define TermDocs_get_positions_t kino_TermDocs_get_positions_t
  #define TermDocs_get_positions kino_TermDocs_get_positions
  #define TermDocs_get_boosts_t kino_TermDocs_get_boosts_t
  #define TermDocs_get_boosts kino_TermDocs_get_boosts
  #define TermDocs_seek_t kino_TermDocs_seek_t
  #define TermDocs_seek kino_TermDocs_seek
  #define TermDocs_seek_tl_t kino_TermDocs_seek_tl_t
  #define TermDocs_seek_tl kino_TermDocs_seek_tl
  #define TermDocs_next_t kino_TermDocs_next_t
  #define TermDocs_next kino_TermDocs_next
  #define TermDocs_skip_to_t kino_TermDocs_skip_to_t
  #define TermDocs_skip_to kino_TermDocs_skip_to
  #define TermDocs_bulk_read_t kino_TermDocs_bulk_read_t
  #define TermDocs_bulk_read kino_TermDocs_bulk_read
  #define TermDocs_Clone Kino_TermDocs_Clone
  #define TermDocs_Destroy Kino_TermDocs_Destroy
  #define TermDocs_Equals Kino_TermDocs_Equals
  #define TermDocs_Hash_Code Kino_TermDocs_Hash_Code
  #define TermDocs_Is_A Kino_TermDocs_Is_A
  #define TermDocs_To_String Kino_TermDocs_To_String
  #define TermDocs_Serialize Kino_TermDocs_Serialize
  #define TermDocs_Set_Doc_Freq Kino_TermDocs_Set_Doc_Freq
  #define TermDocs_Get_Doc_Freq Kino_TermDocs_Get_Doc_Freq
  #define TermDocs_Get_Doc Kino_TermDocs_Get_Doc
  #define TermDocs_Get_Freq Kino_TermDocs_Get_Freq
  #define TermDocs_Get_Field_Boost_Byte Kino_TermDocs_Get_Field_Boost_Byte
  #define TermDocs_Get_Positions Kino_TermDocs_Get_Positions
  #define TermDocs_Get_Boosts Kino_TermDocs_Get_Boosts
  #define TermDocs_Seek Kino_TermDocs_Seek
  #define TermDocs_Seek_TL Kino_TermDocs_Seek_TL
  #define TermDocs_Next Kino_TermDocs_Next
  #define TermDocs_Skip_To Kino_TermDocs_Skip_To
  #define TermDocs_Bulk_Read Kino_TermDocs_Bulk_Read
  #define TERMDOCS KINO_TERMDOCS
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_TERMDOCS_MEMBER_VARS \
    


#ifdef KINO_WANT_TERMDOCS_VTABLE
KINO_TERMDOCS_VTABLE KINO_TERMDOCS = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_OBJ,
    "KinoSearch::Index::TermDocs",
    (kino_Obj_clone_t)kino_Obj_clone,
    (kino_Obj_destroy_t)kino_Obj_destroy,
    (kino_Obj_equals_t)kino_Obj_equals,
    (kino_Obj_hash_code_t)kino_Obj_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_Obj_to_string,
    (kino_Obj_serialize_t)kino_Obj_serialize,
    (kino_TermDocs_set_doc_freq_t)kino_TermDocs_set_doc_freq,
    (kino_TermDocs_get_doc_freq_t)kino_TermDocs_get_doc_freq,
    (kino_TermDocs_get_doc_t)kino_TermDocs_get_doc,
    (kino_TermDocs_get_freq_t)kino_TermDocs_get_freq,
    (kino_TermDocs_get_field_boost_byte_t)kino_TermDocs_get_field_boost_byte,
    (kino_TermDocs_get_positions_t)kino_TermDocs_get_positions,
    (kino_TermDocs_get_boosts_t)kino_TermDocs_get_boosts,
    (kino_TermDocs_seek_t)kino_TermDocs_seek,
    (kino_TermDocs_seek_tl_t)kino_TermDocs_seek_tl,
    (kino_TermDocs_next_t)kino_TermDocs_next,
    (kino_TermDocs_skip_to_t)kino_TermDocs_skip_to,
    (kino_TermDocs_bulk_read_t)kino_TermDocs_bulk_read
};
#endif /* KINO_WANT_TERMDOCS_VTABLE */

#endif /* R_KINO_TERMDOCS */

/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */
