/** @file */
/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/



#ifndef R_KINO_TERMVECTORSREADER
#define R_KINO_TERMVECTORSREADER 1

#include "KinoSearch/Index/TermVectorsReader.h"

#define KINO_TERMVECTORSREADER_BOILERPLATE

typedef void
(*kino_TVReader_destroy_t)(kino_TermVectorsReader *self);

typedef void
(*kino_TVReader_read_record_t)(kino_TermVectorsReader *self, 
                          chy_i32_t doc_num,
                          struct kino_ByteBuf *buffer);

#define Kino_TVReader_Clone(self) \
    kino_Obj_clone((kino_Obj*)self)

#define Kino_TVReader_Destroy(self) \
    kino_TVReader_destroy((kino_TermVectorsReader*)self)

#define Kino_TVReader_Equals(self, other) \
    kino_Obj_equals((kino_Obj*)self, other)

#define Kino_TVReader_Hash_Code(self) \
    kino_Obj_hash_code((kino_Obj*)self)

#define Kino_TVReader_Is_A(self, target_vtable) \
    kino_Obj_is_a((kino_Obj*)self, target_vtable)

#define Kino_TVReader_To_String(self) \
    kino_Obj_to_string((kino_Obj*)self)

#define Kino_TVReader_Serialize(self, target) \
    kino_Obj_serialize((kino_Obj*)self, target)

#define Kino_TVReader_Read_Record(self, doc_num, buffer) \
    kino_TVReader_read_record((kino_TermVectorsReader*)self, doc_num, buffer)

struct KINO_TERMVECTORSREADER_VTABLE {
    KINO_OBJ_VTABLE *_;
    chy_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
    kino_TVReader_read_record_t read_record;
};

extern KINO_TERMVECTORSREADER_VTABLE KINO_TERMVECTORSREADER;

#ifdef KINO_USE_SHORT_NAMES
  #define TermVectorsReader kino_TermVectorsReader
  #define TERMVECTORSREADER KINO_TERMVECTORSREADER
  #define TVReader_new kino_TVReader_new
  #define TVReader_destroy_t kino_TVReader_destroy_t
  #define TVReader_destroy kino_TVReader_destroy
  #define TVReader_read_record_t kino_TVReader_read_record_t
  #define TVReader_read_record kino_TVReader_read_record
  #define TVReader_Clone Kino_TVReader_Clone
  #define TVReader_Destroy Kino_TVReader_Destroy
  #define TVReader_Equals Kino_TVReader_Equals
  #define TVReader_Hash_Code Kino_TVReader_Hash_Code
  #define TVReader_Is_A Kino_TVReader_Is_A
  #define TVReader_To_String Kino_TVReader_To_String
  #define TVReader_Serialize Kino_TVReader_Serialize
  #define TVReader_Read_Record Kino_TVReader_Read_Record
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_TERMVECTORSREADER_MEMBER_VARS \
    chy_u32_t  refcount; \
    struct kino_Schema * schema; \
    struct kino_Folder * folder; \
    struct kino_SegInfo * seg_info; \
    struct kino_InStream * tv_in; \
    struct kino_InStream * tvx_in

#ifdef KINO_WANT_TERMVECTORSREADER_VTABLE
KINO_TERMVECTORSREADER_VTABLE KINO_TERMVECTORSREADER = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_OBJ,
    "KinoSearch::Index::TermVectorsReader",
    (kino_Obj_clone_t)kino_Obj_clone,
    (kino_Obj_destroy_t)kino_TVReader_destroy,
    (kino_Obj_equals_t)kino_Obj_equals,
    (kino_Obj_hash_code_t)kino_Obj_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_Obj_to_string,
    (kino_Obj_serialize_t)kino_Obj_serialize,
    (kino_TVReader_read_record_t)kino_TVReader_read_record
};
#endif /* KINO_WANT_TERMVECTORSREADER_VTABLE */

#undef KINO_TERMVECTORSREADER_BOILERPLATE


#endif /* R_KINO_TERMVECTORSREADER */


/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */

