/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/

#ifndef R_KINO_TLWRITER
#define R_KINO_TLWRITER 1

#include "KinoSearch/Index/TermListWriter.h"

typedef void
(*kino_TLWriter_destroy_t)(kino_TermListWriter *self);

typedef void
(*kino_TLWriter_add_t)(kino_TermListWriter* self, 
                  struct kino_ByteBuf* term_text,
                  struct kino_TermInfo* tinfo);

typedef void
(*kino_TLWriter_finish_t)(kino_TermListWriter *self);

#define Kino_TLWriter_Clone(_self) \
    kino_Obj_clone((kino_Obj*)_self)

#define Kino_TLWriter_Destroy(_self) \
    kino_TLWriter_destroy((kino_TermListWriter*)_self)

#define Kino_TLWriter_Equals(_self, _arg1) \
    kino_Obj_equals((kino_Obj*)_self, _arg1)

#define Kino_TLWriter_Hash_Code(_self) \
    kino_Obj_hash_code((kino_Obj*)_self)

#define Kino_TLWriter_Is_A(_self, _arg1) \
    kino_Obj_is_a((kino_Obj*)_self, _arg1)

#define Kino_TLWriter_To_String(_self) \
    kino_Obj_to_string((kino_Obj*)_self)

#define Kino_TLWriter_Serialize(_self, _arg1) \
    kino_Obj_serialize((kino_Obj*)_self, _arg1)

#define Kino_TLWriter_Add(_self, _arg1, _arg2) \
    kino_TLWriter_add((kino_TermListWriter*)_self, _arg1, _arg2)

#define Kino_TLWriter_Finish(_self) \
    kino_TLWriter_finish((kino_TermListWriter*)_self)

struct KINO_TERMLISTWRITER_VTABLE {
    KINO_OBJ_VTABLE *_;
    kino_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
    kino_TLWriter_add_t add;
    kino_TLWriter_finish_t finish;
};

extern KINO_TERMLISTWRITER_VTABLE KINO_TERMLISTWRITER;

#ifdef KINO_USE_SHORT_NAMES
  #define TermListWriter kino_TermListWriter
  #define TERMLISTWRITER KINO_TERMLISTWRITER
  #define TLWriter_new kino_TLWriter_new
  #define TLWriter_destroy_t kino_TLWriter_destroy_t
  #define TLWriter_destroy kino_TLWriter_destroy
  #define TLWriter_add_t kino_TLWriter_add_t
  #define TLWriter_add kino_TLWriter_add
  #define TLWriter_finish_t kino_TLWriter_finish_t
  #define TLWriter_finish kino_TLWriter_finish
  #define TLWriter_Clone Kino_TLWriter_Clone
  #define TLWriter_Destroy Kino_TLWriter_Destroy
  #define TLWriter_Equals Kino_TLWriter_Equals
  #define TLWriter_Hash_Code Kino_TLWriter_Hash_Code
  #define TLWriter_Is_A Kino_TLWriter_Is_A
  #define TLWriter_To_String Kino_TLWriter_To_String
  #define TLWriter_Serialize Kino_TLWriter_Serialize
  #define TLWriter_Add Kino_TLWriter_Add
  #define TLWriter_Finish Kino_TLWriter_Finish
  #define TERMLISTWRITER KINO_TERMLISTWRITER
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_TERMLISTWRITER_MEMBER_VARS \
    struct kino_InvIndex * invindex; \
    struct kino_SegInfo * seg_info; \
    struct kino_OutStream * fh; \
    struct kino_ByteBuf * filename; \
    struct kino_Hash * counts; \
    kino_i32_t  is_index; \
    kino_i32_t  index_interval; \
    kino_i32_t  skip_interval; \
    kino_TermListWriter * other; \
    struct kino_ByteBuf * last_text; \
    struct kino_TermInfo * last_tinfo; \
    kino_u64_t  last_tl_ptr; \
    kino_i64_t  size;


#ifdef KINO_WANT_TERMLISTWRITER_VTABLE
KINO_TERMLISTWRITER_VTABLE KINO_TERMLISTWRITER = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_OBJ,
    "KinoSearch::Index::TermListWriter",
    (kino_Obj_clone_t)kino_Obj_clone,
    (kino_Obj_destroy_t)kino_TLWriter_destroy,
    (kino_Obj_equals_t)kino_Obj_equals,
    (kino_Obj_hash_code_t)kino_Obj_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_Obj_to_string,
    (kino_Obj_serialize_t)kino_Obj_serialize,
    (kino_TLWriter_add_t)kino_TLWriter_add,
    (kino_TLWriter_finish_t)kino_TLWriter_finish
};
#endif /* KINO_WANT_TERMLISTWRITER_VTABLE */

#endif /* R_KINO_TLWRITER */

/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */
