/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/

#ifndef R_KINO_FSFILEDES
#define R_KINO_FSFILEDES 1

#include "KinoSearch/Store/FSFileDes.h"

typedef void
(*kino_FSFileDes_destroy_t)(kino_FSFileDes *self);

typedef void
(*kino_FSFileDes_fdseek_t)(kino_FSFileDes *self, kino_u64_t target);

typedef void
(*kino_FSFileDes_fdread_t)(kino_FSFileDes *self, char *dest, 
                      kino_u32_t dest_offset, kino_u32_t len);

typedef void
(*kino_FSFileDes_fdwrite_t)(kino_FSFileDes *self, char* buf, kino_u32_t len);

typedef kino_u64_t
(*kino_FSFileDes_fdlength_t)(kino_FSFileDes *self);

typedef void
(*kino_FSFileDes_fdclose_t)(kino_FSFileDes *self);

#define Kino_FSFileDes_Clone(_self) \
    (_self)->_->clone((kino_Obj*)_self)

#define Kino_FSFileDes_Destroy(_self) \
    (_self)->_->destroy((kino_Obj*)_self)

#define Kino_FSFileDes_Equals(_self, _arg1) \
    (_self)->_->equals((kino_Obj*)_self, _arg1)

#define Kino_FSFileDes_Hash_Code(_self) \
    (_self)->_->hash_code((kino_Obj*)_self)

#define Kino_FSFileDes_Is_A(_self, _arg1) \
    (_self)->_->is_a((kino_Obj*)_self, _arg1)

#define Kino_FSFileDes_To_String(_self) \
    (_self)->_->to_string((kino_Obj*)_self)

#define Kino_FSFileDes_Serialize(_self, _arg1) \
    (_self)->_->serialize((kino_Obj*)_self, _arg1)

#define Kino_FSFileDes_FDSeek(_self, _arg1) \
    (_self)->_->fdseek((kino_FileDes*)_self, _arg1)

#define Kino_FSFileDes_FDRead(_self, _arg1, _arg2, _arg3) \
    (_self)->_->fdread((kino_FileDes*)_self, _arg1, _arg2, _arg3)

#define Kino_FSFileDes_FDWrite(_self, _arg1, _arg2) \
    (_self)->_->fdwrite((kino_FileDes*)_self, _arg1, _arg2)

#define Kino_FSFileDes_FDLength(_self) \
    (_self)->_->fdlength((kino_FileDes*)_self)

#define Kino_FSFileDes_FDClose(_self) \
    (_self)->_->fdclose((kino_FileDes*)_self)

struct KINO_FSFILEDES_VTABLE {
    KINO_OBJ_VTABLE *_;
    kino_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
    kino_FileDes_fdseek_t fdseek;
    kino_FileDes_fdread_t fdread;
    kino_FileDes_fdwrite_t fdwrite;
    kino_FileDes_fdlength_t fdlength;
    kino_FileDes_fdclose_t fdclose;
};

extern KINO_FSFILEDES_VTABLE KINO_FSFILEDES;

#ifdef KINO_USE_SHORT_NAMES
  #define FSFileDes kino_FSFileDes
  #define FSFILEDES KINO_FSFILEDES
  #define FSFileDes_new kino_FSFileDes_new
  #define FSFileDes_destroy kino_FSFileDes_destroy
  #define FSFileDes_fdseek kino_FSFileDes_fdseek
  #define FSFileDes_fdread kino_FSFileDes_fdread
  #define FSFileDes_fdwrite kino_FSFileDes_fdwrite
  #define FSFileDes_fdlength kino_FSFileDes_fdlength
  #define FSFileDes_fdclose kino_FSFileDes_fdclose
  #define FSFileDes_Clone Kino_FSFileDes_Clone
  #define FSFileDes_Destroy Kino_FSFileDes_Destroy
  #define FSFileDes_Equals Kino_FSFileDes_Equals
  #define FSFileDes_Hash_Code Kino_FSFileDes_Hash_Code
  #define FSFileDes_Is_A Kino_FSFileDes_Is_A
  #define FSFileDes_To_String Kino_FSFileDes_To_String
  #define FSFileDes_Serialize Kino_FSFileDes_Serialize
  #define FSFileDes_FDSeek Kino_FSFileDes_FDSeek
  #define FSFileDes_FDRead Kino_FSFileDes_FDRead
  #define FSFileDes_FDWrite Kino_FSFileDes_FDWrite
  #define FSFileDes_FDLength Kino_FSFileDes_FDLength
  #define FSFileDes_FDClose Kino_FSFileDes_FDClose
  #define FSFILEDES KINO_FSFILEDES
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_FSFILEDES_MEMBER_VARS \
    char * path; \
    char * mode; \
    kino_u64_t  pos; \
    kino_i32_t  stream_count; \
    FILE * fhandle;


#ifdef KINO_WANT_FSFILEDES_VTABLE
KINO_FSFILEDES_VTABLE KINO_FSFILEDES = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_FILEDES,
    "KinoSearch::Store::FSFileDes",
    (kino_Obj_clone_t)kino_Obj_clone,
    (kino_Obj_destroy_t)kino_FSFileDes_destroy,
    (kino_Obj_equals_t)kino_Obj_equals,
    (kino_Obj_hash_code_t)kino_Obj_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_Obj_to_string,
    (kino_Obj_serialize_t)kino_Obj_serialize,
    (kino_FileDes_fdseek_t)kino_FSFileDes_fdseek,
    (kino_FileDes_fdread_t)kino_FSFileDes_fdread,
    (kino_FileDes_fdwrite_t)kino_FSFileDes_fdwrite,
    (kino_FileDes_fdlength_t)kino_FSFileDes_fdlength,
    (kino_FileDes_fdclose_t)kino_FSFileDes_fdclose
};
#endif /* KINO_WANT_FSFILEDES_VTABLE */

#endif /* R_KINO_FSFILEDES */

/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */
