/** @file */
/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/



#ifndef R_KINO_LOCKFACTORY
#define R_KINO_LOCKFACTORY 1

#include "KinoSearch/Store/LockFactory.h"

#define KINO_LOCKFACTORY_BOILERPLATE

typedef void
(*kino_LockFact_destroy_t)(kino_LockFactory *self);

typedef struct kino_Lock*
(*kino_LockFact_make_lock_t)(kino_LockFactory *self, 
                        const struct kino_ByteBuf *lock_name, 
                        chy_i32_t timeout);

typedef struct kino_SharedLock*
(*kino_LockFact_make_shared_lock_t)(kino_LockFactory *self, 
                               const struct kino_ByteBuf *lock_name, 
                               chy_i32_t timeout);

#define Kino_LockFact_Clone(self) \
    (self)->_->clone((kino_Obj*)self)

#define Kino_LockFact_Destroy(self) \
    (self)->_->destroy((kino_Obj*)self)

#define Kino_LockFact_Equals(self, other) \
    (self)->_->equals((kino_Obj*)self, other)

#define Kino_LockFact_Hash_Code(self) \
    (self)->_->hash_code((kino_Obj*)self)

#define Kino_LockFact_Is_A(self, target_vtable) \
    (self)->_->is_a((kino_Obj*)self, target_vtable)

#define Kino_LockFact_To_String(self) \
    (self)->_->to_string((kino_Obj*)self)

#define Kino_LockFact_Serialize(self, target) \
    (self)->_->serialize((kino_Obj*)self, target)

#define Kino_LockFact_Make_Lock(self, lock_name, timeout) \
    (self)->_->make_lock((kino_LockFactory*)self, lock_name, timeout)

#define Kino_LockFact_Make_Shared_Lock(self, lock_name, timeout) \
    (self)->_->make_shared_lock((kino_LockFactory*)self, lock_name, timeout)

struct KINO_LOCKFACTORY_VTABLE {
    KINO_OBJ_VTABLE *_;
    chy_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
    kino_LockFact_make_lock_t make_lock;
    kino_LockFact_make_shared_lock_t make_shared_lock;
};

extern KINO_LOCKFACTORY_VTABLE KINO_LOCKFACTORY;

#ifdef KINO_USE_SHORT_NAMES
  #define LockFactory kino_LockFactory
  #define LOCKFACTORY KINO_LOCKFACTORY
  #define LockFact_new kino_LockFact_new
  #define LockFact_destroy kino_LockFact_destroy
  #define LockFact_make_lock_t kino_LockFact_make_lock_t
  #define LockFact_make_lock kino_LockFact_make_lock
  #define LockFact_make_shared_lock_t kino_LockFact_make_shared_lock_t
  #define LockFact_make_shared_lock kino_LockFact_make_shared_lock
  #define LockFact_Clone Kino_LockFact_Clone
  #define LockFact_Destroy Kino_LockFact_Destroy
  #define LockFact_Equals Kino_LockFact_Equals
  #define LockFact_Hash_Code Kino_LockFact_Hash_Code
  #define LockFact_Is_A Kino_LockFact_Is_A
  #define LockFact_To_String Kino_LockFact_To_String
  #define LockFact_Serialize Kino_LockFact_Serialize
  #define LockFact_Make_Lock Kino_LockFact_Make_Lock
  #define LockFact_Make_Shared_Lock Kino_LockFact_Make_Shared_Lock
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_LOCKFACTORY_MEMBER_VARS \
    chy_u32_t  refcount; \
    struct kino_Folder * folder; \
    struct kino_ByteBuf * agent_id

#ifdef KINO_WANT_LOCKFACTORY_VTABLE
KINO_LOCKFACTORY_VTABLE KINO_LOCKFACTORY = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_OBJ,
    "KinoSearch::Store::LockFactory",
    (kino_Obj_clone_t)kino_Obj_clone,
    (kino_Obj_destroy_t)kino_LockFact_destroy,
    (kino_Obj_equals_t)kino_Obj_equals,
    (kino_Obj_hash_code_t)kino_Obj_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_Obj_to_string,
    (kino_Obj_serialize_t)kino_Obj_serialize,
    (kino_LockFact_make_lock_t)kino_LockFact_make_lock,
    (kino_LockFact_make_shared_lock_t)kino_LockFact_make_shared_lock
};
#endif /* KINO_WANT_LOCKFACTORY_VTABLE */

#undef KINO_LOCKFACTORY_BOILERPLATE


#endif /* R_KINO_LOCKFACTORY */


/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */

