/** @file */
/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/



#ifndef R_KINO_RAMFILEDES
#define R_KINO_RAMFILEDES 1

#include "KinoSearch/Store/RAMFileDes.h"

#define KINO_RAMFILEDES_BOILERPLATE

typedef void
(*kino_RAMFileDes_destroy_t)(kino_RAMFileDes *self);

typedef chy_bool_t
(*kino_RAMFileDes_fdseek_t)(kino_RAMFileDes *self, chy_u64_t target);

typedef chy_bool_t
(*kino_RAMFileDes_fdread_t)(kino_RAMFileDes *self, char *dest, 
                       chy_u32_t dest_offset, chy_u32_t len);

typedef chy_bool_t
(*kino_RAMFileDes_fdwrite_t)(kino_RAMFileDes *self, const char* buf, 
                        chy_u32_t len);

typedef chy_u64_t
(*kino_RAMFileDes_fdlength_t)(kino_RAMFileDes *self);

typedef chy_bool_t
(*kino_RAMFileDes_fdclose_t)(kino_RAMFileDes *self);

typedef struct kino_ByteBuf*
(*kino_RAMFileDes_contents_t)(kino_RAMFileDes *self);

#define Kino_RAMFileDes_Clone(self) \
    (self)->_->clone((kino_Obj*)self)

#define Kino_RAMFileDes_Destroy(self) \
    (self)->_->destroy((kino_Obj*)self)

#define Kino_RAMFileDes_Equals(self, other) \
    (self)->_->equals((kino_Obj*)self, other)

#define Kino_RAMFileDes_Hash_Code(self) \
    (self)->_->hash_code((kino_Obj*)self)

#define Kino_RAMFileDes_Is_A(self, target_vtable) \
    (self)->_->is_a((kino_Obj*)self, target_vtable)

#define Kino_RAMFileDes_To_String(self) \
    (self)->_->to_string((kino_Obj*)self)

#define Kino_RAMFileDes_Serialize(self, target) \
    (self)->_->serialize((kino_Obj*)self, target)

#define Kino_RAMFileDes_FDSeek(self, target) \
    (self)->_->fdseek((kino_FileDes*)self, target)

#define Kino_RAMFileDes_FDRead(self, dest, dest_offset, len) \
    (self)->_->fdread((kino_FileDes*)self, dest, dest_offset, len)

#define Kino_RAMFileDes_FDWrite(self, buf, len) \
    (self)->_->fdwrite((kino_FileDes*)self, buf, len)

#define Kino_RAMFileDes_FDLength(self) \
    (self)->_->fdlength((kino_FileDes*)self)

#define Kino_RAMFileDes_FDClose(self) \
    (self)->_->fdclose((kino_FileDes*)self)

#define Kino_RAMFileDes_Contents(self) \
    (self)->_->contents((kino_RAMFileDes*)self)

struct KINO_RAMFILEDES_VTABLE {
    KINO_OBJ_VTABLE *_;
    chy_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
    kino_FileDes_fdseek_t fdseek;
    kino_FileDes_fdread_t fdread;
    kino_FileDes_fdwrite_t fdwrite;
    kino_FileDes_fdlength_t fdlength;
    kino_FileDes_fdclose_t fdclose;
    kino_RAMFileDes_contents_t contents;
};

extern KINO_RAMFILEDES_VTABLE KINO_RAMFILEDES;

#ifdef KINO_USE_SHORT_NAMES
  #define RAMFileDes kino_RAMFileDes
  #define RAMFILEDES KINO_RAMFILEDES
  #define RAMFileDes_new kino_RAMFileDes_new
  #define RAMFileDes_destroy kino_RAMFileDes_destroy
  #define RAMFileDes_fdseek kino_RAMFileDes_fdseek
  #define RAMFileDes_fdread kino_RAMFileDes_fdread
  #define RAMFileDes_fdwrite kino_RAMFileDes_fdwrite
  #define RAMFileDes_fdlength kino_RAMFileDes_fdlength
  #define RAMFileDes_fdclose kino_RAMFileDes_fdclose
  #define RAMFileDes_contents_t kino_RAMFileDes_contents_t
  #define RAMFileDes_contents kino_RAMFileDes_contents
  #define RAMFileDes_Clone Kino_RAMFileDes_Clone
  #define RAMFileDes_Destroy Kino_RAMFileDes_Destroy
  #define RAMFileDes_Equals Kino_RAMFileDes_Equals
  #define RAMFileDes_Hash_Code Kino_RAMFileDes_Hash_Code
  #define RAMFileDes_Is_A Kino_RAMFileDes_Is_A
  #define RAMFileDes_To_String Kino_RAMFileDes_To_String
  #define RAMFileDes_Serialize Kino_RAMFileDes_Serialize
  #define RAMFileDes_FDSeek Kino_RAMFileDes_FDSeek
  #define RAMFileDes_FDRead Kino_RAMFileDes_FDRead
  #define RAMFileDes_FDWrite Kino_RAMFileDes_FDWrite
  #define RAMFileDes_FDLength Kino_RAMFileDes_FDLength
  #define RAMFileDes_FDClose Kino_RAMFileDes_FDClose
  #define RAMFileDes_Contents Kino_RAMFileDes_Contents
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_RAMFILEDES_MEMBER_VARS \
    chy_u32_t  refcount; \
    char * path; \
    chy_u64_t  pos; \
    chy_i32_t  stream_count; \
    struct kino_VArray * buffers; \
    chy_u64_t  len

#ifdef KINO_WANT_RAMFILEDES_VTABLE
KINO_RAMFILEDES_VTABLE KINO_RAMFILEDES = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_FILEDES,
    "KinoSearch::Store::RAMFileDes",
    (kino_Obj_clone_t)kino_Obj_clone,
    (kino_Obj_destroy_t)kino_RAMFileDes_destroy,
    (kino_Obj_equals_t)kino_Obj_equals,
    (kino_Obj_hash_code_t)kino_Obj_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_Obj_to_string,
    (kino_Obj_serialize_t)kino_Obj_serialize,
    (kino_FileDes_fdseek_t)kino_RAMFileDes_fdseek,
    (kino_FileDes_fdread_t)kino_RAMFileDes_fdread,
    (kino_FileDes_fdwrite_t)kino_RAMFileDes_fdwrite,
    (kino_FileDes_fdlength_t)kino_RAMFileDes_fdlength,
    (kino_FileDes_fdclose_t)kino_RAMFileDes_fdclose,
    (kino_RAMFileDes_contents_t)kino_RAMFileDes_contents
};
#endif /* KINO_WANT_RAMFILEDES_VTABLE */

#undef KINO_RAMFILEDES_BOILERPLATE


#endif /* R_KINO_RAMFILEDES */


/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */

