/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/

#ifndef R_KINO_SCHEMA
#define R_KINO_SCHEMA 1

#include "KinoSearch/Schema.h"

typedef void
(*kino_Schema_destroy_t)(kino_Schema *self);

typedef struct kino_FieldSpec*
(*kino_Schema_fetch_fspec_t)(kino_Schema *self, 
                        const struct kino_ByteBuf *field_name);

typedef struct kino_Similarity*
(*kino_Schema_fetch_sim_t)(kino_Schema *self, 
                      const struct kino_ByteBuf *field_name);

typedef kino_u32_t
(*kino_Schema_num_fields_t)(kino_Schema *self);

#define Kino_Schema_Clone(_self) \
    (_self)->_->clone((kino_Obj*)_self)

#define Kino_Schema_Destroy(_self) \
    (_self)->_->destroy((kino_Obj*)_self)

#define Kino_Schema_Equals(_self, _arg1) \
    (_self)->_->equals((kino_Obj*)_self, _arg1)

#define Kino_Schema_Hash_Code(_self) \
    (_self)->_->hash_code((kino_Obj*)_self)

#define Kino_Schema_Is_A(_self, _arg1) \
    (_self)->_->is_a((kino_Obj*)_self, _arg1)

#define Kino_Schema_To_String(_self) \
    (_self)->_->to_string((kino_Obj*)_self)

#define Kino_Schema_Serialize(_self, _arg1) \
    (_self)->_->serialize((kino_Obj*)_self, _arg1)

#define Kino_Schema_Fetch_FSpec(_self, _arg1) \
    (_self)->_->fetch_fspec((kino_Schema*)_self, _arg1)

#define Kino_Schema_Fetch_Sim(_self, _arg1) \
    (_self)->_->fetch_sim((kino_Schema*)_self, _arg1)

#define Kino_Schema_Num_Fields(_self) \
    (_self)->_->num_fields((kino_Schema*)_self)

struct KINO_SCHEMA_VTABLE {
    KINO_OBJ_VTABLE *_;
    kino_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
    kino_Schema_fetch_fspec_t fetch_fspec;
    kino_Schema_fetch_sim_t fetch_sim;
    kino_Schema_num_fields_t num_fields;
};

extern KINO_SCHEMA_VTABLE KINO_SCHEMA;

#ifdef KINO_USE_SHORT_NAMES
  #define Schema kino_Schema
  #define SCHEMA KINO_SCHEMA
  #define Schema_new kino_Schema_new
  #define Schema_destroy kino_Schema_destroy
  #define Schema_fetch_fspec_t kino_Schema_fetch_fspec_t
  #define Schema_fetch_fspec kino_Schema_fetch_fspec
  #define Schema_fetch_sim_t kino_Schema_fetch_sim_t
  #define Schema_fetch_sim kino_Schema_fetch_sim
  #define Schema_num_fields_t kino_Schema_num_fields_t
  #define Schema_num_fields kino_Schema_num_fields
  #define Schema_Clone Kino_Schema_Clone
  #define Schema_Destroy Kino_Schema_Destroy
  #define Schema_Equals Kino_Schema_Equals
  #define Schema_Hash_Code Kino_Schema_Hash_Code
  #define Schema_Is_A Kino_Schema_Is_A
  #define Schema_To_String Kino_Schema_To_String
  #define Schema_Serialize Kino_Schema_Serialize
  #define Schema_Fetch_FSpec Kino_Schema_Fetch_FSpec
  #define Schema_Fetch_Sim Kino_Schema_Fetch_Sim
  #define Schema_Num_Fields Kino_Schema_Num_Fields
  #define SCHEMA KINO_SCHEMA
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_SCHEMA_MEMBER_VARS \
    struct kino_Similarity * sim; \
    struct kino_Hash * fspecs; \
    struct kino_Hash * sims; \
    void * analyzers; \
    void * analyzer;


#ifdef KINO_WANT_SCHEMA_VTABLE
KINO_SCHEMA_VTABLE KINO_SCHEMA = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_OBJ,
    "KinoSearch::Schema",
    (kino_Obj_clone_t)kino_Obj_clone,
    (kino_Obj_destroy_t)kino_Schema_destroy,
    (kino_Obj_equals_t)kino_Obj_equals,
    (kino_Obj_hash_code_t)kino_Obj_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_Obj_to_string,
    (kino_Obj_serialize_t)kino_Obj_serialize,
    (kino_Schema_fetch_fspec_t)kino_Schema_fetch_fspec,
    (kino_Schema_fetch_sim_t)kino_Schema_fetch_sim,
    (kino_Schema_num_fields_t)kino_Schema_num_fields
};
#endif /* KINO_WANT_SCHEMA_VTABLE */

#endif /* R_KINO_SCHEMA */

/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */
