=head1 NAME

KinoSearch::Docs::Cookbook - Overview

=head1 DESCRIPTION

Each of the recipes in the Cookbook uses the completed
L<Tutorial|KinoSearch::Docs::Tutorial> application as its point of departure.
The materials can be found in the C<sample> directory at the root of the
KinoSearch distribution:

    sample/USConSchema.pm    # custom KinoSearch::Schema subclass
    sample/invindexer.plx    # indexing app
    sample/search.cgi        # search app
    sample/us_constitution   # html documents

=head2 Chapters

=over

=item *

L<KinoSearch::Docs::Cookbook::ReusingSearchers> - Radically improve
search-time performance by using FastCGI or mod_perl and caching a
Searcher/IndexReader. [TODO]

=item *

L<KinoSearch::Docs::Cookbook::ScalingUp> - distribute really large
indexes over multiple machines. [TODO]

=item *

L<KinoSearch::Docs::Cookbook::DynamicFields> - adding fields on the fly
at index-time. [TODO]

=item *

L<KinoSearch::Docs::Cookbook::SubclassingAnalyzer> - Build your own
subclass of Analyzer. [TODO]

=back

=head1 COPYRIGHT

Copyright 2005-2007 Marvin Humphrey

=head1 LICENSE, DISCLAIMER, BUGS, etc.

See L<KinoSearch> version 0.20.

