/** @file */
/***********************************************

 !!!! DO NOT EDIT THIS FILE !!!!

 All content has been auto-generated by 
 the boilerplater.pl utility.

 See boilerplater's documentation for details.

 ***********************************************/



#ifndef R_KINO_SCOREPOSTING
#define R_KINO_SCOREPOSTING 1

#include "KinoSearch/Posting/ScorePosting.h"

#define KINO_SCOREPOSTING_BOILERPLATE

typedef kino_ScorePosting*
(*kino_ScorePost_clone_t)(kino_ScorePosting *self);

typedef void
(*kino_ScorePost_destroy_t)(kino_ScorePosting *self);

typedef void
(*kino_ScorePost_read_record_t)(kino_ScorePosting *self, 
                           struct kino_InStream *instream);

typedef struct kino_RawPosting*
(*kino_ScorePost_read_raw_t)(kino_ScorePosting *self, 
                        struct kino_InStream *instream,
                        chy_u32_t last_doc_num, 
                        struct kino_ByteBuf *term_text, 
                        struct kino_MemoryPool *mem_pool);

typedef void
(*kino_ScorePost_add_batch_to_pool_t)(kino_ScorePosting *self, 
                                 struct kino_PostingPool *post_pool, 
                                 struct kino_TokenBatch *batch, 
                                 struct kino_FieldSpec *fspec, 
                                 chy_u32_t doc_num, float doc_boost, 
                                 float length_norm);

typedef void
(*kino_ScorePost_reset_t)(kino_ScorePosting *self, chy_u32_t doc_num);

typedef struct kino_ScorePostingScorer*
(*kino_ScorePost_make_scorer_t)(kino_ScorePosting *self, 
                           struct kino_Similarity *sim,
                           struct kino_PostingList *plist, 
                           void *weight, float weight_val);

typedef kino_ScorePosting*
(*kino_ScorePost_dupe_t)(kino_ScorePosting *self, struct kino_Similarity *sim);

#define Kino_ScorePost_Clone(self) \
    (self)->_->clone((kino_Obj*)self)

#define Kino_ScorePost_Destroy(self) \
    (self)->_->destroy((kino_Obj*)self)

#define Kino_ScorePost_Equals(self, other) \
    (self)->_->equals((kino_Obj*)self, other)

#define Kino_ScorePost_Hash_Code(self) \
    (self)->_->hash_code((kino_Obj*)self)

#define Kino_ScorePost_Is_A(self, target_vtable) \
    (self)->_->is_a((kino_Obj*)self, target_vtable)

#define Kino_ScorePost_To_String(self) \
    (self)->_->to_string((kino_Obj*)self)

#define Kino_ScorePost_Serialize(self, target) \
    (self)->_->serialize((kino_Obj*)self, target)

#define Kino_ScorePost_Read_Record(self, instream) \
    (self)->_->read_record((kino_Stepper*)self, instream)

#define Kino_ScorePost_Dump(self, instream) \
    (self)->_->dump((kino_Stepper*)self, instream)

#define Kino_ScorePost_Dump_To_File(self, instream, outstream) \
    (self)->_->dump_to_file((kino_Stepper*)self, instream, outstream)

#define Kino_ScorePost_Read_Raw(self, instream, last_doc_num, term_text, mem_pool) \
    (self)->_->read_raw((kino_Posting*)self, instream, last_doc_num, term_text, mem_pool)

#define Kino_ScorePost_Add_Batch_To_Pool(self, post_pool, batch, fspec, doc_num, doc_boost, length_norm) \
    (self)->_->add_batch_to_pool((kino_Posting*)self, post_pool, batch, fspec, doc_num, doc_boost, length_norm)

#define Kino_ScorePost_Reset(self, doc_num) \
    (self)->_->reset((kino_Posting*)self, doc_num)

#define Kino_ScorePost_Make_Scorer(self, sim, plist, weight, weight_val) \
    (self)->_->make_scorer((kino_Posting*)self, sim, plist, weight, weight_val)

#define Kino_ScorePost_Dupe(self, sim) \
    (self)->_->dupe((kino_Posting*)self, sim)

struct KINO_SCOREPOSTING_VTABLE {
    KINO_OBJ_VTABLE *_;
    chy_u32_t refcount;
    KINO_OBJ_VTABLE *parent;
    const char *class_name;
    kino_Obj_clone_t clone;
    kino_Obj_destroy_t destroy;
    kino_Obj_equals_t equals;
    kino_Obj_hash_code_t hash_code;
    kino_Obj_is_a_t is_a;
    kino_Obj_to_string_t to_string;
    kino_Obj_serialize_t serialize;
    kino_Stepper_read_record_t read_record;
    kino_Stepper_dump_t dump;
    kino_Stepper_dump_to_file_t dump_to_file;
    kino_Post_read_raw_t read_raw;
    kino_Post_add_batch_to_pool_t add_batch_to_pool;
    kino_Post_reset_t reset;
    kino_Post_make_scorer_t make_scorer;
    kino_Post_dupe_t dupe;
};

extern KINO_SCOREPOSTING_VTABLE KINO_SCOREPOSTING;

#ifdef KINO_USE_SHORT_NAMES
  #define ScorePosting kino_ScorePosting
  #define SCOREPOSTING KINO_SCOREPOSTING
  #define ScorePost_new kino_ScorePost_new
  #define ScorePost_clone kino_ScorePost_clone
  #define ScorePost_destroy kino_ScorePost_destroy
  #define ScorePost_read_record kino_ScorePost_read_record
  #define ScorePost_read_raw kino_ScorePost_read_raw
  #define ScorePost_add_batch_to_pool kino_ScorePost_add_batch_to_pool
  #define ScorePost_reset kino_ScorePost_reset
  #define ScorePost_make_scorer kino_ScorePost_make_scorer
  #define ScorePost_dupe kino_ScorePost_dupe
  #define ScorePost_Clone Kino_ScorePost_Clone
  #define ScorePost_Destroy Kino_ScorePost_Destroy
  #define ScorePost_Equals Kino_ScorePost_Equals
  #define ScorePost_Hash_Code Kino_ScorePost_Hash_Code
  #define ScorePost_Is_A Kino_ScorePost_Is_A
  #define ScorePost_To_String Kino_ScorePost_To_String
  #define ScorePost_Serialize Kino_ScorePost_Serialize
  #define ScorePost_Read_Record Kino_ScorePost_Read_Record
  #define ScorePost_Dump Kino_ScorePost_Dump
  #define ScorePost_Dump_To_File Kino_ScorePost_Dump_To_File
  #define ScorePost_Read_Raw Kino_ScorePost_Read_Raw
  #define ScorePost_Add_Batch_To_Pool Kino_ScorePost_Add_Batch_To_Pool
  #define ScorePost_Reset Kino_ScorePost_Reset
  #define ScorePost_Make_Scorer Kino_ScorePost_Make_Scorer
  #define ScorePost_Dupe Kino_ScorePost_Dupe
#endif /* KINO_USE_SHORT_NAMES */

#define KINO_SCOREPOSTING_MEMBER_VARS \
    chy_u32_t  refcount; \
    struct kino_Similarity * sim; \
    chy_u32_t  doc_num; \
    chy_u32_t  freq; \
    float  impact; \
    chy_u32_t * prox; \
    chy_u32_t  prox_cap

#ifdef KINO_WANT_SCOREPOSTING_VTABLE
KINO_SCOREPOSTING_VTABLE KINO_SCOREPOSTING = {
    (KINO_OBJ_VTABLE*)&KINO_VIRTUALTABLE,
    1,
    (KINO_OBJ_VTABLE*)&KINO_MATCHPOSTING,
    "KinoSearch::Posting::ScorePosting",
    (kino_Obj_clone_t)kino_ScorePost_clone,
    (kino_Obj_destroy_t)kino_ScorePost_destroy,
    (kino_Obj_equals_t)kino_Obj_equals,
    (kino_Obj_hash_code_t)kino_Obj_hash_code,
    (kino_Obj_is_a_t)kino_Obj_is_a,
    (kino_Obj_to_string_t)kino_Obj_to_string,
    (kino_Obj_serialize_t)kino_Obj_serialize,
    (kino_Stepper_read_record_t)kino_ScorePost_read_record,
    (kino_Stepper_dump_t)kino_Stepper_dump,
    (kino_Stepper_dump_to_file_t)kino_Stepper_dump_to_file,
    (kino_Post_read_raw_t)kino_ScorePost_read_raw,
    (kino_Post_add_batch_to_pool_t)kino_ScorePost_add_batch_to_pool,
    (kino_Post_reset_t)kino_ScorePost_reset,
    (kino_Post_make_scorer_t)kino_ScorePost_make_scorer,
    (kino_Post_dupe_t)kino_ScorePost_dupe
};
#endif /* KINO_WANT_SCOREPOSTING_VTABLE */

#undef KINO_SCOREPOSTING_BOILERPLATE


#endif /* R_KINO_SCOREPOSTING */


/* Copyright 2007 Marvin Humphrey
 *
 * This program is free software; you can redistribute it and/or modify
 * under the same terms as Perl itself.
 */

